/**
 * Libellés du guide « Banners & Mileage » — transplantés VERBATIM de l'ancien site
 * (oracle de contenu). Les TAUX, COÛTS et la liste des limited ne vivent plus
 * ici : ils sont GÉNÉRÉS (recruit.json) ; ne restent que l'éditorial (intros,
 * descriptions de bannières, avertissements) et le marqueur {star}.
 */
import type { LocalizedText } from '@contracts';

export const LABELS = {
  intro: {
    en: 'Understand the banner types and the mileage system in Outerplane to optimize your summons.',
    jp: 'Outerplaneのバナータイプとマイレージシステムを理解して、召喚を最適化しましょう。',
    kr: 'Outerplane의 배너 유형과 마일리지 시스템을 이해하고 소환을 최적화하세요.',
    zh: '了解异域战记中的卡池类型和指定招募系统以优化您的抽取',
    fr: 'Comprenez les types de Banner et le système de Mileage dans Outerplane pour optimiser vos pulls.',
  },

  // ── Introduction paragraphs ──

  intro_p1: {
    en: 'Like most gacha games, Outerplane features a recruitment system with multiple banners, each using different types of resources. This guide explains how banners and the mileage system work in Outerplane.',
    jp: '多くのガチャゲームと同様に、Outerplaneには複数のバナーを持つ募集システムがあり、それぞれ異なるリソースを使用します。このガイドでは、バナーとマイレージシステムの仕組みを説明します。',
    kr: '대부분의 가챠 게임처럼, Outerplane에는 여러 배너를 가진 모집 시스템이 있으며, 각 배너는 서로 다른 재화를 사용합니다. 이 가이드에서는 배너와 마일리지 시스템의 작동 방식을 설명합니다.',
    zh: '与大多数抽卡游戏一样，异域战记拥有多个卡池的招募系统，每个卡池使用不同的资源。本指南将介绍卡池和指定招募系统的运作方式。',
    fr: 'Comme la plupart des jeux gacha, Outerplane propose un système de recrutement avec plusieurs banners, chacune utilisant différents types de ressources. Ce guide explique le fonctionnement des banners et du système de mileage dans Outerplane.',
  },

  intro_p2_before: {
    en: 'Outerplane uses a ',
    jp: 'Outerplaneは',
    kr: 'Outerplane은 ',
    zh: 'Outerplane采用',
    fr: 'Outerplane utilisé un ',
  },
  intro_p2_highlight: {
    en: 'mileage system',
    jp: 'マイレージシステム',
    kr: '마일리지 시스템',
    zh: '指定招募系统',
    fr: 'système de mileage',
  },
  intro_p2_mid: {
    en: '. Mileage allows you to',
    jp: 'を採用しています。マイレージは必要なポイントを集めると',
    kr: '을 사용합니다. 마일리지는 필요한 포인트를 모으면',
    zh: '。指定招募允许你在积累足够点数后',
    fr: ". Le mileage vous permet d'",
  },
  intro_p2_bold: {
    en: ' directly obtain',
    jp: 'ピックアップヒーローを直接獲得',
    kr: ' 픽업 영웅을 직접 획득',
    zh: '直接获取',
    fr: 'obtenir directement',
  },
  intro_p2_after: {
    en: " the featured unit once you've gathered enough points.",
    jp: 'できます。',
    kr: '할 수 있습니다.',
    zh: 'UP同伴。',
    fr: " l'unité mise en avant une fois que vous avez rassemblé suffisamment de points.",
  },

  intro_p3_before: {
    en: 'Each recruit ',
    jp: '各募集',
    kr: '각 모집',
    zh: '每次招募',
    fr: 'Chaque Recruit ',
  },
  intro_p3_bold: {
    en: '(except those using event tickets)',
    jp: '（イベントチケットを除く）',
    kr: '(이벤트 티켓 제외)',
    zh: '（活动券除外）',
    fr: "(sauf ceux utilisant des tickets d'événement)",
  },
  intro_p3_after: {
    en: ' grants 1 mileage. Once you reach the required amount, you can exchange your mileage for the banner unit.',
    jp: 'でマイレージが1加算されます。必要数に達すると、マイレージをバナーヒーローと交換できます。',
    kr: '마다 마일리지가 1 적립됩니다. 필요 수량에 도달하면 마일리지를 배너 영웅과 교환할 수 있습니다.',
    zh: '可获得1点点数。达到所需数量后，可指定招募卡池同伴。',
    fr: " rapporte 1 mileage. Une fois la quantité requise atteinte, vous pouvez échanger votre mileage contre l'unité de la banner.",
  },

  intro_p4_before: {
    en: 'One major advantage of this system is that ',
    jp: 'このシステムの大きな利点は、',
    kr: '이 시스템의 큰 장점은 ',
    zh: '此系统的一大优势是',
    fr: 'Un avantage majeur de ce système est que le ',
  },
  intro_p4_bold1: {
    en: 'mileage is retained',
    jp: 'マイレージがバナー間で引き継がれる',
    kr: '마일리지가 배너 간에 유지',
    zh: '点数在卡池间保留',
    fr: 'mileage est conservé',
  },
  intro_p4_mid: {
    en: ' across banners.',
    jp: 'ことです。',
    kr: '된다는 것입니다.',
    zh: '。',
    fr: ' entre les banners.',
  },
  intro_p4_why: {
    en: 'Why is that useful?',
    jp: 'これが便利な理由は？',
    kr: '이것이 유용한 이유는?',
    zh: '这有什么用？',
    fr: 'En quoi est-ce utile ?',
  },
  intro_p4_scenario: {
    en: "Imagine you do a 10-recruit, get the unit, and also hit the mileage cap. If you're pulling for collection, you can ",
    jp: '10連募集でヒーローを獲得し、同時にマイレージ上限に達したとします。コレクション目的で引いている場合、',
    kr: '10연 모집에서 영웅을 획득하고 동시에 마일리지 상한에 도달했다고 가정해 봅시다. 수집 목적으로 뽑고 있다면, ',
    zh: '假设您满足指定招募的最后10连抽到了同伴。如果是为了收集，便可以',
    fr: "Imaginez que vous fassiez un Recruit x 10, obteniez l'unité et atteigniez aussi le plafond de mileage. Si vous faites des pulls pour la collection, vous pouvez ",
  },
  intro_p4_bold2: {
    en: 'save your mileage',
    jp: 'マイレージを温存',
    kr: '마일리지를 저장',
    zh: '保留点数',
    fr: 'conserver votre mileage',
  },
  intro_p4_end: {
    en: " for a future banner with a unit you're more interested in — or just keep it to secure your next target more efficiently.",
    jp: 'してより興味のあるヒーローの将来のバナーに使用したり、次の目標をより効率的に確保できます。',
    kr: '해서 더 관심 있는 영웅의 미래 배너에 사용하거나, 다음 목표를 더 효율적으로 확보할 수 있습니다.',
    zh: '用于未来更感兴趣的同伴卡池，高效地保证下一个目标。',
    fr: ' pour une future banner avec une unité qui vous intéresse davantage, ou simplement le garder pour sécuriser votre prochaine cible plus efficacement.',
  },

  // ── Recruitment guarantee (pity, 2026-08-25) ──

  intro_p5_before: {
    en: 'Mileage is not the only safety net: most banners also have a ',
    jp: '救済措置はマイレージだけではありません。ほとんどのバナーには',
    kr: '마일리지만이 유일한 안전장치는 아닙니다. 대부분의 배너에는 ',
    zh: '指定招募并非唯一的保障机制。大多数卡池还拥有',
    fr: "Le mileage n'est pas le seul filet de sécurité : la plupart des banners disposent aussi d'une ",
  },
  intro_p5_highlight: {
    en: 'recruitment guarantee',
    jp: '募集確定システム',
    kr: '모집 확정 시스템',
    zh: '招募保底系统',
    fr: 'garantie de Recruit',
  },
  intro_p5_mid: {
    en: ' — a real pity counter. The target hero is guaranteed within ',
    jp: '（いわゆる天井）があり、',
    kr: '(이른바 천장)이 적용되어, ',
    zh: '，即真正的保底：',
    fr: ' — un vrai compteur de pity. Le Héros ciblé est garanti en ',
  },
  intro_p5_bold: {
    en: '100 recruits',
    jp: '100回の募集以内',
    kr: '100회 모집 이내',
    zh: '100次招募以内',
    fr: '100 Recruits',
  },
  intro_p5_after: {
    en: '. It runs entirely separately from mileage: obtaining a hero through the guarantee consumes no mileage at all.',
    jp: 'に対象ヒーローの獲得が確定します。マイレージとは完全に別の仕組みで、確定で獲得してもマイレージは一切消費しません。',
    kr: '에 대상 영웅 획득이 확정됩니다. 마일리지와는 완전히 별개로 작동하며, 확정으로 영웅을 획득해도 마일리지는 전혀 소모되지 않습니다.',
    zh: '必定获得目标同伴。该系统与指定招募完全独立运作，通过保底获得同伴不会消耗任何点数。',
    fr: ' maximum. Ce système fonctionne totalement à part du mileage : obtenir un Héros par la garantie ne consomme aucun mileage.',
  },

  guarantee_rules_label: {
    en: 'THE RULES',
    jp: 'ルール',
    kr: '규칙',
    zh: '规则',
    fr: 'LES RÈGLES',
  },
  guarantee_rule_scope: {
    en: 'Progress is tracked per banner and is never shared between banners.',
    jp: '進行度はバナーごとに管理され、他のバナーとは共有されません。',
    kr: '진행도는 배너별로 관리되며 다른 배너와 공유되지 않습니다.',
    zh: '进度按卡池分别记录，不同卡池之间不共享。',
    fr: 'La progression est suivie banner par banner et ne se partage jamais entre elles.',
  },
  guarantee_rule_early: {
    en: 'Getting the target hero before the 100th recruit still counts as one guarantee, and ends that progress.',
    jp: '100回に達する前に対象ヒーローを獲得した場合も確定1回分として扱われ、その進行度は終了します。',
    kr: '100회에 도달하기 전에 대상 영웅을 획득해도 확정 1회로 계산되며 해당 진행도는 종료됩니다.',
    zh: '在第100次之前获得目标同伴同样计为1次保底，该次进度随之结束。',
    fr: 'Obtenir le Héros ciblé avant le 100e Recruit compte quand même comme une garantie, et met fin à cette progression.',
  },
  guarantee_rule_reset: {
    en: 'On temporary banners, both the guarantees used and the current progress reset when the banner ends — your mileage does not.',
    jp: '期間限定バナーでは、使用した確定回数と進行度がバナー終了時にリセットされます（マイレージはそのまま残ります）。',
    kr: '기간 한정 배너에서는 사용한 확정 횟수와 진행도가 배너 종료 시 초기화됩니다 — 마일리지는 그대로 유지됩니다.',
    zh: '限时卡池结束时，已使用的保底次数和当前进度都会重置——但点数不会。',
    fr: 'Sur les banners temporaires, les garanties utilisées et la progression en cours sont remises à zéro à la fin de la banner — pas votre mileage.',
  },
  guarantee_rule_screen: {
    en: 'The guarantees used and the recruits left before the next one are shown on the Recruitment screen.',
    jp: '使用した確定回数と次の確定までの残り回数は、募集画面で確認できます。',
    kr: '사용한 확정 횟수와 다음 확정까지 남은 모집 횟수는 모집 화면에서 확인할 수 있습니다.',
    zh: '已使用的保底次数和距离下次保底的剩余次数可在招募界面查看。',
    fr: "Le nombre de garanties utilisées et les Recruits restants avant la prochaine s'affichent sur l'écran de Recruit.",
  },
  guarantee_rule_startdash: {
    en: 'Start Dash Recruitment is the exception: it has no guarantee.',
    jp: '選抜スカウトは例外で、確定システムの対象外です。',
    kr: '선별 동료 영입은 예외로, 확정 시스템이 적용되지 않습니다.',
    zh: '甄选招募是例外，不适用保底系统。',
    fr: "Le Start Dash fait exception : il n'a pas de garantie.",
  },

  // ── Banner tabs ──

  pickup: {
    label: {
      en: 'Custom Rate Up',
      jp: 'カスタムピックアップ',
      kr: '커스텀 픽업',
      zh: '自选UP',
      fr: 'Custom Rate Up',
    },
    heading: {
      en: 'Custom Rate Up Banner',
      jp: 'カスタムピックアップ募集',
      kr: '커스텀 픽업 모집',
      zh: '自选UP招募',
      fr: 'Custom Rate Up Banner',
    },
    specialFeature: {
      en: 'Using Recruit x 10 guarantees at least one 2★ hero',
      jp: '10連募集で2★以上のヒーローが1体以上確定',
      kr: '10연 모집 시 2★ 이상 영웅 1체 이상 확정',
      zh: '10连招募保底至少1个2★以上英雄',
      fr: 'Utiliser Recruit x 10 garantit au moins un Héros 2★',
    },
    pity: {
      en: 'Every 100 recruits, one of your 3 selected heroes is guaranteed, picked at random. This one repeats every 100 recruits, with no limit.',
      jp: '100回の募集ごとに、選択した3体のヒーローのいずれかがランダムで確定します。回数制限はなく、100回ごとに何度でも繰り返されます。',
      kr: '100회 모집마다 선택한 3명의 영웅 중 하나가 무작위로 확정됩니다. 횟수 제한 없이 100회마다 반복됩니다.',
      zh: '每100次招募必定获得所选3名同伴中的随机1名。无次数上限，每100次重复触发。',
      fr: 'Tous les 100 Recruits, un de vos 3 Héros sélectionnés est garanti, tiré au hasard. Celle-ci se répète tous les 100 Recruits, sans limite.',
    },
    desc: {
      en: 'This banner is always available. You can choose up to 3 characters to force the drop rate of those.',
      jp: 'このバナーは常設です。最大3体のキャラクターを選択してピックアップ対象にできます。',
      kr: '이 배너는 상시 운영됩니다. 최대 3명의 캐릭터를 선택하여 픽업 대상으로 지정할 수 있습니다.',
      zh: '此卡池常驻开放。你可以选择最多3个角色作为UP目标。',
      fr: "Cette banner est toujours disponible. Vous pouvez choisir jusqu'à 3 personnages pour forcer leur taux de drop.",
    },
    example_label: { en: 'Example:', jp: '例：', kr: '예시:', zh: '例如：', fr: 'Exemple :' },
    example_before: {
      en: ' If you select ',
      jp: ' ',
      kr: ' ',
      zh: ' 选择',
      fr: ' Si vous sélectionnez ',
    },
    example_after: {
      en: ", you can't drop another 3{star} except for those 3.",
      jp: 'を選択すると、3{star}はこの3体以外排出されません。',
      kr: '를 선택하면 이 3명 외에는 3{star}가 배출되지 않습니다.',
      zh: '后，3{star}只会出这3个角色。',
      fr: ", vous ne pouvez pas obtenir d'autres 3{star} en dehors de ces 3.",
    },
    warning: {
      en: "It's not recommended to use Ether on this banner",
      jp: 'このバナーでエーテルを使用することは推奨されません',
      kr: '이 배너에서 에테르 사용은 권장되지 않습니다',
      zh: '不建议在此卡池使用以太',
      fr: "Il n'est pas recommandé d'utiliser de l'Ether sur cette banner",
    },
  },

  rateup: {
    label: {
      en: 'Rate Up Banner',
      jp: 'ピックアップ募集',
      kr: '픽업 모집',
      zh: 'UP招募',
      fr: 'Rate Up Banner',
    },
    heading: {
      en: 'Rate Up Banner',
      jp: 'ピックアップ募集',
      kr: '픽업 모집',
      zh: 'UP招募',
      fr: 'Rate Up Banner',
    },
    specialFeature: {
      en: 'Using Recruit x 10 guarantees at least one 2★ hero',
      jp: '10連募集で2★以上のヒーローが1体以上確定',
      kr: '10연 모집 시 2★ 이상 영웅 1체 이상 확정',
      zh: '10连招募保底至少1个2★以上英雄',
      fr: 'Utiliser Recruit x 10 garantit au moins un Héros 2★',
    },
    pity: {
      en: 'The featured hero is guaranteed within 100 recruits, twice at most per banner. Guarantees used and progress reset when the banner ends.',
      jp: 'ピックアップヒーローは100回の募集以内に確定します。1つのバナーにつき最大2回まで、使用回数と進行度はバナー終了時にリセットされます。',
      kr: '픽업 영웅은 100회 모집 이내에 확정됩니다. 배너당 최대 2회까지이며, 사용 횟수와 진행도는 배너 종료 시 초기화됩니다.',
      zh: 'UP同伴在100次招募以内必定获得，每个卡池最多2次。已使用次数和进度在卡池结束时重置。',
      fr: 'Le Héros en focus est garanti en 100 Recruits maximum, deux fois au plus par banner. Garanties utilisées et progression sont remises à zéro à la fin de la banner.',
    },
    desc: {
      en: 'This banner is temporary and usually lasts ',
      jp: 'このバナーは期間限定で、通常',
      kr: '이 배너는 기간 한정으로, 보통 ',
      zh: '此卡池为限时开放，通常持续',
      fr: 'Cette banner est temporaire et dure généralement ',
    },
    desc_duration: { en: '2 weeks', jp: '2週間', kr: '2주간', zh: '2周', fr: '2 semaines' },
    desc_after: { en: '.', jp: '開催されます。', kr: ' 운영됩니다.', zh: '。', fr: '.' },
    warning: {
      en: "It's not recommended to use Ether on this banner",
      jp: 'このバナーでエーテルを使用することは推奨されません',
      kr: '이 배너에서 에테르 사용은 권장되지 않습니다',
      zh: '不建议在此卡池使用以太',
      fr: "Il n'est pas recommandé d'utiliser de l'Ether sur cette banner",
    },
  },

  premium: {
    label: {
      en: 'Premium Banner',
      jp: 'プレミアム募集',
      kr: '프리미엄 모집',
      zh: '精选招募',
      fr: 'Premium Banner',
    },
    heading: {
      en: 'Premium Banner',
      jp: 'プレミアム募集',
      kr: '프리미엄 모집',
      zh: '精选招募',
      fr: 'Premium Banner',
    },
    pity: {
      en: 'The selected Demiurge hero is guaranteed within 100 recruits, once per Demiurge hero. Progress is tracked separately for each of them: switching your selection resets nothing.',
      jp: '選択中のデミウルゴスヒーローは100回の募集以内に確定し、ヒーロー1体につき1回まで利用できます。進行度はヒーローごとに個別に記録されるため、選択を変更してもリセットされません。',
      kr: '선택한 데미우르고스 영웅은 100회 모집 이내에 확정되며, 영웅 1명당 1회까지 이용할 수 있습니다. 진행도는 영웅별로 따로 기록되므로 선택을 바꿔도 초기화되지 않습니다.',
      zh: '所选创世之神同伴在100次招募以内必定获得，每名创世之神同伴限1次。进度按同伴分别记录，更换所选同伴不会重置进度。',
      fr: 'Le Héros Demiurge sélectionné est garanti en 100 Recruits maximum, une fois par Héros Demiurge. La progression est suivie séparément pour chacun : changer de sélection ne remet rien à zéro.',
    },
    subtext: {
      en: 'Demiurge heroes have about half the drop rate of regular off-banner heroes',
      jp: 'デミウルゴスヒーローの排出率は通常の3★の約半分です',
      kr: '데미우르고스 영웅의 배출 확률은 일반 비픽업 3★의 약 절반입니다',
      zh: '创世之神同伴的掉率约为普通非UP 3★同伴的一半',
      fr: 'Les Héros Demiurge ont environ la moitié du taux de drop des Héros off-banner habituels',
    },
    desc_bold: {
      en: 'Permanent banner',
      jp: '常設バナー',
      kr: '상시 배너',
      zh: '常驻卡池',
      fr: 'Banner permanente',
    },
    desc: {
      en: ' - The only regular way (besides events like Demiurge Contract) to get Demiurge Heroes.',
      jp: ' - デミウルゴスヒーローを獲得できる唯一の通常手段です（デミウルゴス契約などのイベントを除く）。',
      kr: ' - 데미우르고스 영웅을 획득할 수 있는 유일한 일반적인 방법입니다 (데미우르고스 계약 등의 이벤트 제외).',
      zh: ' - 是获取创世之神同伴的唯一常规途径（除创世之神契约等活动外）。',
      fr: " - Le seul moyen régulier (en dehors des événements comme le Demiurge Contract) d'obtenir des Demiurge Heroes.",
    },
    note: {
      en: 'These heroes are extremely powerful but also very rare. Demiurge heroes benefit more from transcendence overall, but some are strong right from base 3{star}.',
      jp: 'これらのヒーローは非常に強力ですが、排出率も非常に低いです。デミウルゴスヒーローは超越の恩恵が大きいですが、3{star}の状態でも強力なヒーローもいます。',
      kr: '이 영웅들은 매우 강력하지만 배출 확률도 매우 낮습니다. 데미우르고스 영웅은 초월의 효과가 크지만, 기본 3{star}에서도 강력한 영웅들이 있습니다.',
      zh: '这些同伴非常强力但掉率极低：她们的超越获益更多，部分在基础3{star}时就很强。',
      fr: 'Ces Héros sont extrêmement puissants mais aussi très rares. Les Héros Demiurge bénéficient davantage de la transcendance, mais certains sont forts dès leur version de base 3{star}.',
    },
  },

  limited: {
    label: {
      en: 'Limited Banner',
      jp: '限定募集',
      kr: '한정 모집',
      zh: '限定招募',
      fr: 'Limited Banner',
    },
    heading: {
      en: 'Limited Banner',
      jp: '限定募集',
      kr: '한정 모집',
      zh: '限定招募',
      fr: 'Limited Banner',
    },
    specialFeature: {
      en: 'Using Recruit x 10 guarantees at least one 2★ hero',
      jp: '10連募集で2★以上のヒーローが1体以上確定',
      kr: '10연 모집 시 2★ 이상 영웅 1체 이상 확정',
      zh: '10连招募保底至少1个2★以上英雄',
      fr: 'Utiliser Recruit x 10 garantit au moins un Héros 2★',
    },
    pity: {
      en: 'The featured hero is guaranteed within 100 recruits, twice at most per banner — Seasonal, Seasonal Limited Hero Selection, Festival and Dimensional Crossroads each count separately. Everything resets when the banner ends.',
      jp: 'ピックアップヒーローは100回の募集以内に確定し、1つのバナーにつき最大2回まで利用できます。シーズナル、シーズナル限定ヒーロー選択、フェスティバル、次元の交差点はそれぞれ別扱いです。すべてバナー終了時にリセットされます。',
      kr: '픽업 영웅은 100회 모집 이내에 확정되며, 배너당 최대 2회까지 이용할 수 있습니다. 시즈널, 시즈널 한정 영웅 선택, 페스티벌, 차원의 교차점은 각각 별개로 계산됩니다. 배너 종료 시 모두 초기화됩니다.',
      zh: 'UP同伴在100次招募以内必定获得，每个卡池最多2次。季节、季节限定同伴选择、节日和次元交叉点各自独立计算，卡池结束时全部重置。',
      fr: 'Le Héros en focus est garanti en 100 Recruits maximum, deux fois au plus par banner — Seasonal, Seasonal Limited Hero Selection, Festival et Dimensional Crossroads comptent chacune séparément. Tout est remis à zéro à la fin de la banner.',
    },
    desc_bold: {
      en: 'Temporary banner',
      jp: '期間限定バナー',
      kr: '기간 한정 배너',
      zh: '限时卡池',
      fr: 'Banner temporaire',
    },
    desc: {
      en: ' - The only way to obtain Limited Heroes.',
      jp: ' - 限定ヒーローを獲得できる唯一の手段です。',
      kr: ' - 한정 영웅을 획득할 수 있는 유일한 방법입니다.',
      zh: ' - 是获取限定同伴的唯一途径。',
      fr: " - Le seul moyen d'obtenir les Limited Heroes.",
    },
    // « Festival » : le nom du jeu (`OUTER_FES`) et celui du tag `festival` ;
    // « Limited » est le GROUPE des trois, pas l'une d'elles.
    type_limited_label: {
      en: 'Festival:',
      jp: 'フェス:',
      kr: '페스티벌:',
      zh: '限定:',
      fr: 'Festival :',
    },
    type_limited_desc: {
      en: 'Classic time-limited heroes',
      jp: '期間限定の通常ヒーロー',
      kr: '기간 한정 일반 영웅',
      zh: '常规限时同伴',
      fr: 'Héros classiques à durée limitée',
    },
    type_seasonal_label: {
      en: 'Seasonal:',
      jp: 'シーズン:',
      kr: '시즌:',
      zh: '季节：',
      fr: 'Seasonal :',
    },
    type_seasonal_desc: {
      en: 'Heroes tied to yearly events like Halloween or Christmas',
      jp: 'ハロウィンやクリスマスなどの季節イベントに関連するヒーロー',
      kr: '할로윈, 크리스마스 등 시즌 이벤트 관련 영웅',
      zh: '与万圣节、圣诞节等年度活动相关的同伴',
      fr: 'Héros liés aux événements annuels comme Halloween ou Noël',
    },
    type_collab_label: { en: 'Collab:', jp: 'コラボ:', kr: '콜라보:', zh: '联动:', fr: 'Collab :' },
    type_collab_desc: {
      en: 'Heroes from crossovers with other licenses (least likely to return)',
      jp: '他作品とのコラボヒーロー。復刻の可能性が最も低い',
      kr: '다른 작품과의 콜라보 영웅. 복각 가능성이 가장 낮음',
      zh: '与其他作品联动的同伴，复刻可能性最低',
      fr: "Héros issus de crossovers avec d'autres licences (les moins susceptibles de revenir)",
    },
    duration_before: {
      en: 'This banner typically runs for ',
      jp: 'このバナーは通常',
      kr: '이 배너는 보통 ',
      zh: '此卡池通常持续',
      fr: 'Cette banner dure généralement ',
    },
    duration_value: {
      en: '2 to 4 weeks',
      jp: '2〜4週間',
      kr: '2~4주간',
      zh: '2至4周',
      fr: '2 à 4 semaines',
    },
    duration_after: {
      en: '. Like Demiurge heroes, Limited units are (usually) extremely powerful, with their strongest abilities unlocking at high transcendence levels.',
      jp: '開催されます。デミウルゴスヒーローと同様に、限定ヒーローは（通常）非常に強力で、高い超越レベルで最強の能力が解放されます。',
      kr: ' 운영됩니다. 데미우르고스 영웅과 마찬가지로, 한정 영웅은 (대체로) 매우 강력하며, 높은 초월 단계에서 가장 강력한 능력이 해금됩니다.',
      zh: '。与创世之神同伴类似，限定同伴（通常）非常强力。其最强能力在最高超越等级解锁。',
      fr: '. Comme les Demiurge Heroes, les unités Limited sont (en général) extrêmement puissantes, leurs capacités les plus fortes se débloquant à un niveau de transcendance élevé.',
    },
    heroes_list_title: {
      en: 'List of Limited Heroes and their release dates:',
      jp: '限定ヒーロー一覧とリリース日:',
      kr: '한정 영웅 목록 및 출시일:',
      zh: '限定列表列表及发布日期:',
      fr: 'Liste des Limited Heroes et leurs dates de sortie :',
    },
    ticket_note: {
      en: "This item exists but hasn't been used yet",
      jp: 'このアイテムは存在しますがまだ使用されていません',
      kr: '이 아이템은 존재하지만 아직 사용된 적 없음',
      zh: '此道具存在但尚未使用过',
      fr: "Cet objet existe mais n'a pas encore été utilisé",
    },
  },

  supply: {
    label: {
      en: 'Dimensional Supply',
      jp: '次元物資召喚',
      kr: '차원 물자 호출',
      zh: '次元物资召唤',
      fr: 'Dimensional Supply',
    },
    heading: {
      en: 'Dimensional Supply Banner',
      jp: '次元物資召喚バナー',
      kr: '차원 물자 호출 배너',
      zh: '次元物资召唤卡池',
      fr: 'Banner Dimensional Supply',
    },
    desc_bold: {
      en: 'Permanent banner',
      jp: '常設バナー',
      kr: '상시 배너',
      zh: '常驻卡池',
      fr: 'Banner permanente',
    },
    desc: {
      en: ' - The only banner that recruits GEAR instead of heroes: 6★ Legendary gear, Talisman Selection Chests and upgrade materials.',
      jp: ' - ヒーローではなく装備を引く唯一のバナー。★6レジェンド装備、タリスマン選択ボックス、育成素材が対象です。',
      kr: ' - 영웅이 아니라 장비를 뽑는 유일한 배너입니다. 6★ 전설 장비, 탈리스만 선택 상자, 육성 재료가 대상입니다.',
      zh: '——唯一抽装备而非同伴的卡池：6★传说装备、护身符选择箱和培养材料。',
      fr: " - La seule banner qui recrute de l'ÉQUIPEMENT et non des Héros : équipement Légendaire 6★, coffres de Talisman et matériaux d'amélioration.",
    },
    unlock: {
      en: 'Unlocks after clearing Story Normal 1-3.',
      jp: 'ストーリーノーマル1-3をクリアで解放されます。',
      kr: '스토리 노말 1-3을 클리어하면 개방됩니다.',
      zh: '通关剧情普通1-3后解锁。',
      fr: "Se débloque en terminant l'histoire Normal 1-3.",
    },
    settings_label: {
      en: 'Rate-Up Gear settings:',
      jp: 'ピックアップ装備の設定：',
      kr: '픽업 장비 설정:',
      zh: '已选装备设置：',
      fr: "Réglage de l'équipement en focus :",
    },
    settings: {
      en: 'Before supplying, you pick 3 pieces of gear and set the main stat and substats you want on them. Those 3 are what the 2% Rate-Up Gear rate points to.',
      jp: '召喚の前に装備を3つ選び、それぞれのメインオプションとサブオプションを設定します。この3つが、2%のピックアップ装備枠の対象です。',
      kr: '호출 전에 장비 3개를 고르고, 각각의 메인 옵션과 서브 옵션을 설정합니다. 이 3개가 2% 픽업 장비 확률의 대상입니다.',
      zh: '召唤前先选择3件装备，并设定其主属性和副属性。这3件就是2%已选装备概率所指向的对象。',
      fr: "Avant de tirer, vous choisissez 3 pièces d'équipement et réglez le stat principal et les substats voulus. Ce sont ces 3 pièces que vise le taux de 2 %.",
    },
    select_before: {
      en: 'Spending your mileage on Select Gear gives you one of those 3 with exactly the stats you configured, and substat levels rolled between ',
      jp: 'マイレージで装備選択を行うと、設定どおりのステータスを持つ1つを獲得でき、サブオプションのレベルは',
      kr: '마일리지로 장비 선택을 하면 설정한 그대로의 옵션을 가진 장비 1개를 획득하며, 서브 옵션 레벨은 ',
      zh: '使用点数进行装备选择时，可获得完全按设定属性的1件装备，副属性等级在',
      fr: 'Dépenser votre mileage en Select Gear vous donne une de ces 3 pièces avec exactement les stats réglées, et des niveaux de substat tirés entre ',
    },
    select_bold: {
      en: '4/3/2/2 and 4/4/3/2',
      jp: '4/3/2/2 ～ 4/4/3/2',
      kr: '4/3/2/2 ~ 4/4/3/2',
      zh: '4/3/2/2 ~ 4/4/3/2',
      fr: '4/3/2/2 et 4/4/3/2',
    },
    select_after: {
      en: '. That 4 is what makes this banner special: it is one of the rare sources that can put a 4th yellow segment on a substat, where everything else caps at 3.',
      jp: 'の範囲で決まります。この「4」がこのバナーの特別な点で、他がほぼ3で頭打ちのところ、サブオプションに4本目の黄色セグメントを乗せられる数少ない入手先です。',
      kr: ' 범위에서 결정됩니다. 이 4가 이 배너의 특별한 점으로, 다른 곳은 대부분 3에서 멈추는 반면 부옵션에 4번째 노란색 세그먼트를 붙일 수 있는 몇 안 되는 출처입니다.',
      zh: '之间决定。这个4正是本卡池的特别之处：其他来源基本止步于3，而它是少数能让副属性出现第4条黄色条段的来源之一。',
      fr: ". Ce 4 est ce qui rend cette banner particulière : c'est une des rares sources capables de poser un 4e segment jaune sur un substat, là où tout le reste plafonne à 3.",
    },
    monthly_label: {
      en: 'MONTHLY CYCLE',
      jp: '月次サイクル',
      kr: '월간 사이클',
      zh: '每月周期',
      fr: 'CYCLE MENSUEL',
    },
    monthly_reset: {
      en: 'Your selection and your progress reset on the 1st of each month. You choose your 3 pieces once per month, and once confirmed they cannot be changed until that reset.',
      jp: '選択と進行度は毎月1日にリセットされます。装備3つの選択は月に1回のみで、確定すると次のリセットまで変更できません。',
      kr: '선택과 진행도는 매월 1일에 초기화됩니다. 장비 3개 선택은 월 1회뿐이며, 확정하면 다음 초기화까지 변경할 수 없습니다.',
      zh: '选择和进度于每月1日重置。每月仅能选择3件装备1次，确认后在下次重置前无法更改。',
      fr: "Votre sélection et votre progression sont remises à zéro le 1er de chaque mois. Vous choisissez vos 3 pièces une fois par mois, et une fois confirmées elles ne changent plus jusqu'à cette remise à zéro.",
    },
    monthly_once: {
      en: 'Each selected piece can be obtained once per month. As soon as one drops, it leaves the pool for the rest of the month.',
      jp: '選択した装備はそれぞれ月に1回まで獲得できます。獲得した装備はその月の残り期間、抽選対象から外れます。',
      kr: '선택한 장비는 각각 월 1회까지 획득할 수 있습니다. 획득한 장비는 그달의 남은 기간 동안 추첨 풀에서 빠집니다.',
      zh: '所选装备每月各可获得1次。一旦获得，该装备在当月剩余时间内将移出奖池。',
      fr: "Chaque pièce sélectionnée s'obtient une fois par mois. Dès qu'elle tombe, elle quitte le pool pour le reste du mois.",
    },
    monthly_rate: {
      en: 'The combined 2% never moves — it is split equally between the pieces you have not obtained yet. With two left, each sits at 1%; the last one alone carries the full 2%.',
      jp: '合計2%は変わりません——まだ獲得していない装備で均等に分けられます。残り2つなら各1%、最後の1つは2%をまるごと背負います。',
      kr: '합계 2%는 그대로입니다 — 아직 획득하지 않은 장비끼리 균등하게 나뉩니다. 2개가 남으면 각각 1%, 마지막 1개는 2%를 전부 가져갑니다.',
      zh: '合计2%的概率不变——它会在尚未获得的装备之间平均分配。剩2件时各为1%，最后1件独占全部2%。',
      fr: 'Les 2 % cumulés ne bougent jamais — ils se répartissent à parts égales entre les pièces pas encore obtenues. À deux restantes, chacune est à 1 % ; la dernière porte les 2 % à elle seule.',
    },
    monthly_close: {
      en: 'Once you have all three, Dimensional Supply closes until the next monthly reset.',
      jp: '3つすべてを獲得すると、次の月次リセットまで次元物資召喚は利用できなくなります。',
      kr: '3개를 모두 획득하면 다음 월간 초기화까지 차원 물자 호출을 이용할 수 없습니다.',
      zh: '集齐3件后，次元物资召唤将关闭，直到下次每月重置。',
      fr: "Une fois les trois obtenues, la Dimensional Supply ferme jusqu'à la remise à zéro du mois suivant.",
    },
    monthly_mileage: {
      en: 'Gear taken with mileage does not count toward that monthly progress.',
      jp: 'マイレージで受け取った装備は、この月次の進行度には数えられません。',
      kr: '마일리지로 받은 장비는 이 월간 진행도에 포함되지 않습니다.',
      zh: '用点数换取的装备不计入该每月进度。',
      fr: 'Une pièce prise au mileage ne compte pas dans cette progression mensuelle.',
    },
    chips_note: {
      en: 'Independently of mileage, every 150 supplies also grant 100 High-Precision Chips.',
      jp: 'マイレージとは別に、150回の召喚ごとに高精密チップを100個獲得できます。',
      kr: '마일리지와 별개로, 150회 호출마다 고정밀 칩 100개를 획득합니다.',
      zh: '与点数无关，每150次召唤还会获得100个高精度芯片。',
      fr: 'Indépendamment du mileage, chaque palier de 150 tirages rapporte aussi 100 High-Precision Chips.',
    },
  },
};

/** Vérification de forme : chaque feuille est un LocalizedText. */
type Leaf = LocalizedText;
type _Check = typeof LABELS extends Record<string, Leaf | Record<string, Leaf>> ? true : never;
const _check: _Check = true;
void _check;
