/**
 * Libellés du guide « Ether Income » — transplantés VERBATIM de la V2
 * (labels.ts, oracle de contenu), à trois différences près :
 *   - les NOMS DE PALIER (arène, ligues world boss) viennent du jeu
 *     (ether-rankings.json) — seuls les gabarits Top/Rank/Below restent ici ;
 *   - les notes de rang (arena/guild/world boss) sont des GABARITS {min}/{max}
 *     remplis depuis les données générées (les nombres V2 étaient périmés —
 *     le jeu a doublé guild raid et world boss) ;
 *   - le titre vit dans meta.json.
 */
import type { LocalizedText } from '@contracts';

export const LABELS = {
  intro: {
    en: "This guide organizes your income into Daily, Weekly, and Monthly sources. Use the Advanced rank adjustments (Arena, Guild Raid, World Boss) to match your account—totals and the date projection update instantly. Event/seasonal rewards are listed separately and aren't counted in the totals.",
    jp: 'このガイドでは収入を日次、週次、月次に分類しています。詳細設定（アリーナ、ギルドレイド、ワールドボス）でアカウントに合わせると、合計と日付予測が即座に更新されます。イベント/シーズン報酬は別途記載され、合計には含まれません。',
    kr: '이 가이드는 수입을 일간, 주간, 월간으로 분류합니다. 고급 랭크 설정(아레나, 길드 레이드, 월드 보스)을 조정하면 합계와 날짜 예측이 즉시 업데이트됩니다. 이벤트/시즌 보상은 별도로 표시되며 합계에 포함되지 않습니다.',
    zh: '本指南将收入分为日常、每周和每月来源。使用高级排名设置（竞技场、公会副本、世界Boss）来匹配您的账号——总计和日期预测会即时更新。活动/季节奖励单独列出，不计入总计。',
    fr: "Ce guide organise vos revenus en sources Daily, Weekly et Monthly. Utilisez les ajustements de rank avancés (Arena, Guild Raid, World Boss) pour les adapter à votre compte. Les totaux et la projection de date se mettent à jour instantanément. Les récompenses d'event/seasonal sont listées à part et ne sont pas comptées dans les totaux.",
  },

  dailyIncome: {
    en: 'Daily income',
    jp: '日次収入',
    kr: '일간 수입',
    zh: '日常收入',
    fr: 'Revenu quotidien',
  },
  weeklyIncome: {
    en: 'Weekly income',
    jp: '週次収入',
    kr: '주간 수입',
    zh: '每周收入',
    fr: 'Revenu hebdomadaire',
  },
  monthlyIncome: {
    en: 'Monthly income',
    jp: '月次収入',
    kr: '월간 수입',
    zh: '每月收入',
    fr: 'Revenu mensuel',
  },
  weeklyTotal: {
    en: 'Weekly Total',
    jp: '週間合計',
    kr: '주간 총합',
    zh: '周总计',
    fr: 'Total Hebdomadaire',
  },
  monthlyTotal: {
    en: 'Monthly Total',
    jp: '月間合計',
    kr: '월간 총합',
    zh: '月总计',
    fr: 'Total Mensuel',
  },
  perDay: {
    en: '/day',
    jp: '/日',
    kr: '/일',
    zh: '/天',
    fr: '/jour',
  },
  advancedAdjustments: {
    en: 'Advanced rank adjustments',
    jp: '詳細ランク設定',
    kr: '고급 랭크 설정',
    zh: '高级排名设置',
    fr: 'Ajustements de rank avancés',
  },
  arena: {
    en: 'Arena',
    jp: 'アリーナ',
    kr: '아레나',
    zh: '竞技场',
    fr: 'Arena',
  },
  guild: {
    en: 'Guild',
    jp: 'ギルド',
    kr: '길드',
    zh: '公会',
    fr: 'Guild',
  },
  worldBoss: {
    en: 'World Boss',
    jp: 'ワールドボス',
    kr: '월드 보스',
    zh: '世界Boss',
    fr: 'World Boss',
  },
  singularity: {
    en: 'Singularity',
    jp: '特異点',
    kr: '특이점',
    zh: '奇点',
    fr: 'Singularity',
  },
  tableDaily: {
    en: 'Daily income',
    jp: '日次収入',
    kr: '일간 수입',
    zh: '日常收入',
    fr: 'Revenu quotidien',
  },
  tableWeekly: {
    en: 'Weekly income',
    jp: '週次収入',
    kr: '주간 수입',
    zh: '每周收入',
    fr: 'Revenu hebdomadaire',
  },
  tableMonthly: {
    en: 'Monthly income',
    jp: '月次収入',
    kr: '월간 수입',
    zh: '每月收入',
    fr: 'Revenu mensuel',
  },
  source: {
    en: 'Source',
    jp: '取得元',
    kr: '출처',
    zh: '来源',
    fr: 'Source',
  },
  daily: {
    en: 'Daily',
    jp: '日次',
    kr: '일간',
    zh: '日常',
    fr: 'Quotidien',
  },
  weekly: {
    en: 'Weekly',
    jp: '週次',
    kr: '주간',
    zh: '每周',
    fr: 'Hebdomadaire',
  },
  monthly: {
    en: 'Monthly',
    jp: '月次',
    kr: '월간',
    zh: '每月',
    fr: 'Mensuel',
  },
  weeklyApprox: {
    en: 'Weekly ≈×7',
    jp: '週≈×7',
    kr: '주≈×7',
    zh: '周≈×7',
    fr: 'Hebdo ≈×7',
  },
  monthlyApprox: {
    en: 'Monthly ≈×30',
    jp: '月≈×30',
    kr: '월≈×30',
    zh: '月≈×30',
    fr: 'Mensuel ≈×30',
  },
  monthlyApprox4: {
    en: 'Monthly ≈×4',
    jp: '月≈×4',
    kr: '월≈×4',
    zh: '月≈×4',
    fr: 'Mensuel ≈×4',
  },
  notes: {
    en: 'Notes',
    jp: '備考',
    kr: '비고',
    zh: '备注',
    fr: 'Notes',
  },
  dailySubtotal: {
    en: 'Daily subtotal',
    jp: '日次小計',
    kr: '일간 소계',
    zh: '日常小计',
    fr: 'Sous-total quotidien',
  },
  weeklySubtotal: {
    en: 'Weekly subtotal',
    jp: '週次小計',
    kr: '주간 소계',
    zh: '每周小计',
    fr: 'Sous-total hebdomadaire',
  },
  monthlySubtotal: {
    en: 'Monthly subtotal',
    jp: '月次小計',
    kr: '월간 소계',
    zh: '每月小计',
    fr: 'Sous-total mensuel',
  },
  variableExcluded: {
    en: 'Variable / Event-Driven (excluded)',
    jp: '変動/イベント報酬（除外）',
    kr: '변동/이벤트 보상 (제외)',
    zh: '变动/活动奖励（不计入）',
    fr: 'Variable / Lié aux Events (exclu)',
  },
  variableTitle: {
    en: 'Extra',
    jp: 'その他',
    kr: '기타',
    zh: '其他',
    fr: 'Extra',
  },
  projection: {
    en: 'Projection until a date',
    jp: '日付までの予測',
    kr: '날짜까지 예측',
    zh: '日期预测',
    fr: "Projection jusqu'à une date",
  },
  endDate: {
    en: 'End date',
    jp: '終了日',
    kr: '종료일',
    zh: '结束日期',
    fr: 'Date de fin',
  },
  currentEther: {
    en: 'Current Ether',
    jp: '現在のエーテル',
    kr: '현재 에테르',
    zh: '当前以太',
    fr: 'Ether actuel',
  },
  days: {
    en: 'Days',
    jp: '日数',
    kr: '일수',
    zh: '天数',
    fr: 'Jours',
  },
  weeks: {
    en: 'Weeks',
    jp: '週数',
    kr: '주수',
    zh: '周数',
    fr: 'Semaines',
  },
  months: {
    en: 'Months',
    jp: '月数',
    kr: '월수',
    zh: '月数',
    fr: 'Mois',
  },
  fromDaily: {
    en: 'From Daily',
    jp: '日次から',
    kr: '일간에서',
    zh: '来自日常',
    fr: 'Depuis Daily',
  },
  fromWeekly: {
    en: 'From Weekly',
    jp: '週次から',
    kr: '주간에서',
    zh: '来自每周',
    fr: 'Depuis Weekly',
  },
  fromMonthly: {
    en: 'From Monthly',
    jp: '月次から',
    kr: '월간에서',
    zh: '来自每月',
    fr: 'Depuis Monthly',
  },
  projectedTotal: {
    en: 'Projected Total',
    jp: '予測合計',
    kr: '예상 총합',
    zh: '预计总计',
    fr: 'Total projeté',
  },
  tierRank: {
    en: 'Rank {n}',
    jp: '{n}位',
    kr: '{n}위',
    zh: '第{n}名',
    fr: 'Rank {n}',
  },
  tierTop: {
    en: 'Top {n}',
    jp: 'Top {n}',
    kr: 'Top {n}',
    zh: 'Top {n}',
    fr: 'Top {n}',
  },
  tierTopPct: {
    en: 'Top {n}%',
    jp: 'Top {n}%',
    kr: 'Top {n}%',
    zh: 'Top {n}%',
    fr: 'Top {n}%',
  },
  tierBelow: {
    en: 'Below Top {n}',
    jp: 'Top {n}以下',
    kr: 'Top {n} 이하',
    zh: 'Top {n}以下',
    fr: 'Sous le Top {n}',
  },
} as const satisfies Record<string, LocalizedText>;

/** Libellés des sources de revenus (verbatim V2). */
export const SOURCE_LABELS: Record<string, LocalizedText> = {
  'daily.missions': {
    en: 'Daily Missions',
    jp: 'デイリーミッション',
    kr: '일일 미션',
    zh: '每日任务',
    fr: 'Daily Missions',
  },
  'daily.arena': {
    en: 'Daily Arena',
    jp: 'デイリーアリーナ',
    kr: '일일 아레나',
    zh: '每日竞技场',
    fr: 'Daily Arena',
  },
  'daily.freePack': {
    en: 'Daily Free Pack',
    jp: 'デイリー無料パック',
    kr: '일일 무료 팩',
    zh: '每日免费礼包',
    fr: 'Pack Gratuit Quotidien',
  },
  'daily.missionEvent': {
    en: 'Daily Mission Event',
    jp: 'デイリーミッションイベント',
    kr: '일일 미션 이벤트',
    zh: '每日任务活动',
    fr: 'Daily Mission Event',
  },
  'daily.antiparticle': {
    en: 'Antiparticle generator (2×12h)',
    jp: '反粒子発生器（2×12時間）',
    kr: '반입자 발생기 (2×12시간)',
    zh: '反粒子发生器（2×12小时）',
    fr: 'Antiparticle Generator (2×12h)',
  },
  'weekly.freePack': {
    en: 'Weekly Free Pack',
    jp: 'ウィークリー無料パック',
    kr: '주간 무료 팩',
    zh: '每周免费礼包',
    fr: 'Pack Gratuit Hebdomadaire',
  },
  'weekly.arena': {
    en: 'Weekly Arena Ranking',
    jp: 'ウィークリーアリーナランキング',
    kr: '주간 아레나 랭킹',
    zh: '每周竞技场排名',
    fr: 'Classement Arena Hebdomadaire',
  },
  'weekly.missions': {
    en: 'Weekly Missions',
    jp: 'ウィークリーミッション',
    kr: '주간 미션',
    zh: '每周任务',
    fr: 'Weekly Missions',
  },
  'weekly.guildCheckin': {
    en: 'Guild Check-in',
    jp: 'ギルドチェックイン',
    kr: '길드 체크인',
    zh: '公会签到',
    fr: 'Check-in Guild',
  },
  'weekly.monadGate': {
    en: 'Monad Gate Weekly Missions',
    jp: 'モナドゲートウィークリーミッション',
    kr: '모나드 게이트 주간 미션',
    zh: '莫纳德之门每周任务',
    fr: 'Missions Hebdomadaires Monad Gate',
  },
  'monthly.freePack': {
    en: 'Monthly Free Pack',
    jp: 'マンスリー無料パック',
    kr: '월간 무료 팩',
    zh: '每月免费礼包',
    fr: 'Pack Gratuit Mensuel',
  },
  'monthly.skywardTower': {
    en: 'Skyward Tower',
    jp: '昇天の塔',
    kr: '승천의 탑',
    zh: '升天之塔',
    fr: 'Skyward Tower',
  },
  'monthly.checkin': {
    en: 'Check-in',
    jp: 'チェックイン',
    kr: '체크인',
    zh: '签到',
    fr: 'Check-in',
  },
  'monthly.maintenance': {
    en: 'Maintenance rewards',
    jp: 'メンテナンス報酬',
    kr: '점검 보상',
    zh: '维护奖励',
    fr: 'Récompenses de Maintenance',
  },
  'monthly.jointMission': {
    en: 'Joint Mission',
    jp: '共同ミッション',
    kr: '합동 미션',
    zh: '联合任务',
    fr: 'Joint Mission',
  },
  'monthly.guildRaid': {
    en: 'Guild Raid Ranking Reward',
    jp: 'ギルドレイドランキング報酬',
    kr: '길드 레이드 랭킹 보상',
    zh: '公会副本排名奖励',
    fr: 'Récompense de Classement Guild Raid',
  },
  'monthly.worldBoss': {
    en: 'World Boss Ranking Reward',
    jp: 'ワールドボスランキング報酬',
    kr: '월드 보스 랭킹 보상',
    zh: '世界Boss排名奖励',
    fr: 'Récompense de Classement World Boss',
  },
  'daily.singularityRanking': {
    en: 'Dimensional Singularity Daily Ranking (Wed–Sat)',
    jp: '次元特異点 デイリーランキング (水〜土)',
    kr: '차원 특이점 일일 랭킹 (수~토)',
    zh: '次元奇点每日排名 (周三~周六)',
    fr: 'Classement Quotidien Dimensional Singularity (Mer-Sam)',
  },
};

/** Notes par source — gabarits {min}/{max}/{league} pour les rangs. */
export const SOURCE_NOTES: Record<string, LocalizedText> = {
  'weekly.arena': {
    en: '{min} minimum. Can go up to {max} for rank 1.',
    jp: '最低{min}。1位で最大{max}。',
    kr: '최소 {min}. 1위 시 최대 {max}.',
    zh: '最低{min}。第1名最高{max}。',
    fr: '{min} minimum. Peut monter à {max} pour le rank 1.',
  },
  'weekly.monadGate': {
    en: '5×10 + 200 completion bonus',
    jp: '5×10 + 200完了ボーナス',
    kr: '5×10 + 200 완료 보너스',
    zh: '5×10 + 200完成奖励',
    fr: '5×10 + 200 bonus de complétion',
  },
  'monthly.maintenance': {
    en: '≈200 every 2 weeks (min)',
    jp: '約200（2週間ごと、最低）',
    kr: '약 200 (2주마다, 최소)',
    zh: '约200（每2周，最低）',
    fr: '≈200 toutes les 2 semaines (min)',
  },
  'monthly.jointMission': {
    en: '80 from Event Mission, do 10 joint challenge runs',
    jp: 'イベントミッションから80、共同チャレンジ10回',
    kr: '이벤트 미션에서 80, 합동 챌린지 10회',
    zh: '活动任务80，完成10次联合挑战',
    fr: '80 via Event Mission, faites 10 runs de joint challenge',
  },
  'monthly.guildRaid': {
    en: '{min} minimum. Can go up to {max} for rank 1.',
    jp: '最低{min}。1位で最大{max}。',
    kr: '최소 {min}. 1위 시 최대 {max}.',
    zh: '最低{min}。第1名最高{max}。',
    fr: '{min} minimum. Peut monter à {max} pour le rank 1.',
  },
  'monthly.worldBoss': {
    en: '{min} minimum. Can go up to {max} for rank 1 in {league}.',
    jp: '最低{min}。{league}1位で最大{max}。',
    kr: '최소 {min}. {league} 1위 시 최대 {max}.',
    zh: '最低{min}。{league}第1名最高{max}。',
    fr: '{min} minimum. Peut monter à {max} pour le rank 1 en {league}.',
  },
};

/** Sources variables/événementielles, exclues des totaux (verbatim V2). */
export const VARIABLE_ITEMS: Record<string, LocalizedText> = {
  'variable.terminus': {
    en: 'Terminus Island Ether rewards (22–26 on treasure reward on Terminus 10) (5 chances everyday ×2 w/ terminus pack)',
    jp: 'ターミナルアイルのエーテル報酬（ターミナル10の宝箱報酬で22〜26）（毎日5回、ターミナルパックで×2）',
    kr: '터미널 아일 에테르 보상 (터미널 10 보물 보상에서 22~26) (매일 5회, 터미널 팩으로 ×2)',
    zh: '终点岛以太奖励（终点10的宝箱奖励22~26）（每天5次，终点礼包×2）',
    fr: "Récompenses d'Ether Terminus Island (22-26 sur la treasure reward de Terminus 10) (5 chances par jour ×2 avec le terminus pack)",
  },
  'variable.updateEvent': {
    jp: '各アップデートのイベント',
    kr: '각 업데이트 이벤트',
    zh: '每次更新活动',
  },
  'variable.sideStories': {
    en: 'New Side Stories every new character (non-premium/limited)',
    jp: '新キャラクターごとの新サイドストーリー（プレミアム/限定除く）',
    kr: '새 캐릭터마다 새 사이드 스토리 (프리미엄/한정 제외)',
    zh: '每个新角色的新外传（精选/限定除外）',
    fr: 'Nouvelles Side Stories pour chaque nouveau personnage (hors Premium/Limited)',
  },
  'variable.coupons': {
    en: 'Coupon codes',
    jp: 'クーポンコード',
    kr: '쿠폰 코드',
    zh: '兑换码',
    fr: 'Codes coupon',
  },
  'variable.seasonalEvents': {
    en: 'Seasonal events (story, point shops, login chains)',
    jp: 'シーズンイベント（ストーリー、ポイントショップ、ログインチェーン）',
    kr: '시즌 이벤트 (스토리, 포인트 상점, 로그인 체인)',
    zh: '季节活动（剧情、积分商店、登录链）',
    fr: 'Events saisonniers (story, point shops, login chains)',
  },
};
