import type { LocalizedText } from '@contracts';

/**
 * Textes du guide « Stats & Combat Mechanics ». Prose 5 langues ; les entités de
 * jeu (stats, buffs/debuffs, skills, persos) sont des TAGS parse-text embarqués
 * ({S/…}, {B/…}, {D/…}, {SK/…|S1}, {P/…}, {C/…}) résolus en strict à l'affichage.
 * `**gras**` marque les emphases (rendu <strong> par l'index).
 */
export const LABELS = {
  // ── Général ──
  title: {
    en: 'Stats & Combat Mechanics',
    jp: 'ステータス＆戦闘メカニクス',
    kr: '스탯 & 전투 메카닉',
    zh: '属性 & 战斗机制',
    fr: 'Stats & Mécaniques de Combat',
  },
  intro: {
    en: 'A comprehensive guide covering stats and combat mechanics in Outerplane.',
    jp: 'Outerplaneのステータスと戦闘メカニクスを網羅したガイドです。',
    kr: 'Outerplane의 스탯과 전투 메카닉을 다루는 종합 가이드입니다.',
    zh: '这是一份关于Outerplane属性和战斗机制的综合指南。',
    fr: "Guide complet sur les stats et les mécaniques de combat d'Outerplane.",
  },

  tab_stats: {
    en: 'Basic Stats',
    jp: '基本ステータス',
    kr: '기본 스탯',
    zh: '基础属性',
    fr: 'Stats de Base',
  },
  tab_combat: {
    en: 'Combat Basics',
    jp: '戦闘の基本',
    kr: '전투 기초',
    zh: '战斗基础',
    fr: 'Bases du Combat',
  },
  tab_faq: { en: 'FAQ', jp: 'FAQ', kr: 'FAQ', zh: '常见问题', fr: 'FAQ' },

  // ── Section Stats ──
  statsHeading: {
    en: 'Core Stats',
    jp: 'コアステータス',
    kr: '핵심 스탯',
    zh: '核心属性',
    fr: 'Stats Principales',
  },
  group_offensive: {
    en: 'Offensive Stats',
    jp: '攻撃系ステータス',
    kr: '공격 스탯',
    zh: '攻击属性',
    fr: 'Stats Offensives',
  },
  group_defensive: {
    en: 'Defensive Stats',
    jp: '防御系ステータス',
    kr: '방어 스탯',
    zh: '防御属性',
    fr: 'Stats Défensives',
  },
  group_utility: {
    en: 'Utility Stats',
    jp: 'ユーティリティステータス',
    kr: '유틸리티 스탯',
    zh: '功能属性',
    fr: 'Stats Utility',
  },
  group_damage: {
    en: 'Damage Modifiers',
    jp: 'ダメージ修正',
    kr: '데미지 보정',
    zh: '伤害修正',
    fr: 'Modificateurs de Dégâts',
  },
  group_effres: {
    en: 'Effectiveness & Resilience',
    jp: '効果命中＆効果抵抗',
    kr: '효과 적중 & 효과 저항',
    zh: '效果命中 & 效果抵抗',
    fr: 'EFF & RES',
  },

  // ── Descriptions courtes (résumé de chaque stat) ──
  desc_ATK: {
    en: 'The higher your attack, the more damage you deal to enemies.',
    jp: '攻撃力が高いほど、敵に与えるダメージが増加します。',
    kr: '공격력이 높을수록 적에게 더 많은 데미지를 줍니다.',
    zh: '攻击力越高，对敌人造成的伤害越大。',
    fr: 'Plus votre ATK est élevée, plus vous infligez de dégâts aux ennemis.',
  },
  desc_CHC: {
    en: 'Chance for a critical hit to occur. When a critical hit occurs, the damage dealt is increased according to critical damage.',
    jp: 'クリティカルヒットが発生する確率。クリティカルヒット時、クリティカルダメージに応じてダメージが増加します。',
    kr: '치명타가 발생할 확률. 치명타 발생 시 치명타 데미지에 따라 데미지가 증가합니다.',
    zh: '触发暴击的概率。暴击时根据暴击伤害增加伤害。',
    fr: "Chance de faire un coup critique. Lors d'un crit, les dégâts sont augmentés selon le CHD.",
  },
  desc_CHD: {
    en: 'Increase Damage upon scoring a critical hit.',
    jp: 'クリティカルヒット時のダメージ増加量。',
    kr: '치명타 적중 시 데미지 증가량.',
    zh: '暴击命中时的伤害增幅。',
    fr: "Augmente les dégâts lors d'un coup critique.",
  },
  desc_PEN: {
    en: "Penetration lets you ignore a portion of the target's Defense.",
    jp: '貫通により、対象の防御力の一部を無視できます。',
    kr: '관통으로 대상 방어력의 일부를 무시할 수 있습니다.',
    zh: '穿透可以忽略目标部分防御力。',
    fr: "PEN vous permet d'ignorer une partie de la DEF de la cible.",
  },
  desc_HP: {
    en: 'You can no longer participate in combat once your Health falls below zero.',
    jp: '体力が0以下になると、戦闘に参加できなくなります。',
    kr: '체력이 0 이하로 떨어지면 전투에 참여할 수 없습니다.',
    zh: '生命值降至0以下时无法继续战斗。',
    fr: 'Vous ne pouvez plus participer au combat si vos HP tombent en dessous de zéro.',
  },
  desc_DEF: {
    en: 'The higher your defense, the less damage you take from enemies.',
    jp: '防御力が高いほど、敵から受けるダメージが減少します。',
    kr: '방어력이 높을수록 적에게 받는 데미지가 감소합니다.',
    zh: '防御力越高，受到的伤害越少。',
    fr: 'Plus votre DEF est élevée, moins vous subissez de dégâts des ennemis.',
  },
  desc_SPD: {
    en: 'The higher the speed, the more often you can act.',
    jp: '速度が高いほど、より頻繁に行動できます。',
    kr: '속도가 높을수록 더 자주 행동할 수 있습니다.',
    zh: '速度越高，行动越频繁。',
    fr: 'Plus la SPD est élevée, plus vous pouvez agir souvent.',
  },
  desc_DMGUP: {
    en: 'Increases damage dealt when attacking.',
    jp: '攻撃時に与えるダメージが増加します。',
    kr: '공격 시 주는 피해량이 증가합니다.',
    zh: '攻击时造成的伤害增加。',
    fr: "Augmente les dégâts infligés lors d'une attaque.",
  },
  desc_DMGRED: {
    en: 'Reduces damage taken when hit.',
    jp: '被弾時に受けるダメージが減少します。',
    kr: '피격 시 받는 피해량이 감소합니다.',
    zh: '受到攻击时承受的伤害减少。',
    fr: "Réduit les dégâts reçus lors d'un hit.",
  },
  desc_CDMGRED: {
    en: 'Reduces damage taken when critically hit.',
    jp: '会心被弾時に受けるダメージが減少します。',
    kr: '치명 피격 시 받는 피해가 감소합니다.',
    zh: '被暴击时受到的伤害减少。',
    fr: "Réduit les dégâts reçus lors d'un coup critique.",
  },
  desc_EFF: {
    en: 'The higher the Effectiveness, the lower the chance the target has to resist debuffs.',
    jp: '効果命中が高いほど、対象がデバフに抵抗する確率が低下します。',
    kr: '효과 적중이 높을수록 대상이 디버프에 저항할 확률이 낮아집니다.',
    zh: '效果命中越高，目标抵抗减益的概率越低。',
    fr: "Plus l'EFF est élevée, plus la chance que la cible résiste aux Debuffs est faible.",
  },
  desc_RES: {
    en: 'The higher the Resilience, the higher the chance to resist debuffs.',
    jp: '効果抵抗が高いほど、デバフに抵抗する確率が上昇します。',
    kr: '효과 저항이 높을수록 디버프에 저항할 확률이 증가합니다.',
    zh: '效果抵抗越高，抵抗减益的概率越高。',
    fr: 'Plus la RES est élevée, plus la chance de résister aux Debuffs est élevée.',
  },

  // ── ATK ──
  atk_p1: {
    en: 'Attack directly increases the raw damage dealt by your skills. However, some skills scale with other stats or ignore Attack entirely.',
    jp: '攻撃力はスキルの基本ダメージを直接増加させます。ただし、一部のスキルは他のステータスに依存するか、攻撃力を完全に無視します。',
    kr: '공격력은 스킬의 기본 데미지를 직접 증가시킵니다. 단, 일부 스킬은 다른 스탯에 의존하거나 공격력을 완전히 무시합니다.',
    zh: '攻击力直接增加技能造成的基础伤害。但部分技能依赖其他属性或完全忽略攻击力。',
    fr: "L'ATK augmente directement les dégâts bruts de vos skills. Cependant, certains skills scalent avec d'autres stats ou ignorent complètement l'ATK.",
  },
  atk_p2: {
    en: 'Some DoTs (damage over time) are impacted by attack:',
    jp: '一部のDoT（継続ダメージ）は攻撃力の影響を受けます：',
    kr: '일부 DoT(지속 데미지)는 공격력의 영향을 받습니다:',
    zh: '部分DoT（持续伤害）受攻击力影响：',
    fr: "Certains DoTs (dégâts sur la durée) sont impactés par l'ATK :",
  },

  // ── CHC ──
  chc_p1: {
    en: 'By default, most characters start with a low base Crit Chance and must build it through gear, buffs, quirks, or passives. Reaching 100% Crit Chance guarantees that every eligible attack will crit.',
    jp: 'デフォルトでは、ほとんどのキャラクターは低い基本クリ率から始まり、装備、バフ、特性、パッシブで上げる必要があります。クリ率100%で、対象となる全ての攻撃がクリティカルになります。',
    kr: '기본적으로 대부분의 캐릭터는 낮은 기본 치명타 확률로 시작하며, 장비, 버프, 특성, 패시브로 올려야 합니다. 치명타 확률 100%에 도달하면 모든 대상 공격이 치명타가 됩니다.',
    zh: '默认情况下，大多数角色初始暴击率较低，需要通过装备、增益、特性或被动来提升。暴击率达到100%可保证每次符合条件的攻击都暴击。',
    fr: 'Par défaut, la plupart des personnages commencent avec un CHC de base faible et doivent le construire via le gear, les Buffs, les Quirks ou les passives. À 100% de CHC, toutes vos attaques éligibles sont garanties de crit.',
  },
  chc_notes: {
    en: 'Important notes:',
    jp: '重要な注意点：',
    kr: '중요 참고:',
    zh: '重要说明：',
    fr: 'Notes importantes :',
  },
  chc_n1: {
    en: 'Crit Chance is capped at 100% — any excess is wasted.',
    jp: 'クリ率は100%が上限で、超過分は無駄になります。',
    kr: '치명타 확률은 100%가 상한이며, 초과분은 낭비됩니다.',
    zh: '暴击率上限为100%——超出部分无效。',
    fr: 'Le CHC est cap à 100% — tout excès est gâché.',
  },
  chc_n2: {
    en: 'Healing and Shielding cannot crit.',
    jp: '回復とシールドはクリティカルしません。',
    kr: '힐과 보호막은 치명타가 되지 않습니다.',
    zh: '治疗和护盾不会暴击。',
    fr: 'Les heals et les shields ne peuvent pas crit.',
  },
  chc_n3: {
    en: 'Skills with {B/HEAVY_STRIKE} effect cannot crit like {SK/Kitsune of Eternity Tamamo-no-Mae|S1}.',
    jp: '{B/HEAVY_STRIKE}効果を持つスキルはクリティカルしません（{SK/Kitsune of Eternity Tamamo-no-Mae|S1}など）。',
    kr: '{B/HEAVY_STRIKE} 효과가 있는 스킬은 치명타가 되지 않습니다({SK/Kitsune of Eternity Tamamo-no-Mae|S1} 등).',
    zh: '带有{B/HEAVY_STRIKE}效果的技能不会暴击，例如{SK/Kitsune of Eternity Tamamo-no-Mae|S1}。',
    fr: 'Skills avec {B/HEAVY_STRIKE} ne peuvent pas crit, comme {SK/Kitsune of Eternity Tamamo-no-Mae|S1}.',
  },
  chc_n4: {
    en: 'Damage over Time effects cannot crit.',
    jp: '継続ダメージ効果はクリティカルしません。',
    kr: '지속 데미지 효과는 치명타가 되지 않습니다.',
    zh: '持续伤害效果不会暴击。',
    fr: 'Les effets DoT ne peuvent pas crit.',
  },

  // ── CHD ──
  chd_p1: {
    en: 'Crit Damage determines how much bonus damage is applied when you land a critical hit. The formula typically multiplies your base damage by a percentage defined by your Crit Dmg stat.',
    jp: 'クリダメはクリティカルヒット時に適用されるボーナスダメージを決定します。計算式は通常、基本ダメージにクリダメ%を乗算します。',
    kr: '치명타 데미지는 치명타 적중 시 적용되는 보너스 데미지를 결정합니다. 계산식은 보통 기본 데미지에 치명타 데미지%를 곱합니다.',
    zh: '暴击伤害决定暴击命中时施加的额外伤害。公式通常将基础伤害乘以暴击伤害百分比。',
    fr: "Le CHD détermine la quantité de dégâts bonus appliquée lors d'un coup critique.",
  },
  chd_p2: {
    en: 'All units start with a base Crit Damage of **150%**.',
    jp: '全てのユニットは基本クリダメ**150%**から始まります。',
    kr: '모든 유닛은 기본 치명타 데미지 **150%**로 시작합니다.',
    zh: '所有单位初始暴击伤害为**150%**。',
    fr: 'Toutes les unités commencent avec un CHD de base de **150%**.',
  },
  chd_p3: {
    en: "Investing in Crit Damage isn't worthwhile if your Crit Chance is low.",
    jp: 'クリ率が低い場合、クリダメに投資する価値はありません。',
    kr: '치명타 확률이 낮으면 치명타 데미지에 투자할 가치가 없습니다.',
    zh: '如果暴击率低，投资暴击伤害不划算。',
    fr: "Investir dans le CHD n'est pas rentable si votre CHC est faible.",
  },

  // ── PEN ──
  pen_p1: {
    en: "Penetration ignores a percentage of the enemy's Defense (DEF) when calculating how much damage your attacks deal. The higher your PEN, the less DEF is counted in the damage reduction formula.",
    jp: '貫通は、ダメージ計算時に敵の防御力（DEF）の一定割合を無視します。貫通が高いほど、ダメージ軽減計算でのDEFの影響が小さくなります。',
    kr: '관통은 데미지 계산 시 적의 방어력(DEF)의 일정 비율을 무시합니다. 관통이 높을수록 데미지 감소 계산에서 DEF의 영향이 줄어듭니다.',
    zh: '穿透在计算攻击伤害时忽略敌人部分防御力（DEF）。穿透越高，伤害减免公式中计入的DEF越少。',
    fr: "La PEN ignore un pourcentage de la DEF de l'ennemi lors du calcul des dégâts de vos attaques. Plus la PEN est élevée, moins la DEF compte dans la formule de réduction de dégâts.",
  },
  pen_p2: {
    en: 'For example, if your target has **2000 DEF** and you have **20% PEN**, it will behave as if they only had **1600 DEF**.',
    jp: '例えば、対象が**2000 DEF**で、あなたが**20% PEN**を持っている場合、対象は**1600 DEF**しか持っていないかのように扱われます。',
    kr: '예를 들어, 대상이 **2000 DEF**이고, 당신이 **20% PEN**을 가지고 있으면, 대상은 **1600 DEF**만 가진 것처럼 처리됩니다.',
    zh: '例如，目标有**2000 DEF**而你有**20% PEN**时，效果等同于目标只有**1600 DEF**。',
    fr: "Par exemple, si votre cible a **2000 DEF** et que vous avez **20% PEN**, cela se comporte comme si elle n'avait que **1600 DEF**.",
  },
  pen_p3: {
    en: 'Penetration becomes more valuable against tanky enemies with high DEF.',
    jp: '貫通は高DEFの耐久型の敵に対してより効果的です。',
    kr: '관통은 높은 DEF의 탱커형 적에게 더 효과적입니다.',
    zh: '穿透对高防御的肉盾型敌人更有价值。',
    fr: 'La PEN devient plus précieuse contre les ennemis tank avec une DEF élevée.',
  },
  pen_p4: {
    en: 'Penetration is capped at 100% — any excess is wasted.',
    jp: '貫通は100%が上限で、超過分は無駄になります。',
    kr: '관통은 100%가 상한이며, 초과분은 낭비됩니다.',
    zh: '穿透上限为100%——超出部分无效。',
    fr: 'La PEN est plafonnée à 100% — tout excès est gâché.',
  },
  pen_note: {
    en: '**Note:** If the enemy has 0 defense (like in joint battle), penetration becomes useless.',
    jp: '**注意：** 敵の防御力が0の場合（共同戦闘など）、貫通は無意味になります。',
    kr: '**참고:** 적의 방어력이 0이면(합동 전투 등) 관통은 무의미해집니다.',
    zh: '**注意：** 如果敌人防御为0（如联合战斗），穿透将毫无用处。',
    fr: "**Note :** Si l'ennemi a 0 DEF (comme en joint battle), la PEN devient inutile.",
  },

  // ── HP ──
  hp_p1: {
    en: 'Health represents the total amount of damage a unit can take before being defeated. Once HP reaches 0, the unit is immediately removed from combat.',
    jp: '体力は、ユニットが倒されるまでに受けられるダメージの総量を表します。HPが0になると、そのユニットは即座に戦闘から除外されます。',
    kr: '체력은 유닛이 쓰러지기 전 받을 수 있는 총 데미지량입니다. HP가 0이 되면 즉시 전투에서 제외됩니다.',
    zh: '生命值代表单位被击败前可承受的总伤害量。HP归零时立即退出战斗。',
    fr: "Les HP représentent la quantité totale de dégâts qu'une unité peut subir avant d'être vaincue. Quand les HP atteignent 0, l'unité est immédiatement retirée du combat.",
  },
  hp_p2: {
    en: 'Like Attack, some skills scale with HP, such as {SK/Demiurge Drakhan|S1}.',
    jp: '攻撃力と同様に、一部のスキルはHPに依存します（{SK/Demiurge Drakhan|S1}など）。',
    kr: '공격력처럼 일부 스킬은 HP에 의존합니다({SK/Demiurge Drakhan|S1} 등).',
    zh: '与攻击力类似，部分技能依赖HP，例如{SK/Demiurge Drakhan|S1}。',
    fr: "Comme l'ATK, certains skills scalent avec les HP, comme {SK/Demiurge Drakhan|S1}.",
  },
  hp_p3: {
    en: 'You can replenish HP with healing skills, and protect it with buffs like:',
    jp: '回復スキルでHPを補充し、以下のようなバフで保護できます：',
    kr: '힐 스킬로 HP를 회복하고, 다음 버프로 보호할 수 있습니다:',
    zh: '可以用治疗技能补充HP，并用以下增益保护：',
    fr: 'Vous pouvez restaurer les HP avec des skills de heal et les protéger avec des Buffs comme :',
  },

  // ── DEF ──
  def_p1: {
    en: 'Defense reduces the amount of damage taken from most sources. Some skills scale with defense like {SK/Caren|S3}.',
    jp: '防御力はほとんどのソースから受けるダメージを軽減します。一部のスキルは防御力に依存します（{SK/Caren|S3}など）。',
    kr: '방어력은 대부분의 소스에서 받는 데미지를 줄입니다. 일부 스킬은 방어력에 의존합니다({SK/Caren|S3} 등).',
    zh: '防御力减少大部分来源的受到伤害。部分技能依赖防御力，例如{SK/Caren|S3}。',
    fr: 'La DEF réduit la quantité de dégâts subis de la plupart des sources. Certains skills scalent avec la DEF comme {SK/Caren|S3}.',
  },
  def_p2: {
    en: 'However, some in-game mechanics can partially or completely ignore DEF, such as:',
    jp: 'ただし、一部のゲーム内メカニクスはDEFを部分的または完全に無視できます：',
    kr: '하지만 일부 게임 메카닉은 DEF를 부분적 또는 완전히 무시할 수 있습니다:',
    zh: '但部分游戏机制可以部分或完全忽略DEF，例如：',
    fr: 'Cependant, certaines mécaniques in-game peuvent ignorer partiellement ou complètement la DEF, comme :',
  },

  // ── SPD ──
  spd_p1: {
    en: "Speed determines how quickly a unit's turn comes. The higher the SPD, the more frequently a unit can act during combat.",
    jp: '速度は、ユニットのターンがどれだけ早く来るかを決定します。SPDが高いほど、戦闘中により頻繁に行動できます。',
    kr: '속도는 유닛의 턴이 얼마나 빨리 오는지 결정합니다. SPD가 높을수록 전투 중 더 자주 행동할 수 있습니다.',
    zh: '速度决定单位多快轮到行动。SPD越高，战斗中行动越频繁。',
    fr: "La SPD détermine la rapidité avec laquelle un tour arrive. Plus la SPD est élevée, plus l'unité peut agir fréquemment en combat.",
  },
  spd_p2: {
    en: 'Like Attack, some skills scale with SPD, such as {SK/Stella|S2}.',
    jp: '攻撃力と同様に、一部のスキルはSPDに依存します（{SK/Stella|S2}など）。',
    kr: '공격력처럼 일부 스킬은 SPD에 의존합니다({SK/Stella|S2} 등).',
    zh: '与攻击力类似，部分技能依赖SPD，例如{SK/Stella|S2}。',
    fr: "Comme l'ATK, certains skills scalent avec la SPD, comme {SK/Stella|S2}.",
  },
  spd_p3: {
    en: 'Further details are provided in the **Combat Basics** section, since Speed is directly linked to the concept of "Priority".',
    jp: '速度は「優先度」の概念と直接関連しているため、詳細は**戦闘の基本**セクションで説明します。',
    kr: '속도는 "우선도" 개념과 직접 연결되어 있으므로, 자세한 내용은 **전투 기초** 섹션에서 설명합니다.',
    zh: '速度与"行动值"概念直接相关，详见**战斗基础**部分。',
    fr: 'Plus de détails sont fournis dans la **Bases du Combat** section, car la SPD est directement liée au concept de "Priorité".',
  },

  // ── DMG UP% ──
  dmgup_p1: {
    en: 'Damage Increase boosts the damage you deal when attacking. It is part of an **additive system** where all increase-type and reduction-type effects are summed, then subtracted from each other — not multiplied independently.',
    jp: 'ダメージ増加は攻撃時に与えるダメージを上昇させます。これは**加算システム**の一部であり、すべての増加系および減少系の効果が合算され、互いに減算されます（独立して乗算されるわけではありません）。',
    kr: '피해 증가는 공격 시 주는 데미지를 상승시킵니다. 이는 **합산 시스템**의 일부로, 모든 증가형 및 감소형 효과가 합산된 뒤 서로 차감됩니다(독립적으로 곱해지지 않습니다).',
    zh: '伤害增加提升攻击时造成的伤害。它属于一个**加算系统**，所有增益类和减免类效果先各自求和，再相减，而非独立相乘。',
    fr: "Le DMG UP augmente les dégâts que vous infligez à l'attaque. Il fait partie d'un **système additif** où tous les effets d'increase et de réduction sont sommés, puis soustraits les uns des autres — pas multipliés indépendamment.",
  },
  dmgup_formulaLabel: {
    en: 'Additive formula:',
    jp: '加算式：',
    kr: '합산 공식:',
    zh: '加算公式：',
    fr: 'Formule additive :',
  },
  dmgup_formula: {
    en: '(CHD + DMG UP + Skill/Equip DMG UP) − (CDMG RED + DMG RED + Skill/Equip DMG RED) = Final modifier',
    jp: '(CHD + DMG UP + Skill/Equip DMG UP) − (CDMG RED + DMG RED + Skill/Equip DMG RED) = Final modifier',
    kr: '(CHD + DMG UP + Skill/Equip DMG UP) − (CDMG RED + DMG RED + Skill/Equip DMG RED) = Final modifier',
    zh: '(CHD + DMG UP + Skill/Equip DMG UP) − (CDMG RED + DMG RED + Skill/Equip DMG RED) = Final modifier',
    fr: '(CHD + DMG UP + DMG UP de Skill/Equip) − (CDMG RED + DMG RED + DMG RED de Skill/Equip) = Modificateur final',
  },
  dmgup_howLabel: {
    en: 'How it works:',
    jp: '仕組み：',
    kr: '작동 방식:',
    zh: '运作方式：',
    fr: 'Fonctionnement :',
  },
  dmgup_h1: {
    en: 'On a non-crit hit: {S/DMG UP%} (+ any skill/equip bonuses) is opposed by the enemy’s {S/DMG RED%} (+ their skill/equip reductions).',
    jp: '非クリティカル時：{S/DMG UP%}（+スキル/装備のボーナス）が敵の{S/DMG RED%}（+スキル/装備の軽減）と対抗します。',
    kr: '비치명 시: {S/DMG UP%}(+ 스킬/장비 보너스)이 적의 {S/DMG RED%}(+ 스킬/장비 감소)와 대항합니다.',
    zh: '非暴击时：{S/DMG UP%}（+技能/装备加成）与敌方的{S/DMG RED%}（+技能/装备减免）相对抗。',
    fr: "Sur un hit non-crit : {S/DMG UP%} (+ bonus de skill/equip) est opposé au {S/DMG RED%} de l'ennemi (+ ses réductions de skill/equip).",
  },
  dmgup_h2: {
    en: 'On a crit hit: {S/DMG UP%} is added to your {S/CHD}, and the enemy adds their {S/CDMG RED%} to their {S/DMG RED%}. Both totals are then compared.',
    jp: 'クリティカル時：{S/DMG UP%}が自身の{S/CHD}に加算され、敵は{S/CDMG RED%}を自身の{S/DMG RED%}に加算します。その後、両者の合計が比較されます。',
    kr: '치명 시: {S/DMG UP%}이 자신의 {S/CHD}에 합산되고, 적은 {S/CDMG RED%}를 자신의 {S/DMG RED%}에 합산합니다. 그 후 두 합계가 비교됩니다.',
    zh: '暴击时：{S/DMG UP%}加到自身的{S/CHD}上，敌方则将{S/CDMG RED%}加到自身的{S/DMG RED%}上。随后比较双方总计。',
    fr: "Sur un crit : {S/DMG UP%} est ajouté à votre {S/CHD}, et l'ennemi ajoute son {S/CDMG RED%} à son {S/DMG RED%}. Les deux totaux sont ensuite comparés.",
  },
  dmgup_h3: {
    en: 'When total damage reductions exceed total damage increases, the final modifier is floored at −70% (rate floor 0.30).',
    jp: '軽減の合計が増加の合計を上回る場合、最終修正値は−70%で下限に達します（レートフロア0.30）。',
    kr: '총 감소가 총 증가를 초과하면 최종 보정치는 −70%로 하한 처리됩니다(레이트 하한 0.30).',
    zh: '当减免总和超过增益总和时，最终修正值以−70%为下限（速率下限0.30）。',
    fr: 'Quand les réductions totales dépassent les augmentations totales, le modificateur final est plancheré à −70% (floor de 0.30).',
  },
  dmgup_note: {
    en: '**Note:** Damage Increase from quirks, skills, and equipment effects are all part of this same additive pool.',
    jp: '**注意：** クイーク、スキル、装備効果によるダメージ増加は、すべてこの同じ加算プールの一部です。',
    kr: '**참고:** 특성, 스킬, 장비 효과로 인한 피해 증가는 모두 이 동일한 합산 풀의 일부입니다.',
    zh: '**注意：** 来自特性、技能和装备效果的伤害增加，全部属于同一个加算池。',
    fr: "**Note :** Le DMG UP venant des Quirks, skills et effets d'équipement fait partie du même pool additif.",
  },
  dmgup_chdNote: {
    en: 'Here CHD is expressed in percentage points (a CHD of 150% counts as 150); in the full FAQ formula it appears in decimal form (1.5).',
    jp: 'ここではCHDをパーセントポイントで表記しています（CHD 150%は150として計算）。FAQの完全な計算式では小数（1.5）で表されます。',
    kr: '여기서 CHD는 퍼센트 포인트로 표기됩니다(CHD 150%는 150으로 계산). FAQ의 전체 공식에서는 소수(1.5)로 표시됩니다.',
    zh: '此处CHD以百分点表示（CHD 150%记为150）；在FAQ的完整公式中则以小数（1.5）表示。',
    fr: 'Ici la CHD est exprimée en points de % (une CHD de 150% compte pour 150) ; dans la formule complète de la FAQ elle apparaît en décimal (1.5).',
  },

  // ── DMG RED% ──
  dmgred_p1: {
    en: 'Damage Reduction is **not** a standalone flat percentage reduction. It is part of the same additive system as {S/DMG UP%} — it is subtracted from the attacker’s total Damage Increase group. This layer is calculated **before** Defense.',
    jp: '被ダメージ減少は、単独の平坦な割合軽減では**ありません**。これは{S/DMG UP%}と同じ加算システムの一部であり、攻撃側のダメージ増加グループの合計から減算されます。この層は防御力の**前**に計算されます。',
    kr: '받는 피해 감소는 단독의 평탄한 비율 감소가 **아닙니다**. 이는 {S/DMG UP%}과 동일한 합산 시스템의 일부로, 공격자의 피해 증가 그룹 합계에서 차감됩니다. 이 층은 방어력 **이전**에 계산됩니다.',
    zh: '受到伤害减少并**不是**一个独立的平坦百分比减免。它与{S/DMG UP%}属于同一个加算系统——从攻击方的伤害增加总组中减去。该层在防御力**之前**计算。',
    fr: "Le DMG RED **n'est pas** une réduction plate en pourcentage. Il fait partie du même système additif que {S/DMG UP%} — il est soustrait du groupe Damage Increase total de l'attaquant. Cette couche est calculée **avant** la DEF.",
  },
  dmgred_exLabel: {
    en: 'Example (non-crit):',
    jp: '例（非クリティカル）：',
    kr: '예시(비치명):',
    zh: '示例（非暴击）：',
    fr: 'Exemple (non-crit) :',
  },
  dmgred_ex: {
    en: 'If the attacker has **50% DMG UP** and you have **30% DMG RED**, the net modifier is **+20%** damage increase (not a flat 30% reduction).',
    jp: '攻撃側が**50% DMG UP**で、あなたが**30% DMG RED**の場合、最終的な修正値は**+20%**のダメージ増加になります（平坦な30%軽減ではありません）。',
    kr: '공격자가 **50% DMG UP**이고 당신이 **30% DMG RED**이면, 최종 보정치는 **+20%**의 피해 증가입니다(평탄한 30% 감소가 아닙니다).',
    zh: '若攻击方拥有**50% DMG UP**且你拥有**30% DMG RED**，则净修正为**+20%**的伤害增加（并非平坦的30%减免）。',
    fr: "Si l'attaquant a **50% DMG UP** et que vous avez **30% DMG RED**, le modificateur net est **+20%** d'augmentation de dégâts (pas une réduction plate de 30%).",
  },
  dmgred_critLabel: {
    en: 'On a crit hit:',
    jp: 'クリティカル時：',
    kr: '치명 시:',
    zh: '暴击时：',
    fr: 'Sur un crit :',
  },
  dmgred_crit: {
    en: '{S/DMG RED%} is added to your {S/CDMG RED%} to oppose the enemy’s {S/CHD} + {S/DMG UP%}.',
    jp: '{S/DMG RED%}が自身の{S/CDMG RED%}に加算され、敵の{S/CHD} + {S/DMG UP%}に対抗します。',
    kr: '{S/DMG RED%}가 자신의 {S/CDMG RED%}에 합산되어 적의 {S/CHD} + {S/DMG UP%}에 대항합니다.',
    zh: '{S/DMG RED%}加到自身的{S/CDMG RED%}上，以对抗敌方的{S/CHD} + {S/DMG UP%}。',
    fr: "{S/DMG RED%} est ajouté à votre {S/CDMG RED%} pour s'opposer au {S/CHD} + {S/DMG UP%} de l'ennemi.",
  },
  dmgred_note: {
    en: '**Note:** This is not the same as Final Damage Reduction, which is applied separately after Defense.',
    jp: '**注意：** これは最終ダメージ軽減とは異なります。最終ダメージ軽減は防御力の後に別途適用されます。',
    kr: '**참고:** 이것은 최종 데미지 감소와는 다릅니다. 최종 데미지 감소는 방어력 이후에 별도로 적용됩니다.',
    zh: '**注意：** 这与最终伤害减免不同，最终伤害减免在防御力之后单独应用。',
    fr: "**Note :** Ce n'est pas la même chose que la Final Damage Reduction, qui est appliquée séparément après la DEF.",
  },
  dmg_cap: {
    en: '**Cap:** The combined pool (CHD + DMG UP) − (DMG RED + CDMG RED) has a rate floor of 0.30: this layer caps reduction at −70%. Defense and Final Damage Reduction are calculated separately.',
    jp: '**上限：** 統合プール（CHD + DMG UP）−（DMG RED + CDMG RED）には0.30のレートフロアがあり、この層は軽減を−70%で頭打ちにします。防御力と最終ダメージ軽減は別途計算されます。',
    kr: '**상한:** 통합 풀 (CHD + DMG UP) − (DMG RED + CDMG RED)에는 0.30의 레이트 하한이 있어, 이 층은 감소를 −70%로 제한합니다. 방어력과 최종 데미지 감소는 별도로 계산됩니다.',
    zh: '**上限：** 合并池 (CHD + DMG UP) − (DMG RED + CDMG RED) 有 0.30 的速率下限：该层将减免上限限制为 −70%。防御力和最终伤害减免单独计算。',
    fr: '**Cap :** Le pool combiné (CHD + DMG UP) − (DMG RED + CDMG RED) est plancheré à 0.30 : cette couche plafonne à −70% de réduction. La DEF et la Final Damage Reduction sont calculées séparément.',
  },

  // ── CDMG RED% ──
  cdmgred_p1: {
    en: 'Critical Damage Reduction only activates when you are critically hit. It is added to your {S/DMG RED%} to form the total defensive pool, which is subtracted from the attacker’s offensive pool ({S/CHD} + {S/DMG UP%}).',
    jp: '会心ダメージ減少は、会心被弾時に敵の有効{S/CHD}を直接減少させます。',
    kr: '치명 피해 감소는 치명 피격 시 적의 유효 {S/CHD}를 직접 감소시킵니다.',
    zh: '暴击伤害减免在被暴击时直接降低敌方的有效{S/CHD}。',
    fr: "Le CDMG RED ne s'active que lorsque vous subissez un coup critique. Il est ajouté à votre {S/DMG RED%} pour former le pool défensif total, qui est soustrait du pool offensif de l'attaquant ({S/CHD} + {S/DMG UP%}).",
  },
  cdmgred_exLabel: { en: 'Example:', jp: '例：', kr: '예시:', zh: '示例：', fr: 'Exemple :' },
  cdmgred_ex1: {
    en: 'If the enemy has **300% CHD** + **30% DMG UP** and you have **150% CDMG RED** + **20% DMG RED**:',
    jp: '敵の**CHD 300%**に対して**CDMG RED 150%**を持つ場合、受ける会心ダメージは300%ではなく**150%**に減少します。',
    kr: '적의 **CHD 300%**에 대해 **CDMG RED 150%**를 가지고 있으면, 받는 치명 데미지가 300%가 아닌 **150%**로 감소합니다.',
    zh: '敌方**CHD 300%**，你拥有**CDMG RED 150%**时，受到的暴击伤害从300%降至**150%**。',
    fr: "Si l'ennemi a **300% CHD** + **30% DMG UP** et que vous avez **150% CDMG RED** + **20% DMG RED** :",
  },
  cdmgred_ex2: {
    en: '(300 + 30) − (150 + 20) = **+160%** effective damage modifier.',
    jp: 'クリティカル被弾時：CDMG REDは{S/DMG RED%}に加算され、敵の{S/CHD} + {S/DMG UP%}に対する総防御修正値を形成します。',
    kr: '치명 피격 시: CDMG RED가 {S/DMG RED%}에 합산되어 적의 {S/CHD} + {S/DMG UP%}에 대한 총 방어 보정치를 형성합니다.',
    zh: '被暴击时：CDMG RED与{S/DMG RED%}相加，形成对敌方{S/CHD} + {S/DMG UP%}的总防御修正。',
    fr: '(300 + 30) − (150 + 20) = **+160%** de modificateur effectif.',
  },
  cdmgred_note: {
    en: '**Note:** CDMG RED has no effect on non-crit hits.',
    jp: '',
    kr: '',
    zh: '',
    fr: "**Note :** Le CDMG RED n'a aucun effet sur les hits non-crit.",
  },

  // ── EFF ──
  eff_p1: {
    en: 'Effectiveness increases the chance of successfully applying debuffs and is countered by {S/RES}.',
    jp: '効果命中はデバフ付与の成功確率を上げ、{S/RES}で対抗されます。',
    kr: '효과 적중은 디버프 부여 성공 확률을 높이며, {S/RES}로 대응됩니다.',
    zh: '效果命中增加成功施加减益的概率，被{S/RES}对抗。',
    fr: "L'EFF augmente la chance d'appliquer un debuff avec succès et est contrée par {S/RES}.",
  },
  eff_p2: {
    en: "If your Effectiveness is equal to or higher than the enemy's Resilience, the base chance to apply a debuff is 100%.",
    jp: '効果命中が敵の効果抵抗以上の場合、デバフ付与の基本確率は100%です。',
    kr: '효과 적중이 적의 효과 저항 이상이면 디버프 부여 기본 확률은 100%입니다.',
    zh: '当效果命中大于等于敌人效果抵抗时，减益施加基础概率为100%。',
    fr: "Si votre EFF est supérieure ou égale à la RES de l'ennemi, la chance de base d'appliquer un debuff est de 100%.",
  },
  eff_p3: {
    en: "Some skills can scale with Effectiveness, such as {P/Gnosis Beth}'s {D/ETERNAL_BLEEDING}.",
    jp: '一部のスキルは効果命中に依存します（{P/Gnosis Beth}の{D/ETERNAL_BLEEDING}など）。',
    kr: '일부 스킬은 효과 적중에 의존합니다({P/Gnosis Beth}의 {D/ETERNAL_BLEEDING} 등).',
    zh: '部分技能依赖效果命中，例如{P/Gnosis Beth}的{D/ETERNAL_BLEEDING}。',
    fr: "Certains skills peuvent scaler avec l'EFF, comme avec {P/Gnosis Beth} avec {D/ETERNAL_BLEEDING}.",
  },

  // ── RES ──
  res_p1: {
    en: 'Resilience reduces the chance of receiving debuffs and is countered by {S/EFF}. You can be immune to debuff with the {B/BT_IMMUNE} buff.',
    jp: '効果抵抗はデバフを受ける確率を下げ、{S/EFF}で対抗されます。{B/BT_IMMUNE}バフでデバフ無効になれます。',
    kr: '효과 저항은 디버프를 받을 확률을 낮추며, {S/EFF}로 대응됩니다. {B/BT_IMMUNE} 버프로 디버프 면역이 됩니다.',
    zh: '效果抵抗降低被施加减益的概率，被{S/EFF}对抗。{B/BT_IMMUNE}增益可使你免疫减益。',
    fr: 'La RES réduit la chance de recevoir des debuffs et est contrée par {S/EFF}. Vous pouvez être immunisé aux debuffs avec le buff {B/BT_IMMUNE}.',
  },
  res_p2: {
    en: "When your RES is higher than the enemy's EFF:",
    jp: '効果抵抗が敵の効果命中より高い場合：',
    kr: '효과 저항이 적의 효과 적중보다 높을 때:',
    zh: '当效果抵抗高于敌人效果命中时：',
    fr: "Lorsque votre RES est supérieure à l'EFF de l'ennemi :",
  },
  res_b1: {
    en: 'RES − EFF = 0 → 100% chance',
    jp: 'RES − EFF = 0 → 100%確率',
    kr: 'RES − EFF = 0 → 100% 확률',
    zh: 'RES − EFF = 0 → 100%概率',
    fr: 'RES − EFF = 0 → 100% de chance',
  },
  res_note: {
    en: 'Note: Some skills bypass the resilience check like {SK/Drakhan|S2}.',
    jp: '注意：一部のスキルは効果抵抗チェックを回避します（{SK/Drakhan|S2}など）。',
    kr: '참고: 일부 스킬은 효과 저항 체크를 우회합니다({SK/Drakhan|S2} 등).',
    zh: '注意：部分技能绕过效果抵抗检定，例如{SK/Drakhan|S2}。',
    fr: 'Note : certains skills contournent le check de RES, comme {SK/Drakhan|S2}.',
  },

  // ════════════════ Onglet : Combat Basics ════════════════
  combat_priority_heading: {
    en: 'Turn-Based Priority System',
    jp: 'ターン制優先度システム',
    kr: '턴제 우선도 시스템',
    zh: '回合制行动值系统',
    fr: 'Système de Priorité en Tour par Tour',
  },
  combat_turnflow_heading: {
    en: 'Turn Flow Breakdown',
    jp: 'ターンフローの詳細',
    kr: '턴 흐름 상세',
    zh: '回合流程详解',
    fr: 'Découpage du Flow de Tour',
  },
  combat_firstturn_heading: {
    en: 'First Turn Calculation',
    jp: '1ターン目の計算',
    kr: '1턴 계산',
    zh: '第1回合计算',
    fr: 'Calcul du Premier Tour',
  },
  combat_special_heading: {
    en: 'Special Mechanics & Exceptions',
    jp: '特殊メカニクス＆例外',
    kr: '특수 메카닉 & 예외',
    zh: '特殊机制 & 例外',
    fr: 'Mécaniques Spéciales & Exceptions',
  },

  // Priority — intro
  cp_intro1: {
    en: 'Imagine every battle in **Outerplane** as a 100-meter circular racetrack. Each character — ally or enemy — runs along this track. The first to complete a full lap (100%) reaches the action line and gets to **take their turn**.',
    jp: '**Outerplane**の全ての戦闘を100メートルの円形トラックとして想像してください。各キャラクター（味方も敵も）がこのトラックを走ります。最初に1周（100%）を完了した者がアクションラインに到達し、**ターンを取ります**。',
    kr: '**Outerplane**의 모든 전투를 100미터 원형 트랙으로 상상해 보세요. 각 캐릭터(아군과 적 모두)가 이 트랙을 달립니다. 가장 먼저 한 바퀴(100%)를 완주한 자가 액션 라인에 도달하여 **턴을 가집니다**.',
    zh: '把**Outerplane**的每场战斗想象成100米环形跑道。每个角色（友方和敌方）都在这条跑道上奔跑。第一个跑完一圈（100%）到达行动线的人**获得回合**。',
    fr: "Imaginez chaque combat dans **Outerplane** comme une piste circulaire de 100 mètres. Chaque personnage — allié ou ennemi — court sur cette piste. Le premier à compléter un tour complet (100%) atteint la ligne d'action et obtient le droit de **jouer son tour**.",
  },
  cp_intro2: {
    en: 'In-game, this progress is displayed as a **percentage** when you click the turn order icon:',
    jp: 'ゲーム内では、ターン順アイコンをクリックすると、この進行状況が**パーセンテージ**で表示されます：',
    kr: '게임 내에서 턴 순서 아이콘을 클릭하면 이 진행 상황이 **퍼센티지**로 표시됩니다:',
    zh: '在游戏中，点击回合顺序图标可以看到这个进度以**百分比**显示：',
    fr: "In-game, cette progression est affichée en **pourcentage** lorsque vous cliquez sur l'icône d'ordre de tour :",
  },
  cp_b0: {
    en: '**0%** = starting line',
    jp: '**0%** = スタートライン',
    kr: '**0%** = 출발선',
    zh: '**0%** = 起跑线',
    fr: '**0%** = ligne de départ',
  },
  cp_b100: {
    en: '**100%** = action line — you take your turn',
    jp: '**100%** = アクションライン — ターンを取る',
    kr: '**100%** = 액션 라인 — 턴을 가짐',
    zh: '**100%** = 行动线 — 获得回合',
    fr: "**100%** = ligne d'action — vous jouez votre tour",
  },

  // Priority — SPD accordion
  sp_p1: {
    en: "You can imagine that {S/SPD} is your character's running speed — it's the stat that determines how fast they advance on the track.",
    jp: '{S/SPD}はキャラクターの走る速さ — トラック上でどれだけ早く進むかを決定するステータスと想像できます。',
    kr: '{S/SPD}는 캐릭터의 달리기 속도 — 트랙에서 얼마나 빨리 전진하는지 결정하는 스탯이라고 상상할 수 있습니다.',
    zh: '把{S/SPD}想象成角色的奔跑速度——决定在跑道上前进多快的属性。',
    fr: "Vous pouvez vous représenter {S/SPD} comme la vitesse de course de votre personnage — c'est la stat qui détermine la vitesse à laquelle il avance sur la piste.",
  },
  sp_b1: {
    en: 'Higher {S/SPD} means you reach 100% faster.',
    jp: '{S/SPD}が高いほど、100%に早く到達。',
    kr: '{S/SPD}가 높을수록 100%에 더 빨리 도달.',
    zh: '{S/SPD}越高，越快到达100%。',
    fr: 'Plus élevé {S/SPD} plus vous atteignez 100% rapidement.',
  },
  sp_b2: {
    en: 'A character with 200 {S/SPD} moves twice as fast as one with 100.',
    jp: '200 {S/SPD}のキャラクターは100のキャラクターの2倍速く動きます。',
    kr: '200 {S/SPD} 캐릭터는 100인 캐릭터보다 2배 빠르게 움직입니다.',
    zh: '200 {S/SPD}的角色移动速度是100的两倍。',
    fr: "Un personnage avec 200 {S/SPD} avance deux fois plus vite qu'un personnage avec 100.",
  },
  sp_b3: {
    en: 'This means they can act twice while the other acts only once.',
    jp: 'つまり、一方が1回行動する間に2回行動できます。',
    kr: '즉, 한쪽이 1번 행동하는 동안 2번 행동할 수 있습니다.',
    zh: '这意味着一方行动1次时，另一方可以行动2次。',
    fr: "Cela veut dire qu'il peut agir deux fois pendant que l'autre n'agit qu'une seule fois.",
  },
  sp_p2: {
    en: "This isn't a fixed turn-order system — it's a continuous flow. Characters act as soon as they reach 100%.",
    jp: 'これは固定ターン順システムではなく、連続的な流れです。キャラクターは100%に達した瞬間に行動します。',
    kr: '이것은 고정 턴 순서 시스템이 아닙니다 — 연속적인 흐름입니다. 캐릭터는 100%에 도달하자마자 행동합니다.',
    zh: '这不是固定回合顺序系统——而是连续流动。角色一到达100%就立即行动。',
    fr: "Ce n'est pas un système d'ordre de tour fixe — c'est un flow continu. Les personnages agissent dès qu'ils atteignent 100%.",
  },
  sp_accordion: { en: 'Speed', jp: '速度', kr: '속도', zh: '速度', fr: 'Vitesse' },

  // Priority — Priority accordion
  pr_accordion: { en: 'Priority', jp: '優先度', kr: '우선도', zh: '行动值', fr: 'Priorité' },
  pr_p1: {
    en: 'Some skills or effects alter your current position on the track, regardless of your speed. You can imagine this as your character teleporting forward or backward on the track.',
    jp: '一部のスキルや効果は、速度に関係なく、トラック上の現在位置を変更します。キャラクターがトラック上を前方または後方にテレポートすると想像できます。',
    kr: '일부 스킬이나 효과는 속도와 관계없이 트랙에서의 현재 위치를 변경합니다. 캐릭터가 트랙에서 앞이나 뒤로 텔레포트한다고 상상할 수 있습니다.',
    zh: '部分技能或效果可以改变你在跑道上的当前位置，与速度无关。想象角色在跑道上向前或向后瞬移。',
    fr: "Certains skills ou effets modifient votre position actuelle sur la piste, indépendamment de votre SPD. Vous pouvez l'imaginer comme votre personnage qui se téléporte en avant ou en arrière sur la piste.",
  },
  pr_p2: {
    en: 'This is known as **increasing or reducing priority**.',
    jp: 'これは**優先度を増加または減少させる**として知られています。',
    kr: '이것을 **우선도를 증가 또는 감소시킨다**고 합니다.',
    zh: '这称为**增加或减少行动值**。',
    fr: 'On appelle cela **augmenter ou réduire la priorité**.',
  },
  pr_p3: {
    en: "In other games, similar systems exist — such as Combat Readiness in Epic Seven or the ATB gauge in Summoner's War.",
    jp: "他のゲームでも同様のシステムがあります — Epic Sevenの戦闘準備やSummoner's WarのATBゲージなど。",
    kr: "다른 게임에도 비슷한 시스템이 있습니다 — Epic Seven의 전투 준비나 Summoner's War의 ATB 게이지 등.",
    zh: "其他游戏也有类似系统——Epic Seven的战斗准备或Summoner's War的ATB槽等。",
    fr: "Dans d'autres jeux, des systèmes similaires existent — comme le Combat Readiness dans Epic Seven ou la jauge ATB dans Summoner's War.",
  },
  pr_icon_note: {
    en: 'Priority has no official in-game icon. However, this website uses the following icon to represent it:',
    jp: '優先度にはゲーム内の公式アイコンがありません。ただし、このウェブサイトでは以下のアイコンを使用しています：',
    kr: '우선도에는 공식 게임 내 아이콘이 없습니다. 하지만 이 웹사이트에서는 다음 아이콘을 사용합니다:',
    zh: '行动值没有官方游戏内图标。但本网站使用此图标：',
    fr: "La priorité n'a pas d'icône officielle in-game. Cependant, ce site utilise l'icône suivante pour la représenter :",
  },
  pr_beneficial: {
    en: '**Beneficial**: {B/BT_ACTION_GAUGE} — pushes the character forward.',
    jp: '**有益**：{B/BT_ACTION_GAUGE} — キャラクターを前方に押す。',
    kr: '**유익**: {B/BT_ACTION_GAUGE} — 캐릭터를 앞으로 밀음.',
    zh: '**有益**：{B/BT_ACTION_GAUGE} — 将角色向前推。',
    fr: "**Bénéfique** : {B/BT_ACTION_GAUGE} — pousse le personnage vers l'avant.",
  },
  pr_detrimental: {
    en: '**Detrimental**: {D/BT_ACTION_GAUGE} — pushes the character backward.',
    jp: '**有害**：{D/BT_ACTION_GAUGE} — キャラクターを後方に押す。',
    kr: '**해로움**: {D/BT_ACTION_GAUGE} — 캐릭터를 뒤로 밀음.',
    zh: '**有害**：{D/BT_ACTION_GAUGE} — 将角色向后推。',
    fr: "**Néfaste** : {D/BT_ACTION_GAUGE} — pousse le personnage vers l'arrière.",
  },
  pr_notes_title: {
    en: 'Important Notes:',
    jp: '重要な注意事項：',
    kr: '중요 사항:',
    zh: '重要事项：',
    fr: 'Notes importantes :',
  },
  pr_n1: {
    en: 'Priority can never exceed 100% or drop below 0%.',
    jp: '優先度は100%を超えたり0%を下回ったりしません。',
    kr: '우선도는 100%를 초과하거나 0% 아래로 떨어지지 않습니다.',
    zh: '行动值不会超过100%或低于0%。',
    fr: 'La priorité ne peut jamais dépasser 100% ni descendre en dessous de 0%.',
  },
  pr_n2: {
    en: 'When multiple characters reach 100% at different times, the one who gets there first will act first. This is the most common case.',
    jp: '複数のキャラクターが異なるタイミングで100%に達した場合、最初に到達した者が先に行動します。これが最も一般的なケースです。',
    kr: '여러 캐릭터가 다른 시점에 100%에 도달하면, 먼저 도달한 자가 먼저 행동합니다. 이것이 가장 일반적인 경우입니다.',
    zh: '多个角色在不同时间到达100%时，先到的先行动。这是最常见的情况。',
    fr: "Lorsque plusieurs personnages atteignent 100% à des moments différents, celui qui arrive en premier agit en premier. C'est le cas le plus courant.",
  },
  pr_n3: {
    en: 'However, if multiple characters reach 100% **within the same action** (e.g. due to a mass +Priority boost), then the acting order is based on a fixed positional priority: **Front-right → Top → Bottom → Back-left**',
    jp: 'ただし、複数のキャラクターが**同じアクション内で**100%に達した場合（例：大量の+優先度ブーストにより）、行動順序は固定の位置優先度に基づきます：**右前→上→下→左後**',
    kr: '하지만 여러 캐릭터가 **같은 액션 내에서** 100%에 도달하면(예: 대량 +우선도 부스트로), 행동 순서는 고정 위치 우선도를 기반으로 합니다: **오른쪽 앞 → 위 → 아래 → 왼쪽 뒤**',
    zh: '但多个角色在**同一行动内**到达100%时（如通过大量+行动值提升），行动顺序基于固定位置优先级：**右前 → 上 → 下 → 左后**',
    fr: "Cependant, si plusieurs personnages atteignent 100% **pendant la même action** (par ex. à cause d'un boost de +Priority de masse), alors l'ordre d'action est basé sur une priorité positionnelle fixe : **Front-droite → Haut → Bas → Arrière-gauche**",
  },
  pr_n4: {
    en: 'This positional rule is only used when multiple characters are pushed to 100% at the exact same time.',
    jp: 'この位置ルールは、複数のキャラクターが同時に100%に押し上げられた場合にのみ使用されます。',
    kr: '이 위치 규칙은 여러 캐릭터가 정확히 같은 시간에 100%로 밀려날 때만 사용됩니다.',
    zh: '此位置规则仅在多个角色被同时推到100%时使用。',
    fr: "Cette règle positionnelle ne s'applique que lorsque plusieurs personnages sont poussés à 100% exactement au même instant.",
  },
  pr_n5: {
    en: '⚠️ Additional Priority boosts applied **after** 100% are ignored and have no effect on the turn order.',
    jp: '⚠️ 100%以降に適用された追加の優先度ブーストは無視され、ターン順序に影響しません。',
    kr: '⚠️ 100% 이후에 적용된 추가 우선도 부스트는 무시되며 턴 순서에 영향을 주지 않습니다.',
    zh: '⚠️ 100%之后施加的额外行动值提升被忽略，不影响回合顺序。',
    fr: "⚠️ Les boosts de priorité supplémentaires appliqués **après** 100% sont ignorés et n'ont aucun effet sur l'ordre de tour.",
  },
  pr_n6: {
    en: 'In such cases, the acting team always goes first, followed by the enemy team — each resolving ties based on the positional rule above.',
    jp: 'そのような場合、行動チームが常に先に行動し、その後敵チーム — それぞれ上記の位置ルールに基づいてタイを解決します。',
    kr: '그런 경우, 행동 팀이 항상 먼저 행동하고, 그 다음 적 팀 — 각각 위의 위치 규칙에 따라 타이를 해결합니다.',
    zh: '在这种情况下，行动方总是先行动，然后是敌方——各自按上述位置规则解决平局。',
    fr: "Dans ce cas, l'équipe qui agit passe toujours en premier, suivie par l'équipe ennemie — chacune résolvant les égalités selon la règle positionnelle ci-dessus.",
  },

  // Turn Flow
  tf_intro: {
    en: 'When a character reaches 100% priority, their turn proceeds in several phases. Each phase triggers specific events:',
    jp: 'キャラクターが100%優先度に達すると、ターンは複数のフェーズで進行します。各フェーズで特定のイベントが発生します：',
    kr: '캐릭터가 100% 우선도에 도달하면 턴은 여러 단계로 진행됩니다. 각 단계에서 특정 이벤트가 발생합니다:',
    zh: '角色到达100%行动值时，回合分为多个阶段进行。每个阶段发生特定事件：',
    fr: "Lorsqu'un personnage atteint 100% de priorité, son tour se déroule en plusieurs phases. Chaque phase déclenche des événements spécifiques :",
  },
  tf_start_title: {
    en: '1. Starting Phase',
    jp: '1. 開始フェーズ',
    kr: '1. 시작 단계',
    zh: '1. 开始阶段',
    fr: '1. Phase de Début',
  },
  tf_s1: {
    en: 'All skill cooldowns are reduced by 1.',
    jp: '全てのスキルクールダウンが1減少。',
    kr: '모든 스킬 쿨다운이 1 감소.',
    zh: '所有技能冷却减少1。',
    fr: 'Tous les cooldowns de skills sont réduits de 1.',
  },
  tf_s2: {
    en: 'Healing-over-time (HoT) effects are applied, such as {B/BT_CONTINU_HEAL}',
    jp: '継続回復（HoT）効果が適用（{B/BT_CONTINU_HEAL}など）',
    kr: '지속 회복(HoT) 효과 적용({B/BT_CONTINU_HEAL} 등)',
    zh: '持续治疗(HoT)效果生效（如{B/BT_CONTINU_HEAL}）',
    fr: 'Les effets de heal-over-time (HoT) sont appliqués, comme {B/BT_CONTINU_HEAL}',
  },
  tf_s3: {
    en: 'Damage-over-time (DoT) effects are applied, such as {D/BT_DOT_BLEED}',
    jp: '継続ダメージ（DoT）効果が適用（{D/BT_DOT_BLEED}など）',
    kr: '지속 데미지(DoT) 효과 적용({D/BT_DOT_BLEED} 등)',
    zh: '持续伤害(DoT)效果生效（如{D/BT_DOT_BLEED}）',
    fr: 'Les effets de damage-over-time (DoT) sont appliqués, comme {D/BT_DOT_BLEED}',
  },
  tf_action_title: {
    en: '2. Action Phase',
    jp: '2. アクションフェーズ',
    kr: '2. 행동 단계',
    zh: '2. 行动阶段',
    fr: "2. Phase d'Action",
  },
  tf_action_note: {
    en: 'If the unit is under crowd control effects like {D/BT_STUN}, this phase is skipped and the turn proceeds directly to the Ending Phase.',
    jp: '{D/BT_STUN}などの行動不能効果を受けている場合、このフェーズはスキップされ、ターンは直接終了フェーズに進みます。',
    kr: '{D/BT_STUN} 같은 행동 불가 효과를 받고 있으면, 이 단계는 건너뛰고 턴은 바로 종료 단계로 진행합니다.',
    zh: '如果受到{D/BT_STUN}等行动阻止效果，此阶段跳过，回合直接进入结束阶段。',
    fr: "Si l'unité est sous effets de CC comme {D/BT_STUN}, cette phase est sautée et le tour passe directement à la Phase de Fin.",
  },
  tf_choice_title: {
    en: '2-1: Choice Phase',
    jp: '2-1: 選択フェーズ',
    kr: '2-1: 선택 단계',
    zh: '2-1：选择阶段',
    fr: '2-1 : Phase de Choix',
  },
  tf_c1: {
    en: 'Forced actions are resolved first, such as {D/BT_AGGRO}, which immediately starts the Hit Phase.',
    jp: '強制行動が最初に解決されます（{D/BT_AGGRO}など）、即座にヒットフェーズを開始。',
    kr: '강제 행동이 먼저 해결됩니다({D/BT_AGGRO} 등), 즉시 히트 단계를 시작.',
    zh: '强制行动优先解决（如{D/BT_AGGRO}），立即开始命中阶段。',
    fr: 'Les actions forcées sont résolues en premier, comme {D/BT_AGGRO}, qui démarre immédiatement la Phase de Hit.',
  },
  tf_c2: {
    en: 'Then, the player selects a skill and a target.',
    jp: 'その後、プレイヤーがスキルとターゲットを選択。',
    kr: '그 후, 플레이어가 스킬과 타겟을 선택.',
    zh: '之后，玩家选择技能和目标。',
    fr: 'Ensuite, le joueur sélectionne un skill et une cible.',
  },
  tf_hit_title: {
    en: '2-2: Hit Phase',
    jp: '2-2: ヒットフェーズ',
    kr: '2-2: 히트 단계',
    zh: '2-2：命中阶段',
    fr: '2-2 : Phase de Hit',
  },
  tf_hit_intro: {
    en: 'The skill executes in three stages:',
    jp: 'スキルは3段階で実行されます：',
    kr: '스킬은 세 단계로 실행됩니다:',
    zh: '技能分三个阶段执行：',
    fr: "Le skill s'exécute en trois étapes :",
  },
  tf_pre: {
    en: "**Pre-Hit:** Happens before the skill hits. For example, {SK/Drakhan|S3} with EE+10 applies a {D/BT_DOT_CURSE} before it hits — important, as the skill's damage scales with the number of debuffs.",
    jp: '**プレヒット：** スキルがヒットする前に発生。例えば、{SK/Drakhan|S3}のEE+10はヒット前に{D/BT_DOT_CURSE}を付与 — スキルのダメージがデバフ数に依存するため重要。',
    kr: '**프리히트:** 스킬이 히트하기 전에 발생. 예를 들어, {SK/Drakhan|S3}의 EE+10은 히트 전에 {D/BT_DOT_CURSE}를 부여 — 스킬의 데미지가 디버프 수에 의존하므로 중요.',
    zh: '**命中前：** 技能命中前发生。例如，{SK/Drakhan|S3}的EE+10在命中前施加{D/BT_DOT_CURSE}——这很重要，因为技能伤害取决于减益数量。',
    fr: '**Pre-Hit :** Se produit avant que le skill ne touche. Par exemple, {SK/Drakhan|S3} avec EE+10 applique un {D/BT_DOT_CURSE} avant que le coup ne touche — important, car les dégâts du skill scalent avec le nombre de debuffs.',
  },
  tf_hit: {
    en: '**Hit:** The skill connects — direct damage and healing are applied.',
    jp: '**ヒット：** スキルが接続 — 直接ダメージと回復が適用。',
    kr: '**히트:** 스킬이 연결 — 직접 데미지와 힐이 적용.',
    zh: '**命中：** 技能连接——直接伤害和治疗生效。',
    fr: '**Hit :** Le skill touche — les dégâts directs et heals sont appliqués.',
  },
  tf_post: {
    en: '**Post-Hit:** Triggers after the skill hits — for example, {SK/Demiurge Vlada|S3} inflicts {D/BT_SEALED_RECEIVE_HEAL} post-hit.',
    jp: '**ポストヒット：** スキルがヒットした後に発生 — 例えば、{SK/Demiurge Vlada|S3}はポストヒットで{D/BT_SEALED_RECEIVE_HEAL}を付与。',
    kr: '**포스트히트:** 스킬이 히트한 후 발생 — 예를 들어, {SK/Demiurge Vlada|S3}는 포스트히트에 {D/BT_SEALED_RECEIVE_HEAL}를 부여.',
    zh: '**命中后：** 技能命中后发生——例如，{SK/Demiurge Vlada|S3}在命中后施加{D/BT_SEALED_RECEIVE_HEAL}。',
    fr: '**Post-Hit :** Se déclenche après que le skill ait touché — par exemple, {SK/Demiurge Vlada|S3} inflige {D/BT_SEALED_RECEIVE_HEAL} en post-hit.',
  },
  tf_extra: {
    en: 'Extra hits are triggered, such as {SK/Ryu Lion|S2}.',
    jp: '追加ヒットが発動（{SK/Ryu Lion|S2}など）。',
    kr: '추가 히트가 발동({SK/Ryu Lion|S2} 등).',
    zh: '追加攻击触发（如{SK/Ryu Lion|S2}）。',
    fr: 'Des hits supplémentaires se déclenchent, comme {SK/Ryu Lion|S2}.',
  },
  tf_ally: {
    en: 'Ally reactions, like {SK/Caren|S2}, may also trigger. These follow-up effects are resolved in positional order: **Front-right → Top → Bottom → Back-left**.',
    jp: '味方の反応（{SK/Caren|S2}など）も発動可能。これらのフォローアップ効果は位置順で解決：**右前→上→下→左後**。',
    kr: '아군 반응({SK/Caren|S2} 등)도 발동 가능. 이러한 후속 효과는 위치 순서로 해결: **오른쪽 앞 → 위 → 아래 → 왼쪽 뒤**.',
    zh: '友方反应（如{SK/Caren|S2}）也可能触发。这些后续效果按位置顺序解决：**右前 → 上 → 下 → 左后**。',
    fr: "Les réactions d'alliés, comme {SK/Caren|S2}, peuvent aussi se déclencher. Ces effets de follow-up sont résolus dans l'ordre positionnel : **Front-droite → Haut → Bas → Arrière-gauche**.",
  },
  tf_enemy: {
    en: 'Enemy reactions such as {B/BT_STAT|ST_COUNTER_RATE}, {B/BT_AGILE_RESPONSE} or {B/BT_REVENGE} may occur, and also follow this positional order.',
    jp: '敵の反応（{B/BT_STAT|ST_COUNTER_RATE}、{B/BT_AGILE_RESPONSE}、{B/BT_REVENGE}など）も発生可能で、同じ位置順に従います。',
    kr: '적 반응({B/BT_STAT|ST_COUNTER_RATE}, {B/BT_AGILE_RESPONSE}, {B/BT_REVENGE} 등)도 발생 가능하며, 같은 위치 순서를 따릅니다.',
    zh: '敌方反应（{B/BT_STAT|ST_COUNTER_RATE}、{B/BT_AGILE_RESPONSE}、{B/BT_REVENGE}）也可能发生，遵循相同位置顺序。',
    fr: 'Les réactions ennemies comme {B/BT_STAT|ST_COUNTER_RATE}, {B/BT_AGILE_RESPONSE} ou {B/BT_REVENGE} peuvent se déclencher, et suivent aussi cet ordre positionnel.',
  },
  tf_end_title: {
    en: '3. Ending Phase',
    jp: '3. 終了フェーズ',
    kr: '3. 종료 단계',
    zh: '3. 结束阶段',
    fr: '3. Phase de Fin',
  },
  tf_e1: {
    en: 'Revive effects are resolved, such as {B/BT_REVIVAL} or {SK/Demiurge Astei|S2}.',
    jp: '復活効果が解決（{B/BT_REVIVAL}や{SK/Demiurge Astei|S2}など）。',
    kr: '부활 효과 해결({B/BT_REVIVAL}나 {SK/Demiurge Astei|S2} 등).',
    zh: '复活效果解决（如{B/BT_REVIVAL}或{SK/Demiurge Astei|S2}）。',
    fr: 'Les effets de revive sont résolus, comme {B/BT_REVIVAL} ou {SK/Demiurge Astei|S2}.',
  },
  tf_e2: {
    en: 'All remaining buffs and debuffs decrease their duration by 1 turn — except those already processed during the Starting Phase.',
    jp: '残りの全てのバフとデバフの持続時間が1ターン減少 — 開始フェーズで既に処理されたものを除く。',
    kr: '남은 모든 버프와 디버프의 지속 시간이 1턴 감소 — 시작 단계에서 이미 처리된 것 제외.',
    zh: '所有剩余增益和减益的持续时间减少1回合——开始阶段已处理的除外。',
    fr: 'Tous les buffs et debuffs restants voient leur durée réduite de 1 tour — sauf ceux déjà traités pendant la Phase de Début.',
  },
  tf_e3: {
    en: 'Any remaining priority gains or losses are now applied.',
    jp: '残りの優先度増減が適用。',
    kr: '남은 우선도 증감이 적용.',
    zh: '剩余行动值增减生效。',
    fr: 'Tous les gains ou pertes de priorité restants sont alors appliqués.',
  },

  // First Turn
  ft_intro: {
    en: 'At the start of battle, the unit with the highest {S/SPD} will act first. All other units begin with a priority value proportional to their SPD compared to the fastest unit.',
    jp: '戦闘開始時、最も高い{S/SPD}を持つユニットが最初に行動します。他の全てのユニットは、最速ユニットと比較したSPDに比例した優先度値から開始します。',
    kr: '전투 시작 시, 가장 높은 {S/SPD}를 가진 유닛이 먼저 행동합니다. 다른 모든 유닛은 가장 빠른 유닛과 비교한 SPD에 비례한 우선도 값으로 시작합니다.',
    zh: '战斗开始时，{S/SPD}最高的单位先行动。所有其他单位的初始行动值与最快单位的SPD成比例。',
    fr: "En début de combat, l'unité avec la plus haute {S/SPD} agit en premier. Toutes les autres unités commencent avec une valeur de priorité proportionnelle à leur SPD comparée à l'unité la plus rapide.",
  },
  ft_ex_title: { en: 'Example:', jp: '例：', kr: '예시:', zh: '示例：', fr: 'Exemple :' },
  ft_ex1: {
    en: 'If the fastest unit has **300 SPD**, she starts at **100%** priority.',
    jp: '最速ユニットが**300 SPD**の場合、**100%**優先度から開始。',
    kr: '가장 빠른 유닛이 **300 SPD**면 **100%** 우선도로 시작.',
    zh: '最快单位**300 SPD**时以**100%**行动值开始。',
    fr: "Si l'unité la plus rapide a **300 SPD**, elle commence à **100%** priorité.",
  },
  ft_ex2: {
    en: 'A unit with **200 SPD** starts at **66%** (200 × 100 / 300).',
    jp: '**200 SPD**のユニットは**66%**(200 × 100 / 300)から開始。',
    kr: '**200 SPD** 유닛은 **66%**(200 × 100 / 300)로 시작.',
    zh: '**200 SPD**单位以**66%**(200 × 100 / 300)开始。',
    fr: 'Une unité avec **200 SPD** démarre à **66%** (200 × 100 / 300).',
  },
  ft_ex3: {
    en: 'A unit with **150 SPD** starts at **50%** (150 × 100 / 300).',
    jp: '**150 SPD**のユニットは**50%**(150 × 100 / 300)から開始。',
    kr: '**150 SPD** 유닛은 **50%**(150 × 100 / 300)로 시작.',
    zh: '**150 SPD**单位以**50%**(150 × 100 / 300)开始。',
    fr: 'Une unité avec **150 SPD** démarre à **50%** (150 × 100 / 300).',
  },
  ft_rng: {
    en: "However, the game includes a hidden random variation of **0-5%** applied to each unit's starting priority. As a result, a slightly slower unit may still act first.",
    jp: 'ただし、ゲームには各ユニットの開始優先度に適用される**0-5%**の隠れたランダム変動があります。その結果、わずかに遅いユニットでも先に行動する可能性があります。',
    kr: '하지만 게임에는 각 유닛의 시작 우선도에 적용되는 **0-5%**의 숨겨진 랜덤 변동이 있습니다. 결과적으로, 약간 느린 유닛이 먼저 행동할 수도 있습니다.',
    zh: '但游戏有一个隐藏的**0-5%**随机波动应用于每个单位的初始行动值。因此，稍慢的单位可能先行动。',
    fr: 'Cependant, le jeu inclut une variation aléatoire cachée de **0-5%** appliquée à la priorité de départ de chaque unité. En conséquence, une unité légèrement plus lente peut quand même agir en premier.',
  },
  ft_rng_title: {
    en: 'Example with RNG:',
    jp: 'RNGを含む例：',
    kr: 'RNG 포함 예시:',
    zh: '带RNG的示例：',
    fr: 'Exemple avec RNG :',
  },
  ft_rng_a: {
    en: 'Unit A: 300 SPD → 100% +0% = 100%',
    jp: 'ユニットA：300 SPD → 100% +0% = 100%',
    kr: '유닛 A: 300 SPD → 100% +0% = 100%',
    zh: '单位A：300 SPD → 100% +0% = 100%',
    fr: 'Unité A : 300 SPD → 100% +0% = 100%',
  },
  ft_rng_b: {
    en: 'Unit B: 290 SPD → 96% + 5% = 101%',
    jp: 'ユニットB：290 SPD → 96% + 5% = 101%',
    kr: '유닛 B: 290 SPD → 96% + 5% = 101%',
    zh: '单位B：290 SPD → 96% + 5% = 101%',
    fr: 'Unité B : 290 SPD → 96% + 5% = 101%',
  },
  ft_rng_result: {
    en: '→ **Unit B will act first.**',
    jp: '→ **ユニットBが先に行動します。**',
    kr: '→ **유닛 B가 먼저 행동합니다.**',
    zh: '→ **单位B先行动。**',
    fr: "→ **L'Unité B agit en premier.**",
  },
  ft_pvp: {
    en: 'This mechanic is especially important in **PvP**, where the first turn can greatly influence the outcome of a match.',
    jp: 'このメカニクスは**PvP**で特に重要で、1ターン目が試合の結果に大きく影響する可能性があります。',
    kr: '이 메카닉은 **PvP**에서 특히 중요하며, 1턴이 경기 결과에 큰 영향을 미칠 수 있습니다.',
    zh: '此机制在**PvP**中特别重要，第1回合可能决定比赛结果。',
    fr: "Cette mécanique est particulièrement importante en **PvP**, où le premier tour peut grandement influencer le résultat d'un match.",
  },
  ft_spd_title: {
    en: 'Speed Buffs at Battle Start',
    jp: '戦闘開始時の速度バフ',
    kr: '전투 시작 시 속도 버프',
    zh: '战斗开始时的速度增益',
    fr: 'Buffs de SPD en début de combat',
  },
  ft_spd_intro: {
    en: 'Some units may start the battle with a {B/BT_STAT|ST_SPEED}, significantly altering turn order.',
    jp: '一部のユニットは{B/BT_STAT|ST_SPEED}を持って戦闘を開始し、ターン順序を大きく変更する可能性があります。',
    kr: '일부 유닛은 {B/BT_STAT|ST_SPEED}를 가지고 전투를 시작하여 턴 순서를 크게 바꿀 수 있습니다.',
    zh: '部分单位带{B/BT_STAT|ST_SPEED}开始战斗，可以显著改变回合顺序。',
    fr: "Certaines unités peuvent commencer le combat avec un {B/BT_STAT|ST_SPEED}, modifiant significativement l'ordre de tour.",
  },
  ft_spd_ex1: {
    en: '{P/Tamara}: 300 SPD → 100% priority',
    jp: '{P/Tamara}：300 SPD → 100%優先度',
    kr: '{P/Tamara}: 300 SPD → 100% 우선도',
    zh: '{P/Tamara}：300 SPD → 100%行动值',
    fr: '{P/Tamara} : 300 SPD → 100% priorité',
  },
  ft_spd_ex2: {
    en: '{P/Dahlia}: 280 SPD → 93% (280 × 100 / 300)',
    jp: '{P/Dahlia}：280 SPD → 93% (280 × 100 / 300)',
    kr: '{P/Dahlia}: 280 SPD → 93% (280 × 100 / 300)',
    zh: '{P/Dahlia}：280 SPD → 93% (280 × 100 / 300)',
    fr: '{P/Dahlia} : 280 SPD → 93% (280 × 100 / 300)',
  },
  ft_spd_ex3: {
    en: 'Normally, {P/Tamara} would go first.',
    jp: '通常、{P/Tamara}が先に行動します。',
    kr: '일반적으로 {P/Tamara}가 먼저 행동합니다.',
    zh: '通常{P/Tamara}先行动。',
    fr: 'Normalement, {P/Tamara} agirait en premier.',
  },
  ft_spd_ex4: {
    en: 'But if {P/Dahlia} starts with a {B/BT_STAT|ST_SPEED} (e.g., from her EE), her effective SPD becomes:',
    jp: 'しかし、{P/Dahlia}が{B/BT_STAT|ST_SPEED}を持って開始すると（例：EEから）、有効SPDは：',
    kr: '하지만 {P/Dahlia}가 {B/BT_STAT|ST_SPEED}로 시작하면(예: EE에서), 유효 SPD는:',
    zh: '但如果{P/Dahlia}带{B/BT_STAT|ST_SPEED}开始（如从EE），有效SPD为：',
    fr: 'Mais si {P/Dahlia} commence avec un {B/BT_STAT|ST_SPEED} (par ex. depuis son EE), sa SPD effective devient :',
  },
  ft_spd_ex5: {
    en: '280 × 1.3 = 364 → 100% priority',
    jp: '280 × 1.3 = 364 → 100%優先度',
    kr: '280 × 1.3 = 364 → 100% 우선도',
    zh: '280 × 1.3 = 364 → 100%行动值',
    fr: '280 × 1.3 = 364 → 100% priorité',
  },
  ft_spd_ex6: {
    en: '{P/Tamara}: 300 SPD → **82%** (300 × 100 / 364)',
    jp: '{P/Tamara}：300 SPD → **82%** (300 × 100 / 364)',
    kr: '{P/Tamara}: 300 SPD → **82%** (300 × 100 / 364)',
    zh: '{P/Tamara}：300 SPD → **82%** (300 × 100 / 364)',
    fr: '{P/Tamara} : 300 SPD → **82%** (300 × 100 / 364)',
  },
  ft_spd_ex7: {
    en: '→ **{P/Dahlia} will act first.**',
    jp: '→ **{P/Dahlia}が先に行動します。**',
    kr: '→ **{P/Dahlia}가 먼저 행동합니다.**',
    zh: '→ **{P/Dahlia}先行动。**',
    fr: '→ **{P/Dahlia} agira en premier.**',
  },
  ft_spd_transcend: {
    en: 'Some transcendence perks also grant {S/SPD} bonuses to the entire team, such as with {P/Mene} or {P/Demiurge Delta}.',
    jp: '一部の超越特典はチーム全体に{S/SPD}ボーナスを付与します（{P/Mene}や{P/Demiurge Delta}など）。',
    kr: '일부 초월 특전은 팀 전체에 {S/SPD} 보너스를 부여합니다({P/Mene}나 {P/Demiurge Delta} 등).',
    zh: '部分超越特权为全队提供{S/SPD}加成（如{P/Mene}或{P/Demiurge Delta}）。',
    fr: "Certains perks de transcendance accordent aussi des {S/SPD} bonus à toute l'équipe, comme avec {P/Mene} ou {P/Demiurge Delta}.",
  },

  // Special Mechanics
  sm_extra_title: {
    en: 'Extra Turns',
    jp: '追加ターン',
    kr: '추가 턴',
    zh: '额外回合',
    fr: 'Tours supplémentaires',
  },
  sm_extra_p: {
    en: 'If a skill applies {B/BT_ADDITIVE_TURN}, the character will immediately take another full turn (including all phases) before resetting to 0% priority.',
    jp: 'スキルが{B/BT_ADDITIVE_TURN}を適用すると、キャラクターは0%優先度にリセットされる前に、即座に完全なターン（全てのフェーズを含む）を取ります。',
    kr: '스킬이 {B/BT_ADDITIVE_TURN}를 적용하면, 캐릭터는 0% 우선도로 리셋되기 전에 즉시 완전한 턴(모든 단계 포함)을 가집니다.',
    zh: '当技能施加{B/BT_ADDITIVE_TURN}时，角色在行动值重置为0%前立即获得完整回合（包括所有阶段）。',
    fr: 'Si un skill applique {B/BT_ADDITIVE_TURN}, le personnage prend immédiatement un autre tour complet (toutes phases incluses) avant que sa priorité ne revienne à 0%.',
  },
  sm_vlada_title: {
    en: "Demiurge Vlada's Passive",
    jp: 'デミウルゴスヴラダのパッシブ',
    kr: '데미우르고스 블라다의 패시브',
    zh: '造物主弗拉达的被动',
    fr: 'Passive de Demiurge Vlada',
  },
  sm_vlada_p: {
    en: 'If a 5★ {P/Demiurge Vlada} is in battle, all **priority gain effects** on the enemy team are reduced by **50%**.',
    jp: '5★ {P/Demiurge Vlada}が戦闘にいる場合、敵チームの全ての**優先度増加効果**が**50%**減少します。',
    kr: '5★ {P/Demiurge Vlada}가 전투에 있으면, 적 팀의 모든 **우선도 증가 효과**가 **50%** 감소합니다.',
    zh: '当5★{P/Demiurge Vlada}在战斗中时，敌方队伍所有**行动值增加效果**减少**50%**。',
    fr: "Si un 5★ {P/Demiurge Vlada} est en combat, tous les **effets de gain de priorité** sur l'équipe ennemie sont réduits de **50%**.",
  },
  sm_arena_title: {
    en: 'Arena Field Skills',
    jp: 'アリーナフィールドスキル',
    kr: '아레나 필드 스킬',
    zh: '竞技场场地技能',
    fr: 'Arena Field Skills',
  },
  sm_arena_intro: {
    en: 'In arena, field skills are applied. These change every season — here is an example:',
    jp: 'アリーナではフィールドスキルが適用されます。これらはシーズンごとに変わります — 以下は一例です：',
    kr: '아레나에서는 필드 스킬이 적용됩니다. 이것들은 시즌마다 바뀝니다 — 다음은 예시입니다:',
    zh: '竞技场有场地技能生效。这些每赛季更换——以下为示例：',
    fr: 'En arène, des field skills sont appliquées. Elles changent à chaque saison — voici un exemple :',
  },
  sm_arena_1_name: {
    en: 'Pulse of the mighty',
    jp: '強者の鼓動',
    kr: '강자의 고동',
    zh: '强者的心跳',
    fr: 'Pulse of the mighty',
  },
  sm_arena_1_body: {
    en: 'increase all heroes {S/RES} by 50 after Gold III',
    jp: 'ゴールドIII以降、全てのヒーローの{S/RES}を50増加',
    kr: '골드 III 이후, 모든 영웅의 {S/RES}를 50 증가',
    zh: '黄金III以上，所有英雄{S/RES}增加50',
    fr: 'augmente la {S/RES} de tous les héros de 50 après Gold III',
  },
  sm_arena_2_name: {
    en: "Duelist's Pledge",
    jp: '決闘者の誓い',
    kr: '결투자의 맹세',
    zh: '决斗者的誓言',
    fr: "Duelist's Pledge",
  },
  sm_arena_2_body: {
    en: 'decrease priority by 50% after resurrection. Every 10 turn, deals 10% of max HP to all heroes as true damage (bypassing {B/BT_INVINCIBLE}, {B/BT_UNDEAD})',
    jp: '復活後、優先度を50%減少。10ターンごとに、全てのヒーローに最大HPの10%を固定ダメージとして与える（{B/BT_INVINCIBLE}、{B/BT_UNDEAD}を貫通）',
    kr: '부활 후 우선도 50% 감소. 10턴마다 모든 영웅에게 최대 HP의 10%를 고정 데미지로 줌 ({B/BT_INVINCIBLE}, {B/BT_UNDEAD} 관통)',
    zh: '复活后行动值减少50%。每10回合对所有英雄造成最大HP 10%的固定伤害（无视{B/BT_INVINCIBLE}、{B/BT_UNDEAD}）',
    fr: 'réduit la priorité de 50% après une résurrection. Tous les 10 tours, inflige 10% des HP max à tous les héros en true damage (contourne {B/BT_INVINCIBLE}, {B/BT_UNDEAD})',
  },

  // ════════════════ Onglet : FAQ ════════════════
  faq_sec_critDots: {
    en: 'Critical Hits & DoTs',
    jp: 'クリティカル＆DoT',
    kr: '치명타 & DoT',
    zh: '暴击 & DoT',
    fr: 'Coups Critiques & DoTs',
  },
  faq_sec_dmgMods: {
    en: 'Damage Modifiers',
    jp: 'ダメージ修正',
    kr: '데미지 보정',
    zh: '伤害修正',
    fr: 'Modificateurs de Dégâts',
  },
  faq_sec_defPen: {
    en: 'Defense & Penetration',
    jp: '防御＆貫通',
    kr: '방어 & 관통',
    zh: '防御 & 穿透',
    fr: 'DEF & PEN',
  },
  faq_sec_statScaling: {
    en: 'Stat Scaling',
    jp: 'ステータス依存',
    kr: '스탯 의존',
    zh: '属性依赖',
    fr: 'Scaling des Stats',
  },
  faq_sec_speedPriority: {
    en: 'Speed & Priority',
    jp: '速度＆優先度',
    kr: '속도 & 우선도',
    zh: '速度 & 行动值',
    fr: 'SPD & Priorité',
  },
  faq_sec_formulas: {
    en: 'Formulas & Calculations',
    jp: '計算式',
    kr: '공식 & 계산',
    zh: '公式 & 计算',
    fr: 'Formules & Calculs',
  },

  // Titres de questions
  q_critCap: {
    en: 'Can Crit Rate exceed 100%?',
    jp: 'クリ率は100%を超えられますか？',
    kr: '치명타 확률이 100%를 초과할 수 있나요?',
    zh: '暴击率可以超过100%吗？',
    fr: 'Le CHC peut-il dépasser 100% ?',
  },
  q_critOnHeal: {
    en: 'Can healing or shielding crit?',
    jp: '回復やシールドはクリティカルしますか？',
    kr: '힐이나 보호막이 치명타가 되나요?',
    zh: '治疗或护盾可以暴击吗？',
    fr: 'Les Heals ou shields peuvent-ils crit ?',
  },
  q_dotCrit: {
    en: 'Do DoTs scale with Crit or Crit Damage?',
    jp: 'DoTはクリ率やクリダメに影響されますか？',
    kr: 'DoT는 치명타 확률이나 치명타 데미지의 영향을 받나요?',
    zh: 'DoT受暴击率或暴击伤害影响吗？',
    fr: 'Les DoTs scalent-ils avec le CHC ou le CHD ?',
  },
  q_dotScaling: {
    en: 'Do DoTs scale with Attack?',
    jp: 'DoTは攻撃力に影響されますか？',
    kr: 'DoT는 공격력의 영향을 받나요?',
    zh: 'DoT受攻击力影响吗？',
    fr: "Les DoTs scalent-ils avec l'ATK ?",
  },
  q_penVsDots: {
    en: 'Does Penetration affect DoT or true damage?',
    jp: '貫通はDoTや固定ダメージに影響しますか？',
    kr: '관통이 DoT나 고정 데미지에 영향을 주나요?',
    zh: '穿透影响DoT或固定伤害吗？',
    fr: 'La PEN affecte-t-elle les DoT ou les true damage ?',
  },
  q_dmgUpVsChd: {
    en: "What's the difference between DMG UP and Crit Damage?",
    jp: 'DMG UPとクリダメの違いは？',
    kr: 'DMG UP과 치명타 데미지의 차이는?',
    zh: 'DMG UP和暴击伤害有什么区别？',
    fr: 'Quelle est la différence entre DMG UP et CHD ?',
  },
  q_dmgRedVsCdmgRed: {
    en: "What's the difference between DMG RED and CDMG RED?",
    jp: 'DMG REDとCDMG REDの違いは？',
    kr: 'DMG RED와 CDMG RED의 차이는?',
    zh: 'DMG RED和CDMG RED有什么区别？',
    fr: 'Quelle est la différence entre DMG RED et CDMG RED ?',
  },
  q_dmgAdditive: {
    en: 'How does the additive calculation work?',
    jp: '加算計算はどう機能しますか？',
    kr: '합산 계산은 어떻게 작동하나요?',
    zh: '加算计算如何运作？',
    fr: 'Comment fonctionne le calcul additif ?',
  },
  q_dmgRedCap: {
    en: 'Is there a cap on Damage Reduction?',
    jp: 'ダメージ軽減に上限はありますか？',
    kr: '데미지 감소에 상한이 있나요?',
    zh: '伤害减免有上限吗？',
    fr: 'Y a-t-il un cap sur la DMG Reduction ?',
  },
  q_debuffOnMiss: {
    en: 'What happens when an attack misses?',
    jp: '攻撃がミスした場合どうなりますか？',
    kr: '공격이 미스하면 어떻게 되나요?',
    zh: '攻击未命中会怎样？',
    fr: 'Que se passe-t-il quand une attaque rate ?',
  },
  q_effResFormula: {
    en: 'Is there a minimum debuff success chance?',
    jp: 'デバフ成功確率の最低値はありますか？',
    kr: '디버프 성공 확률의 최솟값이 있나요?',
    zh: '减益成功率有最低值吗？',
    fr: "Y a-t-il une chance minimale d'appliquer un Debuff ?",
  },
  q_penVsHighDef: {
    en: 'Is Penetration more effective against high DEF?',
    jp: '貫通は高DEFに対してより効果的ですか？',
    kr: '관통은 높은 DEF에 더 효과적인가요?',
    zh: '穿透对高DEF更有效吗？',
    fr: 'La PEN est-elle plus efficace contre une DEF élevée ?',
  },
  q_fixedDamageMitigation: {
    en: 'Can Defense reduce fixed damage?',
    jp: '防御力は固定ダメージを軽減できますか？',
    kr: '방어력이 고정 데미지를 감소시킬 수 있나요?',
    zh: '防御力能减免固定伤害吗？',
    fr: 'La DEF peut-elle réduire les fixed damage ?',
  },
  q_dualScaling: {
    en: 'Can skills scale with more than one stat?',
    jp: 'スキルは複数のステータスに依存できますか？',
    kr: '스킬이 여러 스탯에 의존할 수 있나요?',
    zh: '技能可以依赖多个属性吗？',
    fr: "Un skill peut-il scaler avec plus d'une stat ?",
  },
  q_statScaling: {
    en: 'How do I know which stats are used for a skill?',
    jp: 'スキルがどのステータスを使うかはどうやって分かりますか？',
    kr: '스킬이 어떤 스탯을 사용하는지 어떻게 알 수 있나요?',
    zh: '如何知道技能使用什么属性？',
    fr: 'Comment savoir quelles stats sont utilisées par un skill ?',
  },
  q_speedFormula: {
    en: 'How is speed calculated?',
    jp: '速度はどう計算されますか？',
    kr: '속도는 어떻게 계산되나요?',
    zh: '速度如何计算？',
    fr: 'Comment la SPD est-elle calculée ?',
  },
  q_priorityFormula: {
    en: 'How is turn 1 priority calculated?',
    jp: '1ターン目の優先度はどう計算されますか？',
    kr: '1턴 우선도는 어떻게 계산되나요?',
    zh: '第1回合行动值如何计算？',
    fr: 'Comment la priorité du tour 1 est-elle calculée ?',
  },
  q_maxSpeed: {
    en: 'Max theoretical speed',
    jp: '理論上の最大速度',
    kr: '이론상 최대 속도',
    zh: '理论最大速度',
    fr: 'SPD théorique maximale',
  },
  q_formula: {
    en: 'How calculations are done',
    jp: '計算の仕組み',
    kr: '계산 방식',
    zh: '计算方法',
    fr: 'Comment les calculs sont effectués',
  },
  q_damageFormula: {
    en: 'What is the full damage formula in Outerplane?',
    jp: 'Outerplaneの完全なダメージ計算式は？',
    kr: 'Outerplane의 전체 데미지 공식은?',
    zh: 'Outerplane的完整伤害公式是什么？',
    fr: 'Quelle est la formule complète de dégâts dans Outerplane ?',
  },

  // Réponses simples (texte)
  a_critCap: {
    en: 'No. Crit Rate is capped at 100%. Any excess has no effect.',
    jp: 'いいえ。クリ率は100%が上限です。超過分は効果がありません。',
    kr: '아니요. 치명타 확률은 100%가 상한입니다. 초과분은 효과가 없습니다.',
    zh: '不可以。暴击率上限为100%。超出部分无效。',
    fr: "Non. Le CHC est cap à 100%. Tout excès n'a aucun effet.",
  },
  a_critOnHeal: {
    en: 'No. Healing, shielding, and utility skills cannot crit unless explicitly stated. Crit mechanics only apply to damage-dealing skills.',
    jp: 'いいえ。回復、シールド、ユーティリティスキルは明示されない限りクリティカルしません。クリティカルメカニクスはダメージスキルにのみ適用されます。',
    kr: '아니요. 힐, 보호막, 유틸리티 스킬은 명시되지 않는 한 치명타가 되지 않습니다. 치명타 메카닉은 데미지 스킬에만 적용됩니다.',
    zh: '不可以。治疗、护盾和辅助技能除非特别说明，否则不会暴击。暴击机制仅适用于伤害技能。',
    fr: "Non. Les heals, shields et utility skills ne peuvent pas crit sauf mention explicite. Les mécaniques de crit ne s'appliquent qu'aux skills de dégâts.",
  },
  a_dotCrit: {
    en: 'No. Damage over Time effects (burn, bleed, poison, etc.) do not scale with Crit Rate or Crit Damage. They cannot crit.',
    jp: 'いいえ。継続ダメージ効果（火傷、出血、毒など）はクリ率やクリダメの影響を受けません。クリティカルしません。',
    kr: '아니요. 지속 데미지 효과(화상, 출혈, 독 등)는 치명타 확률이나 치명타 데미지의 영향을 받지 않습니다. 치명타가 되지 않습니다.',
    zh: '不受。持续伤害效果（如燃烧、流血、中毒等）不受暴击率或暴击伤害影响。它们不会暴击。',
    fr: 'Non. Les effets DoT (burn, bleed, poison, etc.) ne scalent pas avec le CHC ou le CHD. Ils ne peuvent pas crit.',
  },
  a_dotScaling: {
    en: "Yes. Some DoTs scale with the caster's ATK stat, though the scaling ratio is usually lower than for direct damage.",
    jp: 'はい。一部のDoTは術者の攻撃力に依存しますが、直接ダメージより倍率は低めです。',
    kr: '네. 일부 DoT는 시전자의 공격력에 의존하지만, 직접 데미지보다 배율이 낮습니다.',
    zh: '是的。部分DoT依赖施放者的攻击力，但系数比直接伤害低。',
    fr: "Oui. Certains DoTs scalent avec l'ATK du caster, bien que le ratio soit généralement plus faible que pour les dégâts directs.",
  },
  a_dmgUpVsChd: {
    en: "DMG UP applies on every attack regardless of whether it crits. Crit Damage only applies when a critical hit occurs. On a crit, both are added together (along with any skill/equipment DMG UP bonuses) before being compared to the enemy's defensive pool (DMG RED + CDMG RED + their skill/equipment reductions). All sources are additive within their respective group.",
    jp: 'DMG UPはクリティカルかどうかに関わらず全ての攻撃に適用されます。クリダメはクリティカルヒット時のみ適用。クリティカル時、両方の値が加算されてから敵の防御修正値（DMG RED + CDMG RED）と比較されます。',
    kr: 'DMG UP은 치명 여부와 관계없이 모든 공격에 적용됩니다. 치명타 데미지는 치명 발생 시에만 적용. 치명 시 두 값이 합산된 후 적의 방어 보정치(DMG RED + CDMG RED)와 비교됩니다.',
    zh: 'DMG UP无论是否暴击都适用于所有攻击。暴击伤害仅在暴击时生效。暴击时，两个值相加后与敌方防御修正（DMG RED + CDMG RED）比较。',
    fr: "Le DMG UP s'applique à chaque attaque qu'elle crit ou non. Le CHD ne s'applique qu'en cas de crit. Lors d'un crit, les deux sont additionnés (avec les bonus de DMG UP de skill/equipment) avant d'être comparés au pool défensif de l'ennemi (DMG RED + CDMG RED + ses réductions de skill/equipment). Toutes les sources sont additives au sein de leur groupe respectif.",
  },
  a_dmgRedVsCdmgRed: {
    en: "DMG RED opposes the attacker's DMG UP on every hit — it is subtracted from their Damage Increase total, not applied as a flat percentage. CDMG RED only activates on critical hits. When critically hit, both DMG RED and CDMG RED are summed to counter the attacker's CHD + DMG UP.",
    jp: 'DMG REDは全ての受けるダメージを軽減し、CDMG REDはクリティカルヒットからのダメージのみ軽減します。クリティカル被弾時、両方の値が加算されて敵のCHD + DMG UPに対抗します。',
    kr: 'DMG RED는 모든 받는 데미지를 감소시키고, CDMG RED는 치명타 데미지만 감소시킵니다. 치명 피격 시 두 값이 합산되어 적의 CHD + DMG UP에 대항합니다.',
    zh: 'DMG RED减少所有受到的伤害，CDMG RED仅减少暴击伤害。被暴击时，两个值相加以对抗敌方的CHD + DMG UP。',
    fr: "Le DMG RED s'oppose au DMG UP de l'attaquant à chaque coup : il est soustrait de son total d'Increase de dégâts, pas appliqué comme un pourcentage plat. Le CDMG RED ne s'active que sur les coups critiques. Lors d'un crit reçu, le DMG RED et le CDMG RED sont additionnés pour contrer le CHD + DMG UP de l'attaquant.",
  },
  a_dmgAdditive: {
    en: 'All increase-type effects (CHD on crit, DMG UP, skill/equip DMG UP) are summed into one group. All reduction-type effects (CDMG RED on crit, DMG RED, skill/equip DMG RED) are summed into another. The final modifier is: (Total Increase) − (Total Reduction). This result is then applied before Defense and Final Damage modifiers.',
    jp: '攻撃側：DMG UPがクリダメに加算（クリティカル時）。防御側：DMG REDがCDMG REDに加算（クリティカル時）。攻撃側の合計が防御側の合計と比較され、最終的なダメージ修正が決定されます。',
    kr: '공격 측: DMG UP이 치명타 데미지에 합산(치명 시). 방어 측: DMG RED가 CDMG RED에 합산(치명 시). 공격 측 합계가 방어 측 합계와 비교되어 최종 데미지 보정이 결정됩니다.',
    zh: '攻击方：DMG UP与暴击伤害相加（暴击时）。防御方：DMG RED与CDMG RED相加（暴击时）。攻击方总计与防御方总计比较，决定最终伤害修正。',
    fr: "Tous les effets d'increase (CHD en crit, DMG UP, DMG UP de skill/equip) sont sommés dans un groupe. Tous les effets de réduction (CDMG RED en crit, DMG RED, DMG RED de skill/equip) sont sommés dans un autre. Le modificateur final est : (Total Increase) − (Total Reduction). Ce résultat est appliqué avant la DEF et les modificateurs de Final Damage.",
  },
  a_dmgRedCap: {
    en: 'Yes. The damage modifier system has a built-in rate floor of 0.30, capping reduction from DMG RED + CDMG RED at 70% via this layer. Defense and Final Damage Reduction (boss-specific final-damage-reduction passives) are calculated separately and are not affected by this cap.',
    jp: 'はい。ダメージ修正システムには0.30のレートフロアが組み込まれており、この層を通じたDMG RED + CDMG REDによる軽減は70%が上限です。防御力と最終ダメージ軽減（ボス固有の最終ダメージ軽減パッシブ）は別計算で、この上限の影響を受けません。',
    kr: '네. 데미지 보정 시스템에는 0.30의 레이트 하한이 내장되어 있어, 이 층을 통한 DMG RED + CDMG RED 감소는 최대 70%로 제한됩니다. 방어력과 최종 데미지 감소(보스 전용 최종 데미지 감소 패시브)는 별도로 계산되며 이 상한의 영향을 받지 않습니다.',
    zh: '是的。伤害修正系统内置了0.30的速率下限，使得通过此层的DMG RED + CDMG RED最多只能减免70%伤害。防御力和最终伤害减免（首领专属的最终伤害减免被动）是独立计算的，不受此上限影响。',
    fr: 'Oui. Le système de modificateur de dégâts intègre un floor de 0.30, ce qui cap la réduction via DMG RED + CDMG RED à 70% sur cette couche. La DEF et la Final Damage Reduction (passives boss-specific) sont calculées séparément et ne sont pas affectées par ce cap.',
  },
  a_effResFormula: {
    en: "No. The success chance depends on the difference between the attacker's Effectiveness (EFF) and the target's Resilience (RES). If EFF ≥ RES, the success chance is 100%. Otherwise, the chance decreases with a lower bound that depends on how much RES exceeds EFF. For example, a RES − EFF difference of 300 leads to a 25% chance, and a difference of 900 leads to only 10%.",
    jp: 'いいえ。成功確率は攻撃者の効果命中（EFF）と対象の効果抵抗（RES）の差に依存します。EFF ≥ RESなら100%成功。それ以外は、RESがEFFを超える量に応じて確率が下がります。例えば、RES − EFFの差が300なら25%、900なら10%のみです。',
    kr: '아니요. 성공 확률은 공격자의 효과 적중(EFF)과 대상의 효과 저항(RES) 차이에 의존합니다. EFF ≥ RES면 100% 성공. 그 외에는 RES가 EFF를 초과하는 양에 따라 확률이 감소합니다. 예를 들어, RES − EFF 차이가 300이면 25%, 900이면 10%만 됩니다.',
    zh: '没有。成功率取决于攻击者的效果命中(EFF)和目标的效果抵抗(RES)之差。EFF ≥ RES时100%成功。否则根据RES超过EFF的量递减。例如，RES − EFF差值为300时只有25%，900时只有10%。',
    fr: "Non. La chance de succès dépend de la différence entre l'EFF de l'attaquant et la RES de la cible. Si EFF ≥ RES, la chance est de 100%. Sinon, elle diminue avec une borne inférieure dépendant de l'écart RES − EFF. Par exemple, un écart de 300 donne 25% de chance, et un écart de 900 seulement 10%.",
  },
  a_penVsHighDef: {
    en: 'Yes. The more DEF the enemy has, the greater the damage gain from Penetration, since it reduces the effective DEF used in the damage formula.',
    jp: 'はい。敵のDEFが高いほど、貫通によるダメージ増加が大きくなります。ダメージ計算式で有効DEFを減らすためです。',
    kr: '네. 적의 DEF가 높을수록 관통으로 인한 데미지 증가가 커집니다. 데미지 공식에서 유효 DEF를 줄이기 때문입니다.',
    zh: '是的。敌人DEF越高，穿透带来的伤害增幅越大。因为它减少了伤害公式中的有效DEF。',
    fr: "Oui. Plus l'ennemi a de DEF, plus le gain de dégâts grâce à la PEN est important, car elle réduit la DEF effective utilisée dans la formule.",
  },
  a_fixedDamageMitigation: {
    en: 'No. Fixed damage ignores DEF. Only shields or invincibility can prevent it.',
    jp: 'いいえ。固定ダメージはDEFを無視します。シールドまたは無敵のみで防げます。',
    kr: '아니요. 고정 데미지는 DEF를 무시합니다. 보호막이나 무적만으로 막을 수 있습니다.',
    zh: '不能。固定伤害忽略DEF。只能用护盾或无敌来阻挡。',
    fr: "Non. Les fixed damage ignorent la DEF. Seuls les shields ou l'invincibilité peuvent les empêcher.",
  },

  // penVsDots (riche)
  pvd_p1: {
    en: 'It depends on the DoT type. Some DoTs are reduced by DEF and therefore benefit from Penetration:',
    jp: 'DoTの種類によります。DEFで軽減されるDoTは貫通の恩恵を受けます：',
    kr: 'DoT 종류에 따라 다릅니다. DEF로 감소되는 DoT는 관통의 혜택을 받습니다:',
    zh: '取决于DoT类型。被DEF减免的DoT受穿透加成：',
    fr: 'Cela dépend du type de DoT. Certains DoTs sont réduits par la DEF et bénéficient donc de la PEN :',
  },
  pvd_p2: {
    en: 'However, some DoTs ignore DEF entirely and are unaffected by Penetration:',
    jp: 'ただし、DEFを完全に無視し、貫通の影響を受けないDoTもあります：',
    kr: '하지만 DEF를 완전히 무시하고 관통의 영향을 받지 않는 DoT도 있습니다:',
    zh: '但部分DoT完全忽略DEF，不受穿透影响：',
    fr: 'Cependant, certains DoTs ignorent complètement la DEF et ne sont pas affectés par la PEN :',
  },
  pvd_p3: {
    en: 'Fixed damage always ignores DEF and is unaffected by Penetration.',
    jp: '固定ダメージは常にDEFを無視し、貫通の影響を受けません。',
    kr: '고정 데미지는 항상 DEF를 무시하며 관통의 영향을 받지 않습니다.',
    zh: '固定伤害始终忽略DEF，不受穿透影响。',
    fr: 'Les fixed damage ignorent toujours la DEF et ne sont pas affectés par la PEN.',
  },

  // debuffOnMiss (riche)
  dom_p1: {
    en: 'When a miss occurs, the attack deals **50% reduced damage**, and neither debuffs nor critical hits can occur.',
    jp: 'ミス発生時、攻撃のダメージが**50%減少**し、デバフもクリティカルも発生しません。',
    kr: '미스 발생 시 공격 데미지가 **50% 감소**하며, 디버프와 치명타 모두 발생하지 않습니다.',
    zh: '未命中时，攻击伤害**减少50%**，且不会触发减益和暴击。',
    fr: "Lorsqu'un miss survient, l'attaque inflige **50% de dégâts en moins**, et ni les debuffs ni les coups critiques ne peuvent se produire.",
  },
  dom_p2: {
    en: 'A miss can occur when the attacker is affected by effects like {B/BT_STAT|ST_AVOID}, which increases the miss rate by 15%.',
    jp: '{B/BT_STAT|ST_AVOID}などの効果により、ミス率が15%上昇することでミスが発生します。',
    kr: '{B/BT_STAT|ST_AVOID} 등의 효과로 빗나감 확률이 15% 증가하여 미스가 발생할 수 있습니다.',
    zh: '通过{B/BT_STAT|ST_AVOID}等效果使未命中率提升15%，可导致未命中发生。',
    fr: "Un miss peut survenir lorsque l'attaquant est affecté par des effets comme {B/BT_STAT|ST_AVOID}, qui augmente le taux de miss de 15%.",
  },

  // dualScaling (riche)
  ds_p1: {
    en: 'Not exactly. Outerplane does not currently feature skills that use two stats evenly (e.g., 50% ATK + 50% HP). What is often referred to as "dual-scaling" is actually **secondary scaling** — a main stat (usually ATK), with a minor bonus from another stat like HP or SPD.',
    jp: '正確には違います。Outerplaneには現在、2つのステータスを均等に使うスキル（例：50% ATK + 50% HP）はありません。「デュアルスケーリング」と呼ばれるものは実際には**副次依存**です — メインステータス（通常ATK）に、HPやSPDなどの副次ボーナスが加わります。',
    kr: '정확히는 아닙니다. Outerplane에는 현재 두 스탯을 균등하게 사용하는 스킬(예: 50% ATK + 50% HP)이 없습니다. "듀얼 스케일링"이라고 불리는 것은 실제로 **부차 의존**입니다 — 메인 스탯(보통 ATK)에 HP나 SPD 등의 부차 보너스가 추가됩니다.',
    zh: '严格来说不能。Outerplane目前没有均匀使用两个属性的技能（如50% ATK + 50% HP）。所谓的"双重依赖"实际上是**次要依赖**——主属性（通常是ATK）加上HP或SPD等的次要加成。',
    fr: "Pas vraiment. Outerplane ne propose actuellement aucun skill utilisant deux stats à parts égales (par ex. 50% ATK + 50% HP). Ce qu'on appelle souvent \"dual-scaling\" est en réalité du **scaling secondaire** — une stat principale (généralement l'ATK), avec un bonus mineur d'une autre stat comme les HP ou la SPD.",
  },
  ds_p2: {
    en: "For example, some skills primarily scale with ATK but gain a bonus from the caster's Max HP or Speed. {P/Demiurge Stella} has partial scaling from HP.",
    jp: '例えば、一部のスキルはATKをメインに、術者の最大HPや速度からボーナスを得ます。{P/Demiurge Stella}はHPからの部分依存を持ちます。',
    kr: '예를 들어, 일부 스킬은 ATK를 메인으로 시전자의 최대 HP나 속도에서 보너스를 얻습니다. {P/Demiurge Stella}는 HP에서 부분 의존을 가집니다.',
    zh: '例如，部分技能以ATK为主，并从施放者的最大HP或速度获得加成。{P/Demiurge Stella}有HP的部分依赖。',
    fr: "Par exemple, certains skills scalent principalement avec l'ATK mais gagnent un bonus à partir des Max HP ou de la SPD du caster. {P/Demiurge Stella} a un scaling partiel sur les HP.",
  },
  ds_p3: {
    en: 'These secondary scalings are usually small and should not be the focus of gear building. There are also skills that use a stat other than ATK entirely — such as HP-based or DEF-based damage.',
    jp: 'これらの副次依存は通常小さく、装備構築の焦点にすべきではありません。ATK以外のステータスに完全に依存するスキル（HP依存やDEF依存ダメージなど）もあります。',
    kr: '이러한 부차 의존은 보통 작으며 장비 구성의 초점이 되어서는 안 됩니다. ATK 외의 스탯에 완전히 의존하는 스킬(HP 기반이나 DEF 기반 데미지 등)도 있습니다.',
    zh: '这些次要依赖通常较小，不应成为装备配置的重点。也有技能完全依赖ATK以外的属性（如基于HP或DEF的伤害）。',
    fr: "Ces scalings secondaires sont généralement faibles et ne doivent pas guider le build de gear. Il existe aussi des skills qui utilisent uniquement une stat autre que l'ATK — comme des dégâts basés sur les HP ou la DEF.",
  },

  // statScaling (riche)
  ss_p1: {
    en: 'If nothing is mentioned, the skill usually scales with ATK by default.',
    jp: '何も記載がなければ、通常はデフォルトでATK依存です。',
    kr: '아무것도 언급되지 않으면 보통 기본적으로 ATK 의존입니다.',
    zh: '如果没有提及，通常默认依赖ATK。',
    fr: "Si rien n'est mentionné, le skill scale par défaut avec l'ATK.",
  },
  ss_p2: {
    en: "If it uses a different stat, you'll see one of these:",
    jp: '異なるステータスを使う場合、以下のような記述があります：',
    kr: '다른 스탯을 사용하면 다음과 같은 문구가 있습니다:',
    zh: '如果使用其他属性，会有类似描述：',
    fr: "S'il utilise une autre stat, vous verrez l'une de ces mentions :",
  },
  ss_b1: {
    en: '"Damage dealt increases proportional to Max Health **instead of** Attack."',
    jp: '「与えるダメージは攻撃力**ではなく**最大体力に比例して増加します。」',
    kr: '"주는 데미지는 공격력 **대신** 최대 체력에 비례하여 증가합니다."',
    zh: '"造成的伤害根据最大生命值**而非**攻击力增加。"',
    fr: '"Damage dealt increases proportional to Max Health **au lieu de** Attack."',
  },
  ss_b2: {
    en: '"Damage dealt increases proportional to Max Health." (in addition to ATK)',
    jp: '「与えるダメージは最大体力に比例して増加します。」（ATKに加えて）',
    kr: '"주는 데미지는 최대 체력에 비례하여 증가합니다." (ATK에 추가로)',
    zh: '"造成的伤害根据最大生命值增加。"（在ATK基础上）',
    fr: '"Damage dealt increases proportional to Max Health." (in addition to ATK)',
  },
  ss_p3: {
    en: 'The wording is important: "instead of" replaces ATK scaling, while without it means additional scaling.',
    jp: '表現が重要です：「ではなく」はATK依存を置き換え、それがない場合は追加依存を意味します。',
    kr: '문구가 중요합니다: "대신"은 ATK 의존을 대체하고, 없으면 추가 의존을 의미합니다.',
    zh: '措辞很重要："而非"表示替代ATK依赖，没有则表示额外依赖。',
    fr: 'La formulation est importante : "instead of" remplace le scaling ATK, alors que son absence indique un scaling additionnel.',
  },

  // speedFormula (riche)
  sf_p1: {
    en: 'The base formula used to calculate speed in **Outerplane** is:',
    jp: '**Outerplane**での速度計算の基本式：',
    kr: '**Outerplane**에서 속도 계산의 기본 공식:',
    zh: '**Outerplane**速度计算基础公式：',
    fr: 'La formule de base pour calculer la SPD dans **Outerplane** est :',
  },
  sf_formula: {
    en: 'SPD = Base SPD + Gear SPD + (Base SPD × Set Effect %)',
    jp: 'SPD = 基本SPD + 装備SPD + (基本SPD × セット効果%)',
    kr: 'SPD = 기본 SPD + 장비 SPD + (기본 SPD × 세트 효과%)',
    zh: 'SPD = 基础SPD + 装备SPD + (基础SPD × 套装效果%)',
    fr: 'SPD = Base SPD + Gear SPD + (Base SPD × Set Effect %)',
  },
  sf_base: {
    en: "**Base SPD:** The character's innate, unmodified speed.",
    jp: '**基本SPD：** キャラクターの固有の未修正速度。',
    kr: '**기본 SPD:** 캐릭터의 고유 미수정 속도.',
    zh: '**基础SPD：** 角色固有的未修正速度。',
    fr: '**SPD de base :** SPD intrinsèque et non modifiée du personnage.',
  },
  sf_gear: {
    en: '**Gear SPD:** Flat speed gained from equipped gear.',
    jp: '**装備SPD：** 装備から得た固定速度。',
    kr: '**장비 SPD:** 장비에서 얻은 고정 속도.',
    zh: '**装备SPD：** 装备提供的固定速度。',
    fr: '**SPD de gear :** SPD flat obtenue depuis le gear équipé.',
  },
  sf_set: {
    en: '**Set Effect:**',
    jp: '**セット効果：**',
    kr: '**세트 효과:**',
    zh: '**套装效果：**',
    fr: '**Effet de Set :**',
  },
  sf_set0: {
    en: '0 if no Speed set equipped',
    jp: '速度セットなし = 0',
    kr: '속도 세트 없음 = 0',
    zh: '无速度套装 = 0',
    fr: '0 si pas de Set Speed équipé',
  },
  sf_set2: {
    en: '0.12 (12%) if 2-piece Speed set',
    jp: '2セット速度 = 0.12 (12%)',
    kr: '2세트 속도 = 0.12 (12%)',
    zh: '2件速度套装 = 0.12 (12%)',
    fr: '0.12 (12%) avec un Set Speed 2-pièces',
  },
  sf_set4: {
    en: '0.25 (25%) if 4-piece Speed set',
    jp: '4セット速度 = 0.25 (25%)',
    kr: '4세트 속도 = 0.25 (25%)',
    zh: '4件速度套装 = 0.25 (25%)',
    fr: '0.25 (25%) avec un Set Speed 4-pièces',
  },

  // priorityFormula (riche)
  pf_p1: {
    en: 'The formula used to calculate initial priority at the start of battle:',
    jp: '戦闘開始時の初期優先度計算式：',
    kr: '전투 시작 시 초기 우선도 계산 공식:',
    zh: '战斗开始时的初始行动值计算公式：',
    fr: 'La formule pour calculer la priorité initiale en début de combat :',
  },
  pf_formula: {
    en: 'Priority = (SPD + Ally Speed transcend bonus + (SPD × Buff %)) × 100 / (Top SPD + Top SPD team Ally Speed transcend bonus + (Top SPD × Buff %))',
    jp: '優先度 = (SPD + 味方速度超越ボーナス + (SPD × バフ%)) × 100 / (最高SPD + 最高SPDチーム味方速度超越ボーナス + (最高SPD × バフ%))',
    kr: '우선도 = (SPD + 아군 속도 초월 보너스 + (SPD × 버프%)) × 100 / (최고 SPD + 최고 SPD 팀 아군 속도 초월 보너스 + (최고 SPD × 버프%))',
    zh: '行动值 = (SPD + 友方速度超越加成 + (SPD × 增益%)) × 100 / (最高SPD + 最高SPD队友方速度超越加成 + (最高SPD × 增益%))',
    fr: 'Priority = (SPD + Ally Speed transcend bonus + (SPD × Buff %)) × 100 / (Top SPD + Top SPD team Ally Speed transcend bonus + (Top SPD × Buff %))',
  },
  pf_spd: {
    en: '**SPD:** Total speed of the unit, as calculated above.',
    jp: '**SPD：** 上記で計算されたユニットの総速度。',
    kr: '**SPD:** 위에서 계산된 유닛의 총 속도.',
    zh: '**SPD：** 单位的总速度（如上计算）。',
    fr: "**SPD :** SPD totale de l'unité, calculée comme ci-dessus.",
  },
  pf_top: {
    en: '**Top SPD:** Highest SPD among all units (used as divisor).',
    jp: '**最高SPD：** 全ユニット中の最高SPD（除数として使用）。',
    kr: '**최고 SPD:** 모든 유닛 중 최고 SPD (제수로 사용).',
    zh: '**最高SPD：** 所有单位中最高的SPD（作为除数）。',
    fr: '**SPD max :** SPD la plus élevée parmi toutes les unités (utilisée comme diviseur).',
  },
  pf_transcend: {
    en: '**Ally Speed transcend bonus:** Speed from transcendence.',
    jp: '**味方速度超越ボーナス：** 超越からの速度。',
    kr: '**아군 속도 초월 보너스:** 초월에서 얻은 속도.',
    zh: '**友方速度超越加成：** 从超越获得的速度。',
    fr: '**Bonus Ally Speed de transcendance :** SPD obtenue via la transcendance.',
  },
  pf_buff: {
    en: '**Buff:**',
    jp: '**バフ：**',
    kr: '**버프:**',
    zh: '**增益：**',
    fr: '**Buff :**',
  },
  pf_buff0: {
    en: '0 if no buff speed',
    jp: '速度バフなし = 0',
    kr: '속도 버프 없음 = 0',
    zh: '无速度增益 = 0',
    fr: '0 si pas de buff SPD',
  },
  pf_buff30: {
    en: '0.3 (30%) if buff speed',
    jp: '速度バフ = 0.3 (30%)',
    kr: '속도 버프 = 0.3 (30%)',
    zh: '速度增益 = 0.3 (30%)',
    fr: '0.3 (30%) avec un buff SPD',
  },
  pf_buffm30: {
    en: '-0.3 (-30%) if malus speed',
    jp: '速度デバフ = -0.3 (-30%)',
    kr: '속도 디버프 = -0.3 (-30%)',
    zh: '速度减益 = -0.3 (-30%)',
    fr: '-0.3 (-30%) avec un malus SPD',
  },

  // maxSpeed (riche)
  ms_p1: {
    en: 'The maximum theoretical speed is:',
    jp: '理論上の最大速度：',
    kr: '이론상 최대 속도:',
    zh: '理论最大速度：',
    fr: 'La SPD théorique maximale est :',
  },
  ms_base: {
    en: '**Base speed:** 154 hit by {C/Ranger}',
    jp: '**基本速度：** {C/Ranger}の154',
    kr: '**기본 속도:** {C/Ranger}의 154',
    zh: '**基础速度：** {C/Ranger}的154',
    fr: '**SPD de base :** 154 atteint par {C/Ranger}',
  },
  ms_gear: {
    en: '**Gear SPD:** 145 (18 per piece + 55 from Accessory)',
    jp: '**装備SPD：** 145（各部位18 + アクセサリー55）',
    kr: '**장비 SPD:** 145 (각 부위 18 + 악세사리 55)',
    zh: '**装备SPD：** 145（每部位18 + 饰品55）',
    fr: "**SPD de gear :** 145 (18 par pièce + 55 depuis l'Accessory)",
  },
  ms_set: {
    en: '**Set SPD:** 38 (on a 154 character)',
    jp: '**セットSPD：** 38（154キャラで）',
    kr: '**세트 SPD:** 38 (154 캐릭터 기준)',
    zh: '**套装SPD：** 38（基于154角色）',
    fr: '**SPD de set :** 38 (sur un personnage à 154)',
  },
  ms_transcend: {
    en: '**Ally Speed transcend bonus:** 30 ({P/Dianne} + {P/Mene} + {P/Demiurge Delta})',
    jp: '**味方速度超越ボーナス：** 30（{P/Dianne} + {P/Mene} + {P/Demiurge Delta}）',
    kr: '**아군 속도 초월 보너스:** 30 ({P/Dianne} + {P/Mene} + {P/Demiurge Delta})',
    zh: '**友方速度超越加成：** 30（{P/Dianne} + {P/Mene} + {P/Demiurge Delta}）',
    fr: '**Bonus Ally Speed de transcendance :** 30 ({P/Dianne} + {P/Mene} + {P/Demiurge Delta})',
  },
  ms_total: {
    en: 'Leading to a grand total of: **367** (468 including the speed buff)',
    jp: '合計：**367**（速度バフ込みで468）',
    kr: '합계: **367** (속도 버프 포함 시 468)',
    zh: '总计：**367**（带速度增益时468）',
    fr: 'Pour un total de : **367** (468 avec le buff SPD inclus)',
  },
  ms_ryu: {
    en: '{P/Ryu Lion} can go further with her 4 star transcend bonus: **377** (478 with speed buff)',
    jp: '{P/Ryu Lion}は4つ星超越ボーナスでさらに上げられます：**377**（速度バフ込みで478）',
    kr: '{P/Ryu Lion}은 4성 초월 보너스로 더 올릴 수 있습니다: **377** (속도 버프 포함 시 478)',
    zh: '{P/Ryu Lion}的4星超越加成可进一步提升：**377**（带速度增益时478）',
    fr: '{P/Ryu Lion} peut aller plus loin avec son bonus de transcendance 4 étoiles : **377** (478 avec le buff SPD)',
  },

  // formula (riche)
  fm_p1: {
    en: 'The following formulas and explanations were gathered and tested by **Enebe-NB**, who did an amazing job analyzing combat formulas in Outerplane.',
    jp: '以下の計算式と説明は**Enebe-NB**によって収集・検証されました。Outerplaneの戦闘計算式を分析した素晴らしい仕事です。',
    kr: '다음 공식과 설명은 **Enebe-NB**가 수집하고 테스트했습니다. Outerplane의 전투 공식을 분석한 훌륭한 작업입니다.',
    zh: '以下公式和说明由**Enebe-NB**收集和测试。这是对Outerplane战斗公式的出色分析工作。',
    fr: "Les formules et explications suivantes ont été rassemblées et testées par **Enebe-NB**, qui a fait un travail remarquable d'analyse des formules de combat d'Outerplane.",
  },
  fm_p2: {
    en: 'For full reference, the data is available here: {L/[Google Sheet - Outerplane Analysis by Enebe-NB]|https://docs.google.com/spreadsheets/d/10Sl_b7n7_j-PxkNxYGZEvu7HvrJNyRYDSyyYLcUwDOU/edit?gid=938189457#gid=938189457}',
    jp: '完全な参照はこちら：{L/[Google Sheet - Outerplane Analysis by Enebe-NB]|https://docs.google.com/spreadsheets/d/10Sl_b7n7_j-PxkNxYGZEvu7HvrJNyRYDSyyYLcUwDOU/edit?gid=938189457#gid=938189457}',
    kr: '전체 참조는 여기: {L/[Google Sheet - Outerplane Analysis by Enebe-NB]|https://docs.google.com/spreadsheets/d/10Sl_b7n7_j-PxkNxYGZEvu7HvrJNyRYDSyyYLcUwDOU/edit?gid=938189457#gid=938189457}',
    zh: '完整参考：{L/[Google Sheet - Outerplane Analysis by Enebe-NB]|https://docs.google.com/spreadsheets/d/10Sl_b7n7_j-PxkNxYGZEvu7HvrJNyRYDSyyYLcUwDOU/edit?gid=938189457#gid=938189457}',
    fr: 'Pour la référence complète, les données sont disponibles ici : {L/[Google Sheet - Outerplane Analysis by Enebe-NB]|https://docs.google.com/spreadsheets/d/10Sl_b7n7_j-PxkNxYGZEvu7HvrJNyRYDSyyYLcUwDOU/edit?gid=938189457#gid=938189457}',
  },
  fm_h_def: {
    en: 'Defense Mitigation',
    jp: '防御軽減',
    kr: '방어 감소',
    zh: '防御减免',
    fr: 'Mitigation par DEF',
  },
  fm_def_label: {
    en: '**Formula:** `f(DEF) = 1000 / (1000 + DEF)`',
    jp: '**計算式：** `f(DEF) = 1000 / (1000 + DEF)`',
    kr: '**공식:** `f(DEF) = 1000 / (1000 + DEF)`',
    zh: '**公式：** `f(DEF) = 1000 / (1000 + DEF)`',
    fr: '**Formule :** `f(DEF) = 1000 / (1000 + DEF)`',
  },
  fm_def_desc: {
    en: 'This formula determines how much damage is reduced by defense. As DEF increases, the effect of each additional point diminishes (diminishing returns).',
    jp: 'この式は防御力によるダメージ軽減量を決定します。DEFが増えるほど、追加ポイントの効果は減少します（収穫逓減）。',
    kr: '이 공식은 방어력에 의한 데미지 감소량을 결정합니다. DEF가 증가할수록 추가 포인트의 효과가 감소합니다(수확 체감).',
    zh: '此公式决定防御力的伤害减免量。DEF增加时，额外点数的效果递减（收益递减）。',
    fr: "Cette formule détermine la quantité de dégâts réduite par la DEF. Plus la DEF augmente, plus l'effet de chaque point supplémentaire diminue (rendements décroissants).",
  },
  fm_ehp_intro: {
    en: 'Effective Health (EHP) can be derived from it (assuming the attacker has 0% PEN):',
    jp: '有効HP（EHP）はここから導出できます（攻撃者がPEN 0%の場合）：',
    kr: '유효 HP(EHP)는 여기서 도출할 수 있습니다 (공격자 PEN 0% 가정):',
    zh: '有效生命值(EHP)可由此推导（假设攻击者穿透为0%）：',
    fr: "On peut en déduire les HP effectifs (EHP), en supposant que l'attaquant a 0% de PEN :",
  },
  fm_ehp: {
    en: '**Effective HP:** `EHP = HP × (1 + DEF / 1000)`',
    jp: '**有効HP：** `EHP = HP × (1 + DEF / 1000)`',
    kr: '**유효 HP:** `EHP = HP × (1 + DEF / 1000)`',
    zh: '**有效HP：** `EHP = HP × (1 + DEF / 1000)`',
    fr: '**HP effectifs :** `EHP = HP × (1 + DEF / 1000)`',
  },
  fm_pen_desc: {
    en: 'When the attacker has Penetration, the effective DEF is reduced before mitigation kicks in:',
    jp: '攻撃者が貫通を持つ場合、軽減計算前に有効DEFが減少します：',
    kr: '공격자가 관통을 가지면 경감 계산 전에 유효 DEF가 감소합니다:',
    zh: '当攻击者带有穿透时，在减免计算之前有效DEF会先减少：',
    fr: "Lorsque l'attaquant a de la PEN, la DEF effective est réduite avant l'application de la mitigation :",
  },
  fm_ehp_pen: {
    en: '**EHP vs PEN:** `EHP = HP × (1 + (1 − PEN%) × DEF / 1000)`',
    jp: '**PEN対応EHP：** `EHP = HP × (1 + (1 − PEN%) × DEF / 1000)`',
    kr: '**PEN 대응 EHP:** `EHP = HP × (1 + (1 − PEN%) × DEF / 1000)`',
    zh: '**考虑穿透时的EHP：** `EHP = HP × (1 + (1 − PEN%) × DEF / 1000)`',
    fr: '**EHP vs PEN :** `EHP = HP × (1 + (1 − PEN%) × DEF / 1000)`',
  },
  fm_h_effres: {
    en: 'Effectiveness vs Resilience',
    jp: '効果命中vs効果抵抗',
    kr: '효과 적중 vs 효과 저항',
    zh: '效果命中 vs 效果抵抗',
    fr: 'EFF vs RES',
  },
  fm_effres_1: {
    en: 'If `EFF ≥ RES`, the debuff success chance is 100%.',
    jp: '`EFF ≥ RES`の場合、デバフ成功確率は100%。',
    kr: '`EFF ≥ RES`면 디버프 성공 확률은 100%.',
    zh: '如果`EFF ≥ RES`，减益成功概率为100%。',
    fr: 'Si `EFF ≥ RES`, la chance de succès du debuff est de 100%.',
  },
  fm_effres_2: {
    en: 'Otherwise, the chance to apply a debuff is calculated using:',
    jp: 'それ以外、デバフ付与確率は以下で計算：',
    kr: '그 외, 디버프 부여 확률은 다음으로 계산:',
    zh: '否则，减益施加概率计算如下：',
    fr: "Sinon, la chance d'appliquer un debuff est calculée ainsi :",
  },
  fm_effres_formula: {
    en: 'Success Chance = 100 / (100 + (RES − EFF))',
    jp: '成功確率 = 100 / (100 + (RES − EFF))',
    kr: '성공 확률 = 100 / (100 + (RES − EFF))',
    zh: '成功概率 = 100 / (100 + (RES − EFF))',
    fr: 'Success Chance = 100 / (100 + (RES − EFF))',
  },

  // damageFormula (riche)
  df_p1: {
    en: 'The full formula used to calculate skill damage in Outerplane is:',
    jp: 'Outerplaneでスキルダメージを計算する完全な計算式：',
    kr: 'Outerplane에서 스킬 데미지를 계산하는 전체 공식:',
    zh: 'Outerplane中计算技能伤害的完整公式：',
    fr: 'La formule complète utilisée pour calculer les dégâts de skill dans Outerplane est :',
  },
  df_formula: {
    en: 'Dmg = ATK × Skill × Mitigation × Rate × Elemental × Marking × Missed × FinalReduce',
    jp: 'Dmg = ATK × スキル × 軽減 × レート × 属性 × マーキング × ミス × 最終軽減',
    kr: 'Dmg = ATK × 스킬 × 경감 × 레이트 × 속성 × 마킹 × 미스 × 최종 경감',
    zh: '伤害 = ATK × 技能 × 减免 × 速率 × 属性 × 标记 × 未命中 × 最终减免',
    fr: 'Dmg = ATK × Skill × Mitigation × Rate × Elemental × Marking × Missed × FinalReduce',
  },
  df_atk: {
    en: "**ATK**: Your unit's main scaling stat (can also be HP, DEF, etc. depending on the skill/character)",
    jp: '**ATK**：ユニットのメイン依存ステータス（スキル/キャラによってHP、DEFなども可）',
    kr: '**ATK**: 유닛의 메인 의존 스탯 (스킬/캐릭터에 따라 HP, DEF 등도 가능)',
    zh: '**ATK**：单位的主要依赖属性（根据技能/角色可能是HP、DEF等）',
    fr: '**ATK** : Stat principale de scaling de votre unité (peut aussi être HP, DEF, etc. selon le skill/personnage)',
  },
  df_skill: {
    en: '**Skill**: Per-skill internal multiplier. Not displayed in-game.',
    jp: '**スキル**：スキルごとの内部倍率。ゲーム内では表示されません。',
    kr: '**스킬**: 스킬별 내부 배율. 게임 내에는 표시되지 않습니다.',
    zh: '**技能**：每个技能的内部倍率。游戏内不显示。',
    fr: '**Skill** : Multiplicateur interne propre au skill. Non affiché in-game.',
  },
  df_mit: {
    en: '**Mitigation**: `1000 / (1000 + (1 − PEN%) × DEF)` — same defense mitigation covered above',
    jp: '**軽減**：`1000 / (1000 + (1 − PEN%) × DEF)` — 上記の防御軽減と同じ',
    kr: '**경감**: `1000 / (1000 + (1 − PEN%) × DEF)` — 위의 방어 감소와 동일',
    zh: '**减免**：`1000 / (1000 + (1 − PEN%) × DEF)` — 与上述防御减免相同',
    fr: '**Mitigation** : `1000 / (1000 + (1 − PEN%) × DEF)` — même mitigation par DEF que vue plus haut',
  },
  df_rate: {
    en: '**Rate**: damage modifier pool, floored at 0.30 (= up to 70% reduction). Computed as:',
    jp: '**レート**：ダメージ修正プール、最小値0.30で上限あり（=最大70%軽減）。計算式：',
    kr: '**레이트**: 데미지 보정 풀, 최소값 0.30 상한(=최대 70% 감소). 계산:',
    zh: '**速率**：伤害修正池，下限为0.30（=最多减免70%）。计算：',
    fr: "**Rate** : pool de modificateurs de dégâts, avec un floor à 0.30 (= jusqu'à 70% de réduction). Calculé ainsi :",
  },
  df_rate_formula: {
    en: 'Rate = max(0.30, base + (DMG UP additions) − (DMG RED + CDMG RED on crit))',
    jp: 'Rate = max(0.30, base + (DMG UP合計) − (DMG RED + クリ時CDMG RED))',
    kr: 'Rate = max(0.30, base + (DMG UP 합산) − (DMG RED + 치명 시 CDMG RED))',
    zh: 'Rate = max(0.30, base + (DMG UP合计) − (DMG RED + 暴击时CDMG RED))',
    fr: 'Rate = max(0.30, base + (DMG UP additions) − (DMG RED + CDMG RED on crit))',
  },
  df_rate_note: {
    en: 'where `base = 1.0` on non-crit, or `CHD/100` on crit. Includes awakening, EE, skill, and gear contributions.',
    jp: 'ここで `base = 1.0`（非クリティカル）／`CHD/100`（クリティカル）。覚醒、EE、スキル、装備の寄与を含む。',
    kr: '여기서 `base = 1.0` (비치명) / `CHD/100` (치명). 각성, EE, 스킬, 장비의 기여 포함.',
    zh: '其中 `base = 1.0`（非暴击）/ `CHD/100`（暴击时）。包含觉醒、EE、技能和装备的贡献。',
    fr: "avec `base = 1.0` sur non-crit, ou `CHD/100` sur crit. Inclut les contributions d'awakening, EE, skill et gear.",
  },
  df_elem: {
    en: '**Elemental**: 0.80 (disadvantage), 1.00 (neutral), or 1.20 (advantage)',
    jp: '**属性**：0.80（不利）、1.00（中立）、1.20（有利）',
    kr: '**속성**: 0.80 (불리), 1.00 (중립), 1.20 (유리)',
    zh: '**属性**：0.80（被克制）、1.00（中立）、1.20（克制）',
    fr: '**Elemental** : 0.80 (désavantage), 1.00 (neutre), ou 1.20 (avantage)',
  },
  df_marking: {
    en: '**Marking**: ×1.15 when the target carries the Marking debuff, else ×1.00',
    jp: '**マーキング**：×1.15 対象がマーキングデバフを受けている時、それ以外は×1.00',
    kr: '**마킹**: ×1.15 대상이 마킹 디버프를 받고 있을 때, 그 외에는 ×1.00',
    zh: '**标记**：×1.15 目标带有标记减益时，否则×1.00',
    fr: '**Marking** : ×1.15 lorsque la cible porte le debuff Marking, sinon ×1.00',
  },
  df_missed: {
    en: '**Missed**: ×0.5 when the attack misses (no crit, no debuff applied), else ×1.00',
    jp: '**ミス**：×0.5 攻撃がミスした時（クリティカルなし、デバフ付与なし）、それ以外は×1.00',
    kr: '**미스**: ×0.5 공격이 미스한 경우(치명타 없음, 디버프 부여 없음), 그 외에는 ×1.00',
    zh: '**未命中**：×0.5 攻击未命中时（无暴击，不施加减益），否则×1.00',
    fr: "**Missed** : ×0.5 lorsque l'attaque rate (pas de crit, pas de debuff appliqué), sinon ×1.00",
  },
  df_finalreduce: {
    en: '**FinalReduce**: `1 − pct/100` for boss-specific final-damage-reduction passives (e.g. Amadeus Prelude). Default ×1.00.',
    jp: '**最終軽減**：`1 − pct/100` ボス固有の最終ダメージ軽減パッシブ（例：アマデウス序曲）に対して。デフォルト×1.00。',
    kr: '**최종 경감**: `1 − pct/100` 보스 전용 최종 데미지 감소 패시브(예: 아마데우스 프렐류드)에 대해. 기본 ×1.00.',
    zh: '**最终减免**：`1 − pct/100` 针对首领专属的最终伤害减免被动（如阿玛迪斯前奏）。默认×1.00。',
    fr: '**FinalReduce** : `1 − pct/100` pour les passives boss-specific de Final Damage Reduction (par ex. Amadeus Prelude). Défaut ×1.00.',
  },
  df_source: {
    en: 'Source: {L/Fabool on EvaMains Discord (July 23, 2024)|https://discord.com/channels/1264787916660670605/1264811556059873312/1265103204128133191} + Outerpedia damage calc reverse-engineering',
    jp: '出典：{L/Fabool on EvaMains Discord (2024年7月23日)|https://discord.com/channels/1264787916660670605/1264811556059873312/1265103204128133191} + Outerpediaダメージ計算機のリバースエンジニアリング',
    kr: '출처: {L/Fabool on EvaMains Discord (2024년 7월 23일)|https://discord.com/channels/1264787916660670605/1264811556059873312/1265103204128133191} + Outerpedia 데미지 계산기 리버스 엔지니어링',
    zh: '来源：{L/Fabool on EvaMains Discord（2024年7月23日）|https://discord.com/channels/1264787916660670605/1264811556059873312/1265103204128133191} + Outerpedia伤害计算器逆向工程',
    fr: 'Source : {L/Fabool on EvaMains Discord (July 23, 2024)|https://discord.com/channels/1264787916660670605/1264811556059873312/1265103204128133191} + Reverse-engineering du damage calc Outerpedia',
  },

  // ── Atteindre 100% de crit (Basic Stats) ──
  crit100_title: {
    en: 'Reaching 100% Crit Chance',
    jp: 'クリ率100%の達成',
    kr: '치명타 확률 100% 달성',
    zh: '达成100%暴击率',
    fr: 'Atteindre 100% de CHC',
  },
  crit100_intro: {
    en: 'Crit Chance is capped at 100% and stacks from many sources, so it is easy to cap. Here is where it comes from (values from the game files):',
    jp: 'クリ率は100%が上限で多くのソースから累積するため、簡単に上限に達します。内訳は以下の通りです（ゲームデータの値）：',
    kr: '치명타 확률은 100%가 상한이며 여러 소스에서 누적되므로 쉽게 상한에 도달합니다. 그 출처는 다음과 같습니다(게임 데이터 값):',
    zh: '暴击率上限为100%，且可从多种来源叠加，因此很容易达到上限。其来源如下（数值来自游戏文件）：',
    fr: "Le CHC est cap à 100% et se cumule depuis de nombreuses sources, donc facile à capper. Voici d'où il vient (valeurs issues des fichiers du jeu) :",
  },
  crit_base: {
    en: '**Base:** 5% for every hero.',
    jp: '**基本：** 全ヒーロー5%。',
    kr: '**기본:** 모든 영웅 5%.',
    zh: '**基础：** 每位英雄5%。',
    fr: '**Base :** 5% pour chaque héros.',
  },
  crit_class: {
    en: '**Class:** Strikers gain an extra +5% (10% total).',
    jp: '**クラス：** ストライカーは追加で+5%（合計10%）。',
    kr: '**클래스:** 스트라이커는 추가로 +5%(합계 10%).',
    zh: '**职业：** 打击者额外获得+5%（共10%）。',
    fr: '**Classe :** les Strikers gagnent +5% supplémentaires (10% au total).',
  },
  crit_wizard: {
    en: '**Wizard subclass:** +6% from class transcendence.',
    jp: '**ウィザードサブクラス：** クラス超越から+6%。',
    kr: '**위저드 서브클래스:** 클래스 초월에서 +6%.',
    zh: '**巫师子职业：** 来自职业超越的+6%。',
    fr: '**Sous-classe Wizard :** +6% via la transcendance de classe.',
  },
  crit_quirk: {
    en: '**Element Quirk:** +10% (the three crit nodes of the element tree).',
    jp: '**属性ギフト：** +10%（属性ツリーのクリノード3つ）。',
    kr: '**속성 기프트:** +10%(속성 트리의 치명타 노드 3개).',
    zh: '**元素天赋：** +10%（元素树的3个暴击节点）。',
    fr: "**Quirk d'élément :** +10% (les trois nœuds de crit de l'arbre d'élément).",
  },
  crit_gear: {
    en: '**6★ Gear substats:** the Crit Chance substat grows per level, up to +18% per piece at level 6 — across the 6 gear slots (excluding EE and Talisman), up to +108%.',
    jp: '**6★装備サブステータス：** クリ率のサブステータスはレベルごとに増加し、レベル6で1部位最大+18% — 6つの装備スロット（EEとタリスマンを除く）で最大+108%。',
    kr: '**6★ 장비 부옵션:** 치명타 확률 부옵션은 레벨마다 증가하여 레벨 6에서 부위당 최대 +18% — 6개 장비 슬롯(EE와 탈리스만 제외)에서 최대 +108%.',
    zh: '**6★装备副属性：** 暴击率副属性随等级提升，等级6时每件最多+18%——6个装备槽（不含EE和护符）最多+108%。',
    fr: "**Substats de gear 6★ :** la substat de CHC augmente par niveau, jusqu'à +18% par pièce au niveau 6 — sur les 6 slots de gear (hors EE et Talisman), jusqu'à +108%.",
  },
  crit_accessory: {
    en: '**Accessory main stat:** an accessory can carry Crit Chance as its main stat — 8% at 6★, up to +55.2% at +15 with max breakthrough. Not recommended in late game.',
    jp: '**アクセサリーのメインステータス：** アクセサリーはメインステータスとしてクリ率を持てる — 6★で8%、最大突破の+15で最大+55.2%。ただし終盤は非推奨。',
    kr: '**액세서리 주옵션:** 액세서리는 주옵션으로 치명타 확률을 가질 수 있습니다 — 6★에서 8%, 최대 돌파의 +15에서 최대 +55.2%. 다만 후반부에는 비추천.',
    zh: '**饰品主属性：** 饰品可将暴击率作为主属性——6★时8%，满突破+15时最高+55.2%。但后期不推荐。',
    fr: "**Main stat d'accessoire :** un accessoire peut porter le CHC en stat principale — 8% au 6★, jusqu'à +55,2% au +15 avec la percée max. Déconseillé en late game.",
  },
  crit_talisman: {
    en: '**Talisman:** +7.2% to +9%, depending on its enhancement.',
    jp: '**タリスマン：** 強化に応じて+7.2%～+9%。',
    kr: '**탈리스만:** 강화에 따라 +7.2%~+9%.',
    zh: '**护符：** 根据强化+7.2%~+9%。',
    fr: '**Talisman :** +7.2% à +9%, selon son enhancement.',
  },
  crit_gems: {
    en: '**Gems (Stage 6):** +3% per gem, up to +30% across all 10 slots.',
    jp: '**ジェム（ステージ6）：** ジェム1つ+3%、全10スロットで最大+30%。',
    kr: '**젬(스테이지 6):** 젬당 +3%, 전체 10슬롯에서 최대 +30%.',
    zh: '**宝石（第6阶）：** 每颗+3%，全部10个槽位最多+30%。',
    fr: "**Gemmes (Stage 6) :** +3% par gemme, jusqu'à +30% sur les 10 slots.",
  },
  crit_buff: {
    en: '**Crit Chance buff:** in-combat Crit Chance buffs (from skills, e.g. supports) also count toward the cap during a fight.',
    jp: '**クリ率バフ：** 戦闘中のクリ率バフ（スキル由来、例：サポーター）も戦闘中は上限に加算される。',
    kr: '**치명타 확률 버프:** 전투 중 치명타 확률 버프(스킬, 예: 서포터)도 전투 중에는 상한에 합산됩니다.',
    zh: '**暴击率增益：** 战斗中的暴击率增益（来自技能，如辅助）在战斗中同样计入上限。',
    fr: '**Buff de CHC :** les buffs de CHC en combat (via compétences, ex. supports) comptent aussi vers le cap pendant un combat.',
  },
  crit100_outro: {
    en: 'Because these stack well beyond 100%, a handful of 6★ gear substats plus your class and quirk already cap you — so any crit past 100% is wasted and should be reallocated to other stats.',
    jp: 'これらは100%を大きく超えて累積するため、いくつかの6★装備サブステータスにクラスとギフトを加えるだけで上限に達します。100%を超えたクリは無駄なので、他のステータスに回すべきです。',
    kr: '이들은 100%를 크게 초과해 누적되므로, 몇 개의 6★ 장비 부옵션에 클래스와 기프트만 더해도 상한에 도달합니다. 100%를 넘는 치명타는 낭비이므로 다른 스탯에 재배분해야 합니다.',
    zh: '由于这些叠加远超100%，只需几条6★装备副属性加上职业与天赋就已封顶——超过100%的暴击都是浪费，应重新分配到其他属性。',
    fr: "Comme tout cela dépasse largement 100%, quelques substats de gear 6★ plus votre classe et votre quirk vous cappent déjà — tout crit au-delà de 100% est gâché et devrait être réalloué à d'autres stats.",
  },

  // ── Formule ATK/DEF/HP (FAQ) ──
  q_statFormulas: {
    en: 'How are ATK, DEF and HP calculated?',
    jp: 'ATK・DEF・HPはどう計算されますか？',
    kr: 'ATK, DEF, HP는 어떻게 계산되나요?',
    zh: 'ATK、DEF、HP如何计算？',
    fr: 'Comment ATK, DEF et HP sont-ils calculés ?',
  },
  statf_p1: {
    en: 'The final stat is built in layers — flat bonuses first, then percentage multipliers applied in two nested steps, with the codex bonus added on the base value at the very end. This model was reverse-engineered by **Shiraen**:',
    jp: '最終ステータスは層状に構築されます — まず固定ボーナス、次に割合乗数を2段階の入れ子で適用し、最後に図鑑ボーナスを基本値に加算します。このモデルは**Shiraen**によってリバースエンジニアリングされました：',
    kr: '최종 스탯은 층으로 구성됩니다 — 먼저 고정 보너스, 그다음 비율 배수를 2단계로 중첩 적용하고, 마지막에 도감 보너스를 기본값에 더합니다. 이 모델은 **Shiraen**이 리버스 엔지니어링했습니다:',
    zh: '最终属性分层构建——先是固定加成，再以两个嵌套步骤应用百分比乘数，最后将图鉴加成加到基础值上。此模型由**Shiraen**逆向工程得出：',
    fr: "La stat finale se construit en couches — d'abord les bonus plats, puis les multiplicateurs en pourcentage appliqués en deux étapes imbriquées, et enfin le bonus de codex ajouté à la valeur de base tout à la fin. Ce modèle a été reverse-engineered par **Shiraen** :",
  },
  statf_formula: {
    en: 'ATK = ( (Base ATK + Upgrade + Class Quirk flat ATK)\n        × (1 + Gear %ATK + 6★ Transcend %ATK)\n        + flat ATK on gear )\n      × (1 + Class Quirk %ATK + Talisman + Skill/Transcend passive %ATK)\n      + Base ATK × Codex bonus',
    jp: 'ATK = ( (Base ATK + Upgrade + Class Quirk flat ATK)\n        × (1 + Gear %ATK + 6★ Transcend %ATK)\n        + flat ATK on gear )\n      × (1 + Class Quirk %ATK + Talisman + Skill/Transcend passive %ATK)\n      + Base ATK × Codex bonus',
    kr: 'ATK = ( (Base ATK + Upgrade + Class Quirk flat ATK)\n        × (1 + Gear %ATK + 6★ Transcend %ATK)\n        + flat ATK on gear )\n      × (1 + Class Quirk %ATK + Talisman + Skill/Transcend passive %ATK)\n      + Base ATK × Codex bonus',
    zh: 'ATK = ( (Base ATK + Upgrade + Class Quirk flat ATK)\n        × (1 + Gear %ATK + 6★ Transcend %ATK)\n        + flat ATK on gear )\n      × (1 + Class Quirk %ATK + Talisman + Skill/Transcend passive %ATK)\n      + Base ATK × Codex bonus',
    fr: 'ATK = ( (Base ATK + Upgrade + Class Quirk flat ATK)\n        × (1 + Gear %ATK + 6★ Transcend %ATK)\n        + flat ATK on gear )\n      × (1 + Class Quirk %ATK + Talisman + Skill/Transcend passive %ATK)\n      + Base ATK × Codex bonus',
  },
  statf_note: {
    en: '**DEF** and **HP** follow the exact same layered structure, each with their own flat and % sources. **Affinity ATK** is applied in combat, not on the character sheet — it sits on top of this formula, not inside it. **Note:** this is community reverse-engineering, not datamined; values are a close approximation and may differ slightly from the in-game display due to per-step rounding.',
    jp: '**DEF**と**HP**もまったく同じ層状構造に従い、それぞれ固有の固定・割合ソースを持ちます。**親密度ATK**はキャラシートではなく戦闘中に適用されます — この計算式の内側ではなく上に乗ります。**注意：** これはコミュニティによるリバースエンジニアリングであり、データマイニングではありません。値は近似であり、各段階の丸めによりゲーム内表示と若干異なる場合があります。',
    kr: '**DEF**와 **HP**도 완전히 동일한 층 구조를 따르며 각자 고정·비율 소스를 가집니다. **친밀도 ATK**는 캐릭터 시트가 아닌 전투 중에 적용됩니다 — 이 공식 안이 아니라 위에 얹힙니다. **참고:** 이것은 커뮤니티의 리버스 엔지니어링이며 데이터마이닝이 아닙니다. 값은 근사치이며 단계별 반올림으로 인해 인게임 표시와 약간 다를 수 있습니다.',
    zh: '**DEF**和**HP**遵循完全相同的分层结构，各有自己的固定与百分比来源。**好感度ATK**在战斗中生效，而非角色面板——它叠加在此公式之上，而非其中。**注意：** 这是社区逆向工程，并非数据挖掘；数值为近似值，且因逐步取整可能与游戏内显示略有差异。',
    fr: "**DEF** et **HP** suivent exactement la même structure en couches, chacune avec ses propres sources plates et en %. L'**ATK d'affinity** est appliquée en combat, pas sur la fiche du personnage — elle se pose au-dessus de cette formule, pas à l'intérieur. **Note :** il s'agit de reverse-engineering communautaire, pas de datamining ; les valeurs sont une approximation proche et peuvent différer légèrement de l'affichage en jeu à cause des arrondis à chaque étape.",
  },
} satisfies Record<string, LocalizedText>;
