// lib/team-planner/bossPresetsData.ts
//
// AUTO-GENERATED by scripts/generate-boss-presets.mjs
// Do NOT edit this file manually — add "presetRules" to a boss JSON and re-run the script.
//
// To add a new boss preset:
//   1. Add a "presetRules" array to the boss JSON in src/data/boss/
//   2. Run: node scripts/generate-boss-presets.mjs

import type { RuleType, BossPreset } from '@/types/team-planner'

// ============================================================================
// Types
// ============================================================================

export interface RuleShorthand {
  type: RuleType
  value?: number
}

export interface PresetDefinition {
  boss: {
    id: string
    Name: { en: string; kr?: string; jp?: string; zh?: string }
    element: string
    class: string
    icons: string
    location: { mode: { en: string } }
  }
  rules: RuleShorthand[]
  opts?: {
    difficulty?: BossPreset['difficulty']
    category?: BossPreset['category']
    description?: string
  }
}

// ============================================================================
// Preset definitions
// ============================================================================

export const PRESET_DEFINITIONS: PresetDefinition[] = [
  // ===== SPECIAL REQUEST =====
  {
    boss: {
      id: '403400262',
      Name: { en: 'Unidentified Chimera', kr: '미확인 키메라', jp: '未確認キメラ', zh: '未知的奇美拉' },
      element: 'Earth',
      class: 'Mage',
      icons: '4034002',
      location: { mode: { en: 'Special Request: Ecology Study' } },
    },
    rules: [
      { type: 'bonus_fire' },
      { type: 'require_crit_damage_buff' },
      { type: 'require_defense_break' },
    ],
  },
]
